import { useAuth } from "@/_core/hooks/useAuth";
import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, BookOpenCheck, CheckCircle2, ClipboardCheck, Database, Gamepad2, ShieldAlert, UsersRound, Wrench } from "lucide-react";
import { useEffect, useState } from "react";

type PublicationStatus = "draft" | "published" | "archived";
type Difficulty = "beginner" | "intermediate" | "advanced";
type FixCategory = "steam" | "proton" | "wine" | "vulkan" | "amd" | "nvidia" | "intel" | "anti_cheat" | "audio" | "controller" | "fps" | "stuttering" | "crashes" | "black_screen" | "launch_errors" | "other";
type EditorialStep = { title: string; explanation?: string | null; command?: string | null; warning?: string | null };

const FIX_CATEGORIES: FixCategory[] = ["steam", "proton", "wine", "vulkan", "amd", "nvidia", "intel", "anti_cheat", "audio", "controller", "fps", "stuttering", "crashes", "black_screen", "launch_errors", "other"];
const EMPTY_GUIDE_STEPS = JSON.stringify([{ title: "Passo 1", explanation: "Descreva a ação e o contexto.", command: null, warning: null }], null, 2);
const EMPTY_FIX_SOLUTIONS = JSON.stringify([{ title: "Etapa 1", explanation: "Descreva a correção e sua justificativa.", command: null, warning: null }], null, 2);

export default function Admin() {
  const { user } = useAuth();
  const isAdmin = user?.role === "admin";
  const utils = trpc.useUtils();
  const overview = trpc.admin.overview.useQuery(undefined, { enabled: isAdmin });
  const games = trpc.admin.games.list.useQuery(undefined, { enabled: isAdmin });
  const distros = trpc.admin.distributions.list.useQuery(undefined, { enabled: isAdmin });
  const hardware = trpc.admin.hardware.list.useQuery(undefined, { enabled: isAdmin });
  const guides = trpc.admin.guides.list.useQuery(undefined, { enabled: isAdmin });
  const fixes = trpc.admin.linuxFix.list.useQuery(undefined, { enabled: isAdmin });
  const benchmarkRecords = trpc.admin.benchmarks.list.useQuery(undefined, { enabled: isAdmin });
  const reportRecords = trpc.admin.reports.list.useQuery(undefined, { enabled: isAdmin });
  const benchmarks = trpc.admin.moderation.benchmarks.useQuery(undefined, { enabled: isAdmin });
  const reports = trpc.admin.moderation.reports.useQuery(undefined, { enabled: isAdmin });
  const users = trpc.admin.users.list.useQuery(undefined, { enabled: isAdmin });
  const audit = trpc.admin.audit.useQuery(undefined, { enabled: isAdmin });
  const reviewBenchmark = trpc.benchmarks.review.useMutation({ onSuccess: () => { utils.admin.moderation.benchmarks.invalidate(); utils.admin.overview.invalidate(); } });
  const reviewReport = trpc.admin.moderation.reviewReport.useMutation({ onSuccess: () => { utils.admin.moderation.reports.invalidate(); utils.admin.overview.invalidate(); } });
  const removeBenchmark = trpc.admin.moderation.removeBenchmark.useMutation({ onSuccess: () => { utils.admin.moderation.benchmarks.invalidate(); utils.admin.overview.invalidate(); } });
  const removeReport = trpc.admin.moderation.removeReport.useMutation({ onSuccess: () => { utils.admin.moderation.reports.invalidate(); utils.admin.overview.invalidate(); } });
  const setRole = trpc.admin.users.setRole.useMutation({ onSuccess: () => utils.admin.users.list.invalidate() });
  const setBan = trpc.admin.users.setBan.useMutation({ onSuccess: () => utils.admin.users.list.invalidate() });

  if (!isAdmin) return <DashboardLayout><AccessDenied /></DashboardLayout>;
  if (overview.isError) return <DashboardLayout><AdminUnavailable /></DashboardLayout>;

  return <DashboardLayout><div className="mx-auto max-w-6xl space-y-6">
    <header className="diagnostic-panel rounded-2xl border border-primary/15 p-5 md:p-7"><div className="relative z-10"><p className="evidence-label text-primary">ADMINISTRAÇÃO / CONTROL PLANE</p><h1 className="mt-3 text-3xl font-semibold tracking-tight md:text-4xl">Conteúdo, moderação e rastreabilidade.</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-muted-foreground">Toda publicação exige fonte; decisões administrativas preservam uma trilha de auditoria. As métricas abaixo são indicadores operacionais, não avaliações de qualidade editorial.</p></div></header>
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><Stat icon={Gamepad2} label="Jogos" value={overview.data?.games} /><Stat icon={BookOpenCheck} label="Distros" value={overview.data?.distributions} /><Stat icon={Wrench} label="Hardware" value={overview.data?.hardware} /><Stat icon={ClipboardCheck} label="Benchmarks pendentes" value={overview.data?.pendingBenchmarks} warn /><Stat icon={ShieldAlert} label="Reports abertos" value={overview.data?.openReports} warn /></div>
    <Tabs defaultValue="catalog"><TabsList className="h-auto flex-wrap justify-start gap-1 bg-transparent p-0"><TabsTrigger value="catalog">Catálogo</TabsTrigger><TabsTrigger value="editorial">Conteúdo editorial</TabsTrigger><TabsTrigger value="records">Registros</TabsTrigger><TabsTrigger value="moderation">Moderação</TabsTrigger><TabsTrigger value="users">Usuários</TabsTrigger><TabsTrigger value="audit">Auditoria</TabsTrigger></TabsList>
      <TabsContent value="catalog" className="mt-5 space-y-5"><div className="flex items-center justify-between rounded-xl border border-primary/15 bg-card/70 px-4 py-3"><span className="evidence-label text-primary">CATÁLOGO / MANUTENÇÃO</span><span className="text-xs text-muted-foreground">Publicação condicionada à fonte</span></div><div className="grid gap-5 xl:grid-cols-3"><CatalogEditor kind="game" items={games.data ?? []} /><CatalogEditor kind="distribution" items={distros.data ?? []} /><CatalogEditor kind="hardware" items={hardware.data ?? []} /></div></TabsContent>
      <TabsContent value="editorial" className="mt-5 grid gap-5 xl:grid-cols-2"><GuideEditor items={guides.data ?? []} onSaved={() => utils.admin.guides.list.invalidate()} /><FixEditor items={fixes.data ?? []} onSaved={() => utils.admin.linuxFix.list.invalidate()} /></TabsContent>
      <TabsContent value="records" className="mt-5 grid gap-5 xl:grid-cols-2"><BenchmarkEditor items={benchmarkRecords.data ?? []} games={games.data ?? []} onSaved={() => utils.admin.benchmarks.list.invalidate()} /><ReportEditor items={reportRecords.data ?? []} onSaved={() => utils.admin.reports.list.invalidate()} /></TabsContent>
      <TabsContent value="moderation" className="mt-5 grid gap-5 lg:grid-cols-2"><Card><CardHeader><CardTitle>Benchmarks aguardando revisão</CardTitle><CardDescription>Confirme fonte e ambiente antes de promover qualquer FPS a verificado.</CardDescription></CardHeader><CardContent className="space-y-3">{benchmarks.data?.length ? benchmarks.data.map(({ benchmark, gameTitle }) => <div key={benchmark.id} className="rounded-xl border p-4"><p className="font-medium">{gameTitle}</p><p className="mt-1 text-xs text-muted-foreground">{benchmark.sourceLabel || "Sem rótulo"} · {benchmark.provenance}</p>{benchmark.sourceUrl ? <a className="mt-2 block truncate text-xs text-primary hover:underline" href={benchmark.sourceUrl} target="_blank" rel="noreferrer">{benchmark.sourceUrl}</a> : null}<div className="mt-3 flex flex-wrap gap-2"><Button size="sm" onClick={() => reviewBenchmark.mutate({ id: benchmark.id, decision: "verified", reviewNote: "Fonte e ambiente revisados pela administração." })}><CheckCircle2 className="mr-1.5 h-3.5 w-3.5" />Verificar</Button><Button size="sm" variant="outline" onClick={() => reviewBenchmark.mutate({ id: benchmark.id, decision: "rejected", reviewNote: "Evidência insuficiente após revisão." })}>Rejeitar</Button><Button size="sm" variant="ghost" className="text-destructive" onClick={() => removeBenchmark.mutate({ id: benchmark.id, reason: "Remoção administrativa após revisão." })}>Remover</Button></div></div>) : <Empty title="Nenhum benchmark pendente" text="Submissões comunitárias com evidência aparecem nesta fila." />}</CardContent></Card><Card><CardHeader><CardTitle>Reports em análise</CardTitle><CardDescription>Resolva ou rejeite o report sem remover o histórico de decisão.</CardDescription></CardHeader><CardContent className="space-y-3">{reports.data?.length ? reports.data.map(({ report, reporterName }) => <div key={report.id} className="rounded-xl border p-4"><p className="font-medium capitalize">{report.type.replaceAll("_", " ")}</p><p className="mt-1 text-sm text-muted-foreground">{report.description}</p><p className="mt-2 text-xs text-muted-foreground">Por {reporterName || "usuário"} · alvo {report.subjectType} #{report.subjectId}</p><div className="mt-3 flex flex-wrap gap-2"><Button size="sm" onClick={() => reviewReport.mutate({ id: report.id, status: "resolved", resolution: "Report revisado e resolvido pela administração." })}>Resolver</Button><Button size="sm" variant="outline" onClick={() => reviewReport.mutate({ id: report.id, status: "rejected", resolution: "Report rejeitado após revisão." })}>Rejeitar</Button><Button size="sm" variant="ghost" className="text-destructive" onClick={() => removeReport.mutate({ id: report.id, reason: "Remoção administrativa após revisão." })}>Remover</Button></div></div>) : <Empty title="Nenhum report pendente" text="Reports enviados pela comunidade aparecerão aqui." />}</CardContent></Card></TabsContent>
      <TabsContent value="users" className="mt-5"><Card><CardHeader><CardTitle>Usuários e roles</CardTitle><CardDescription>Bloqueios impedem procedimentos protegidos; mudanças de role são auditadas.</CardDescription></CardHeader><CardContent className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="border-b text-xs text-muted-foreground"><tr><th className="p-3">Usuário</th><th className="p-3">Role</th><th className="p-3">Status</th><th className="p-3">Ações</th></tr></thead><tbody>{users.data?.map((entry) => <tr key={entry.id} className="border-b last:border-0"><td className="p-3"><p className="font-medium">{entry.name || "Sem nome"}</p><p className="text-xs text-muted-foreground">{entry.email}</p></td><td className="p-3"><select className="h-8 rounded-md border bg-background px-2 text-xs" value={entry.role} onChange={(event) => setRole.mutate({ userId: entry.id, role: event.target.value as "user" | "moderator" | "admin" })}><option value="user">USER</option><option value="moderator">MODERATOR</option><option value="admin">ADMIN</option></select></td><td className="p-3">{entry.isBanned ? "Bloqueado" : "Ativo"}</td><td className="p-3"><Button size="sm" variant="outline" onClick={() => setBan.mutate({ userId: entry.id, isBanned: !entry.isBanned })}>{entry.isBanned ? "Desbloquear" : "Bloquear"}</Button></td></tr>)}</tbody></table></CardContent></Card></TabsContent>
      <TabsContent value="audit" className="mt-5"><Card><CardHeader><CardTitle>Audit log</CardTitle><CardDescription>Operações administrativas recentes.</CardDescription></CardHeader><CardContent className="space-y-2">{audit.data?.map((entry) => <div key={entry.id} className="flex flex-wrap items-center justify-between gap-2 rounded-lg border p-3 text-sm"><span><strong>{entry.action}</strong> · {entry.entityType} #{entry.entityId}</span><span className="text-xs text-muted-foreground">{new Date(entry.createdAt).toLocaleString("pt-BR")}</span></div>)}</CardContent></Card></TabsContent>
    </Tabs></div></DashboardLayout>;
}

function CatalogEditor({ kind, items }: { kind: "game" | "distribution" | "hardware"; items: any[] }) {
  const [selected, setSelected] = useState(""); const [name, setName] = useState(""); const [slug, setSlug] = useState(""); const [detail, setDetail] = useState(""); const [sourceUrl, setSourceUrl] = useState(""); const utils = trpc.useUtils();
  const reset = () => { setSelected(""); setName(""); setSlug(""); setDetail(""); setSourceUrl(""); };
  const game = trpc.admin.games.save.useMutation({ onSuccess: () => utils.admin.games.list.invalidate() }); const distro = trpc.admin.distributions.save.useMutation({ onSuccess: () => utils.admin.distributions.list.invalidate() }); const hardware = trpc.admin.hardware.save.useMutation({ onSuccess: () => utils.admin.hardware.list.invalidate() }); const archiveGame = trpc.admin.games.archive.useMutation({ onSuccess: () => { utils.admin.games.list.invalidate(); reset(); } }); const archiveDistro = trpc.admin.distributions.archive.useMutation({ onSuccess: () => { utils.admin.distributions.list.invalidate(); reset(); } }); const archiveHardware = trpc.admin.hardware.archive.useMutation({ onSuccess: () => { utils.admin.hardware.list.invalidate(); reset(); } });
  useEffect(() => { const entry = items.find((item) => String(item.id) === selected); if (!entry) return; setName(kind === "hardware" ? entry.model : kind === "distribution" ? entry.name : entry.title); setSlug(entry.slug); setDetail(kind === "hardware" ? entry.manufacturer : kind === "distribution" ? entry.family || "" : entry.shortDescription || ""); setSourceUrl(entry.sourceUrl || ""); }, [items, kind, selected]);
  const submit = () => { const id = selected ? Number(selected) : undefined; if (kind === "game") game.mutate({ id, title: name, slug, shortDescription: detail || null, steamAppId: null, status: sourceUrl ? "published" : "draft", sourceUrl: sourceUrl || null }); if (kind === "distribution") distro.mutate({ id, name, slug, family: detail || null, packageManager: null, officialUrl: sourceUrl || null, status: sourceUrl ? "published" : "draft", sourceUrl: sourceUrl || null }); if (kind === "hardware") hardware.mutate({ id, slug, kind: "gpu", manufacturer: detail || "Não informado", model: name, architecture: null, vramMb: null, sourceUrl: sourceUrl || null }); }; const archive = () => { if (!selected) return; if (kind === "game") archiveGame.mutate({ id: Number(selected) }); if (kind === "distribution") archiveDistro.mutate({ id: Number(selected) }); if (kind === "hardware") archiveHardware.mutate({ id: Number(selected) }); };
  const label = kind === "game" ? "Jogo" : kind === "distribution" ? "Distribuição" : "Hardware"; return <Card><CardHeader><CardTitle>{label}</CardTitle><CardDescription>Selecione para editar ou deixe vazio para criar. Publicação requer fonte.</CardDescription></CardHeader><CardContent className="space-y-3"><select className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={selected} onChange={(event) => event.target.value ? setSelected(event.target.value) : reset()}><option value="">Novo {label.toLowerCase()}</option>{items.slice(0, 100).map((item) => <option key={item.id} value={item.id}>{kind === "hardware" ? `${item.manufacturer} ${item.model}` : kind === "distribution" ? item.name : item.title}</option>)}</select><Input value={name} onChange={(event) => setName(event.target.value)} placeholder={kind === "hardware" ? "Modelo" : "Nome"} /><Input value={slug} onChange={(event) => setSlug(event.target.value)} placeholder="slug-unico" /><Input value={detail} onChange={(event) => setDetail(event.target.value)} placeholder={kind === "hardware" ? "Fabricante" : kind === "distribution" ? "Família" : "Resumo"} /><Input value={sourceUrl} onChange={(event) => setSourceUrl(event.target.value)} placeholder="https://fonte.example" /><div className="flex gap-2"><Button size="sm" onClick={submit} disabled={!name || !slug}>Salvar</Button>{selected ? <Button size="sm" variant="outline" onClick={archive}>Arquivar</Button> : null}<Button size="sm" variant="ghost" onClick={reset}>Limpar</Button></div></CardContent></Card>;
}

function GuideEditor({ items, onSaved }: { items: any[]; onSaved: () => void }) {
  const [selected, setSelected] = useState(""); const detail = trpc.admin.guides.byId.useQuery({ id: Number(selected) || 1 }, { enabled: Boolean(selected) }); const [title, setTitle] = useState(""); const [slug, setSlug] = useState(""); const [description, setDescription] = useState(""); const [difficulty, setDifficulty] = useState<Difficulty>("beginner"); const [sourceUrl, setSourceUrl] = useState(""); const [status, setStatus] = useState<PublicationStatus>("draft"); const [steps, setSteps] = useState(EMPTY_GUIDE_STEPS); const [error, setError] = useState(""); const utils = trpc.useUtils();
  const save = trpc.admin.guides.save.useMutation({ onSuccess: (result) => { setSelected(String(result.id)); onSaved(); utils.admin.guides.byId.invalidate(); setError(""); } }); const archive = trpc.admin.guides.archive.useMutation({ onSuccess: () => { reset(); onSaved(); } });
  useEffect(() => { if (!detail.data) return; const { guide, steps: value } = detail.data; setTitle(guide.title); setSlug(guide.slug); setDescription(guide.description || ""); setDifficulty(guide.difficulty); setSourceUrl(guide.sourceUrl || ""); setStatus(guide.status); setSteps(JSON.stringify(value.map((step) => ({ title: step.title, explanation: step.explanation, command: step.command, warning: step.warning })), null, 2)); }, [detail.data]);
  const reset = () => { setSelected(""); setTitle(""); setSlug(""); setDescription(""); setDifficulty("beginner"); setSourceUrl(""); setStatus("draft"); setSteps(EMPTY_GUIDE_STEPS); setError(""); };
  const submit = () => { try { const parsed = JSON.parse(steps) as EditorialStep[]; if (!Array.isArray(parsed) || !parsed.length) throw new Error("Informe ao menos uma etapa."); save.mutate({ id: selected ? Number(selected) : undefined, title, slug, description: description || null, difficulty, guideVersion: null, distributionId: null, distributionVersionId: null, gameId: null, provenance: "verified", sourceUrl: sourceUrl || null, status, steps: parsed }); } catch (err) { setError(err instanceof Error ? err.message : "JSON de etapas inválido."); } };
  return <Card><CardHeader><CardTitle>Linux Setup</CardTitle><CardDescription>Etapas são atualizadas integralmente e recebem ordenação automática.</CardDescription></CardHeader><CardContent className="space-y-3"><select className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={selected} onChange={(event) => event.target.value ? setSelected(event.target.value) : reset()}><option value="">Novo guia</option>{items.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select><Input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Título" /><Input value={slug} onChange={(event) => setSlug(event.target.value)} placeholder="slug-do-guia" /><Textarea value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Resumo e escopo" /><div className="grid grid-cols-2 gap-3"><select className="h-10 rounded-md border bg-background px-3 text-sm" value={difficulty} onChange={(event) => setDifficulty(event.target.value as Difficulty)}><option value="beginner">Iniciante</option><option value="intermediate">Intermediário</option><option value="advanced">Avançado</option></select><StatusSelect value={status} onChange={setStatus} /></div><Input value={sourceUrl} onChange={(event) => setSourceUrl(event.target.value)} placeholder="https://fonte-oficial.example" /><Textarea className="min-h-44 font-mono text-xs" value={steps} onChange={(event) => setSteps(event.target.value)} placeholder="JSON de etapas" />{error ? <p className="text-xs text-destructive">{error}</p> : null}<div className="flex gap-2"><Button size="sm" onClick={submit} disabled={!title || !slug || save.isPending}>Salvar</Button>{selected ? <Button size="sm" variant="outline" onClick={() => archive.mutate({ id: Number(selected) })}>Arquivar</Button> : null}<Button size="sm" variant="ghost" onClick={reset}>Limpar</Button></div></CardContent></Card>;
}

function FixEditor({ items, onSaved }: { items: any[]; onSaved: () => void }) {
  const [selected, setSelected] = useState(""); const detail = trpc.admin.linuxFix.byId.useQuery({ id: Number(selected) || 1 }, { enabled: Boolean(selected) }); const [title, setTitle] = useState(""); const [slug, setSlug] = useState(""); const [category, setCategory] = useState<FixCategory>("steam"); const [symptoms, setSymptoms] = useState(""); const [causes, setCauses] = useState(""); const [sourceUrl, setSourceUrl] = useState(""); const [status, setStatus] = useState<PublicationStatus>("draft"); const [solutions, setSolutions] = useState(EMPTY_FIX_SOLUTIONS); const [error, setError] = useState(""); const utils = trpc.useUtils();
  const save = trpc.admin.linuxFix.save.useMutation({ onSuccess: (result) => { setSelected(String(result.id)); onSaved(); utils.admin.linuxFix.byId.invalidate(); setError(""); } }); const archive = trpc.admin.linuxFix.archive.useMutation({ onSuccess: () => { reset(); onSaved(); } });
  useEffect(() => { if (!detail.data) return; const { fix, solutions: value } = detail.data; setTitle(fix.title); setSlug(fix.slug); setCategory(fix.category as FixCategory); setSymptoms(fix.symptoms); setCauses(fix.possibleCauses); setSourceUrl(fix.sourceUrl || ""); setStatus(fix.status); setSolutions(JSON.stringify(value.map((solution) => ({ title: solution.title, explanation: solution.explanation, command: solution.command, warning: solution.warning })), null, 2)); }, [detail.data]);
  const reset = () => { setSelected(""); setTitle(""); setSlug(""); setCategory("steam"); setSymptoms(""); setCauses(""); setSourceUrl(""); setStatus("draft"); setSolutions(EMPTY_FIX_SOLUTIONS); setError(""); };
  const submit = () => { try { const parsed = JSON.parse(solutions) as EditorialStep[]; if (!Array.isArray(parsed) || !parsed.length) throw new Error("Informe ao menos uma solução."); save.mutate({ id: selected ? Number(selected) : undefined, title, slug, category, symptoms, possibleCauses: causes, gameId: null, distributionId: null, hardwareId: null, affectedVersion: null, confidence: "medium", provenance: "verified", sourceUrl: sourceUrl || null, status, solutions: parsed }); } catch (err) { setError(err instanceof Error ? err.message : "JSON de soluções inválido."); } };
  return <Card><CardHeader><CardTitle>LinuxFix</CardTitle><CardDescription>Diagnóstico, causa e soluções possuem fonte e status de publicação independentes.</CardDescription></CardHeader><CardContent className="space-y-3"><select className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={selected} onChange={(event) => event.target.value ? setSelected(event.target.value) : reset()}><option value="">Nova solução</option>{items.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select><Input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Título" /><Input value={slug} onChange={(event) => setSlug(event.target.value)} placeholder="slug-da-correcao" /><select className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={category} onChange={(event) => setCategory(event.target.value as FixCategory)}>{FIX_CATEGORIES.map((item) => <option key={item} value={item}>{item.replaceAll("_", " ")}</option>)}</select><Textarea value={symptoms} onChange={(event) => setSymptoms(event.target.value)} placeholder="Sintomas observados" /><Textarea value={causes} onChange={(event) => setCauses(event.target.value)} placeholder="Causas prováveis" /><div className="grid grid-cols-2 gap-3"><StatusSelect value={status} onChange={setStatus} /><Input value={sourceUrl} onChange={(event) => setSourceUrl(event.target.value)} placeholder="https://fonte-oficial.example" /></div><Textarea className="min-h-44 font-mono text-xs" value={solutions} onChange={(event) => setSolutions(event.target.value)} placeholder="JSON de soluções" />{error ? <p className="text-xs text-destructive">{error}</p> : null}<div className="flex gap-2"><Button size="sm" onClick={submit} disabled={!title || !slug || !symptoms || !causes || save.isPending}>Salvar</Button>{selected ? <Button size="sm" variant="outline" onClick={() => archive.mutate({ id: Number(selected) })}>Arquivar</Button> : null}<Button size="sm" variant="ghost" onClick={reset}>Limpar</Button></div></CardContent></Card>;
}

function BenchmarkEditor({ items, games, onSaved }: { items: any[]; games: any[]; onSaved: () => void }) {
  const [selected, setSelected] = useState(""); const detail = trpc.admin.benchmarks.byId.useQuery({ id: Number(selected) || 1 }, { enabled: Boolean(selected) }); const [gameId, setGameId] = useState(""); const [sourceLabel, setSourceLabel] = useState(""); const [sourceUrl, setSourceUrl] = useState(""); const [status, setStatus] = useState<"submitted" | "in_review" | "verified" | "rejected">("submitted"); const [provenance, setProvenance] = useState<"verified" | "community" | "estimated" | "unknown">("verified"); const [results, setResults] = useState("[]"); const [error, setError] = useState(""); const utils = trpc.useUtils();
  const save = trpc.admin.benchmarks.save.useMutation({ onSuccess: (result) => { setSelected(String(result.id)); onSaved(); utils.admin.benchmarks.byId.invalidate(); setError(""); } }); const remove = trpc.admin.benchmarks.remove.useMutation({ onSuccess: () => { reset(); onSaved(); } });
  useEffect(() => { if (!detail.data) return; const { benchmark, results: value } = detail.data; setGameId(String(benchmark.gameId)); setSourceLabel(benchmark.sourceLabel || ""); setSourceUrl(benchmark.sourceUrl || ""); setStatus(benchmark.verificationStatus); setProvenance(benchmark.provenance); setResults(JSON.stringify(value.map((result) => ({ resolutionWidth: result.resolutionWidth, resolutionHeight: result.resolutionHeight, preset: result.preset, averageFps: Number(result.averageFps), onePercentLowFps: result.onePercentLowFps ? Number(result.onePercentLowFps) : null, zeroPointOnePercentLowFps: result.zeroPointOnePercentLowFps ? Number(result.zeroPointOnePercentLowFps) : null })), null, 2)); }, [detail.data]);
  const reset = () => { setSelected(""); setGameId(""); setSourceLabel(""); setSourceUrl(""); setStatus("submitted"); setProvenance("verified"); setResults("[]"); setError(""); };
  const submit = () => { try { const parsed = JSON.parse(results); if (!Array.isArray(parsed) || !parsed.length) throw new Error("Informe pelo menos um resultado medido."); save.mutate({ id: selected ? Number(selected) : undefined, gameId: Number(gameId), cpuId: null, gpuId: null, distributionId: null, distributionVersionId: null, gameVersion: null, kernelVersion: null, driverVersion: null, protonVersion: null, wineVersion: null, runtimeVersion: null, sourceLabel, sourceUrl, evidenceNote: null, provenance, verificationStatus: status, measuredAt: null, results: parsed }); } catch (err) { setError(err instanceof Error ? err.message : "JSON de resultados inválido."); } };
  return <Card><CardHeader><CardTitle>Benchmark</CardTitle><CardDescription>Crie ou edite registros reais. FPS médio e URL de fonte são obrigatórios.</CardDescription></CardHeader><CardContent className="space-y-3"><select className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={selected} onChange={(event) => event.target.value ? setSelected(event.target.value) : reset()}><option value="">Novo benchmark</option>{items.map((item) => <option key={item.benchmark.id} value={item.benchmark.id}>{item.gameTitle} · #{item.benchmark.id}</option>)}</select><select className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={gameId} onChange={(event) => setGameId(event.target.value)}><option value="">Selecione o jogo</option>{games.map((game) => <option key={game.id} value={game.id}>{game.title}</option>)}</select><Input value={sourceLabel} onChange={(event) => setSourceLabel(event.target.value)} placeholder="Rótulo da fonte" /><Input value={sourceUrl} onChange={(event) => setSourceUrl(event.target.value)} placeholder="https://fonte-rastreavel.example" /><div className="grid grid-cols-2 gap-3"><select className="h-10 rounded-md border bg-background px-3 text-sm" value={status} onChange={(event) => setStatus(event.target.value as typeof status)}><option value="submitted">Submetido</option><option value="in_review">Em revisão</option><option value="verified">Verificado</option><option value="rejected">Rejeitado</option></select><select className="h-10 rounded-md border bg-background px-3 text-sm" value={provenance} onChange={(event) => setProvenance(event.target.value as typeof provenance)}><option value="verified">Verified</option><option value="community">Community</option><option value="estimated">Estimated</option><option value="unknown">Unknown</option></select></div><Textarea className="min-h-40 font-mono text-xs" value={results} onChange={(event) => setResults(event.target.value)} placeholder="JSON de resultados" />{error ? <p className="text-xs text-destructive">{error}</p> : null}<div className="flex gap-2"><Button size="sm" disabled={!gameId || !sourceLabel || !sourceUrl || save.isPending} onClick={submit}>Salvar</Button>{selected ? <Button size="sm" variant="outline" onClick={() => remove.mutate({ id: Number(selected), reason: "Remoção administrativa de registro." })}>Remover</Button> : null}<Button size="sm" variant="ghost" onClick={reset}>Limpar</Button></div></CardContent></Card>;
}

function ReportEditor({ items, onSaved }: { items: any[]; onSaved: () => void }) {
  const [selected, setSelected] = useState(""); const [subjectType, setSubjectType] = useState("game"); const [subjectId, setSubjectId] = useState(""); const [type, setType] = useState<"incorrect_information" | "invalid_benchmark" | "duplicate" | "broken_link" | "inappropriate_content" | "spam" | "other">("other"); const [description, setDescription] = useState(""); const [status, setStatus] = useState<"open" | "in_review" | "resolved" | "rejected">("open"); const [resolution, setResolution] = useState(""); const utils = trpc.useUtils(); const save = trpc.admin.reports.save.useMutation({ onSuccess: (result) => { setSelected(String(result.id)); onSaved(); } }); const remove = trpc.admin.reports.remove.useMutation({ onSuccess: () => { reset(); onSaved(); } });
  useEffect(() => { const entry = items.find((item) => String(item.report.id) === selected)?.report; if (!entry) return; setSubjectType(entry.subjectType); setSubjectId(String(entry.subjectId)); setType(entry.type); setDescription(entry.description); setStatus(entry.status); setResolution(entry.resolution || ""); }, [items, selected]); const reset = () => { setSelected(""); setSubjectType("game"); setSubjectId(""); setType("other"); setDescription(""); setStatus("open"); setResolution(""); };
  return <Card><CardHeader><CardTitle>Report</CardTitle><CardDescription>Crie, edite, resolva ou remova reports com registro de auditoria.</CardDescription></CardHeader><CardContent className="space-y-3"><select className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={selected} onChange={(event) => event.target.value ? setSelected(event.target.value) : reset()}><option value="">Novo report</option>{items.map((item) => <option key={item.report.id} value={item.report.id}>#{item.report.id} · {item.report.type.replaceAll("_", " ")}</option>)}</select><div className="grid grid-cols-2 gap-3"><Input value={subjectType} onChange={(event) => setSubjectType(event.target.value)} placeholder="Tipo de alvo" /><Input value={subjectId} onChange={(event) => setSubjectId(event.target.value)} placeholder="ID do alvo" /></div><select className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={type} onChange={(event) => setType(event.target.value as typeof type)}>{["incorrect_information", "invalid_benchmark", "duplicate", "broken_link", "inappropriate_content", "spam", "other"].map((item) => <option key={item} value={item}>{item.replaceAll("_", " ")}</option>)}</select><Textarea value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Descrição" /><div className="grid grid-cols-2 gap-3"><select className="h-10 rounded-md border bg-background px-3 text-sm" value={status} onChange={(event) => setStatus(event.target.value as typeof status)}><option value="open">Aberto</option><option value="in_review">Em revisão</option><option value="resolved">Resolvido</option><option value="rejected">Rejeitado</option></select><Input value={resolution} onChange={(event) => setResolution(event.target.value)} placeholder="Resolução (opcional)" /></div><div className="flex gap-2"><Button size="sm" disabled={!subjectId || description.length < 8 || save.isPending} onClick={() => save.mutate({ id: selected ? Number(selected) : undefined, subjectType, subjectId: Number(subjectId), type, description, status, resolution: resolution || null })}>Salvar</Button>{selected ? <Button size="sm" variant="outline" onClick={() => remove.mutate({ id: Number(selected), reason: "Remoção administrativa de report." })}>Remover</Button> : null}<Button size="sm" variant="ghost" onClick={reset}>Limpar</Button></div></CardContent></Card>;
}

function StatusSelect({ value, onChange }: { value: PublicationStatus; onChange: (value: PublicationStatus) => void }) { return <select className="h-10 rounded-md border bg-background px-3 text-sm" value={value} onChange={(event) => onChange(event.target.value as PublicationStatus)}><option value="draft">Rascunho</option><option value="published">Publicado</option><option value="archived">Arquivado</option></select>; }
function Stat({ icon: Icon, label, value, warn = false }: { icon: typeof Database; label: string; value: number | undefined; warn?: boolean }) { return <Card className="diagnostic-panel border-primary/15"><CardContent className="relative z-10 flex items-center gap-3 p-4"><Icon className={`h-5 w-5 ${warn ? "text-amber-500" : "text-primary"}`} /><div><p className="text-xl font-semibold">{value ?? "—"}</p><p className="evidence-label mt-1 text-[8px] text-muted-foreground">{label}</p></div></CardContent></Card>; }
function Empty({ title, text }: { title: string; text: string }) { return <div className="rounded-xl border border-dashed bg-muted/20 p-6 text-center"><AlertTriangle className="mx-auto h-5 w-5 text-muted-foreground" /><p className="evidence-label mt-3 text-primary">FILA OPERACIONAL</p><p className="mt-2 font-medium">{title}</p><p className="mt-1 text-sm text-muted-foreground">{text}</p></div>; }
function AccessDenied() { return <div className="mx-auto max-w-xl pt-16 text-center"><ShieldAlert className="mx-auto h-9 w-9 text-amber-500" /><h1 className="mt-5 text-2xl font-semibold">Acesso administrativo necessário</h1><p className="mt-2 text-sm leading-6 text-muted-foreground">Esta área é visível apenas para usuários com role ADMIN.</p></div>; }
function AdminUnavailable() { return <div className="mx-auto max-w-xl pt-16 text-center"><AlertTriangle className="mx-auto h-9 w-9 text-amber-500" /><p className="evidence-label mt-5 text-primary">FALHA DE CONSULTA</p><h1 className="mt-2 text-2xl font-semibold">O painel administrativo não carregou</h1><p className="mt-2 text-sm leading-6 text-muted-foreground">Não interprete métricas ausentes como filas vazias. Tente recarregar antes de tomar uma decisão de moderação.</p></div>; }
