import { SiteHeader } from "@/components/platform/SiteHeader";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { groupBenchmarkEvidence } from "@/lib/benchmarkComparison";
import { trpc } from "@/lib/trpc";
import { BarChart3, DatabaseZap, ExternalLink, Search, ShieldCheck } from "lucide-react";
import { useMemo, useState } from "react";
import { Link } from "wouter";

export default function Compare() {
  const [query, setQuery] = useState("");
  const [gameId, setGameId] = useState<number>();
  const gamesInput = useMemo(() => {
    const term = query.trim();
    return { page: 1, pageSize: 24, sort: "popular" as const, ...(term ? { q: term } : {}) };
  }, [query]);
  const games = trpc.games.list.useQuery(gamesInput);
  const evidence = trpc.benchmarks.compare.useQuery({ gameId: gameId ?? 1, limit: 120 }, { enabled: Boolean(gameId) });
  const groups = useMemo(() => groupBenchmarkEvidence(evidence.data ?? []), [evidence.data]);
  const maxFps = groups[0]?.averageFps ?? 0;

  return <div className="min-h-screen bg-background"><SiteHeader /><main className="container technical-grid py-8 md:py-12"><header className="stray-compare-hero stray-product-section rounded-2xl p-6 md:p-9"><div className="grid gap-6 md:grid-cols-[1fr_auto] md:items-end"><div><Badge variant="outline" className="border-primary/30 bg-primary/5 text-primary">COMPARADOR / EVIDÊNCIA VERIFICADA</Badge><h1 className="mt-4 max-w-3xl text-4xl font-semibold tracking-tight md:text-5xl">Compare cenários. Preserve o contexto.</h1><p className="mt-4 max-w-3xl leading-7 text-muted-foreground">Escolha um jogo publicado. O comparador organiza apenas benchmarks verificados, preservando GPU, CPU, distribuição, resolução, preset, data e fonte de cada amostra.</p></div><div className="stray-compare-readout rounded-xl px-4 py-3"><p className="stray-kicker">ESTADO ATUAL</p><p className="mt-1 text-sm font-medium">{gameId ? evidence.isLoading ? "consultando amostras" : `${evidence.data?.length ?? 0} resultados verificados` : "aguardando jogo"}</p></div></div></header>
    <section className="mt-6 grid gap-5 lg:grid-cols-[minmax(0,1fr)_330px]"><article className="stray-compare-step rounded-2xl p-5"><div className="flex items-center gap-2"><span className="stray-compare-index">01</span><Search className="h-4 w-4 text-primary" /><h2 className="font-semibold">Escolha o jogo</h2></div><p className="mt-2 text-sm leading-6 text-muted-foreground">Pesquise por título no catálogo real. A seleção não cria nem estima benchmarks.</p><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Ex.: Elden Ring, Hades, Cyberpunk…" className="mt-4" /><select value={gameId ?? ""} onChange={(event) => setGameId(event.target.value ? Number(event.target.value) : undefined)} className="mt-3 h-10 w-full rounded-md border bg-background px-3 text-sm" aria-label="Selecionar jogo para comparação"><option value="">{games.isLoading ? "Carregando jogos…" : "Selecione um jogo publicado"}</option>{games.data?.data.map((game) => <option key={game.id} value={game.id}>{game.title}</option>)}</select>{query.trim() && !games.isLoading && games.data?.data.length === 0 ? <p className="mt-3 text-sm text-muted-foreground">Nenhum jogo publicado corresponde à pesquisa. Tente outro título.</p> : null}</article>
      <aside className="stray-compare-limit rounded-2xl p-5"><ShieldCheck className="h-6 w-6 text-primary" /><p className="stray-kicker mt-4">LEITURA RESPONSÁVEL</p><h2 className="mt-2 font-semibold">Um cenário não é uma sentença.</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Uma diferença de GPU não isola CPU, driver, distro ou preset. Use a fonte primária antes de concluir que um componente é melhor em qualquer cenário.</p></aside></section>
    {gameId ? <section className="mt-7"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="evidence-label text-primary">02. RESULTADOS COMPARÁVEIS</p><h2 className="mt-1 text-2xl font-semibold">Amostras verificadas por GPU</h2></div>{evidence.isLoading ? <span className="text-sm text-muted-foreground">Carregando evidências…</span> : <span className="text-sm text-muted-foreground">{evidence.data?.length ?? 0} resultados verificados</span>}</div>{!evidence.isLoading && groups.length === 0 ? <div className="stray-empty-state mt-5 rounded-2xl p-10 text-center"><DatabaseZap className="mx-auto h-7 w-7 text-primary" /><h3 className="mt-4 text-lg font-semibold">Nenhum benchmark verificado disponível.</h3><p className="mx-auto mt-2 max-w-xl text-sm leading-6 text-muted-foreground">Ainda não há dados verificados para este jogo. Uma submissão pode ser enviada pelo fluxo de benchmark, mas só a moderação pode marcar o resultado como verificado.</p><Link href="/benchmark" className="mt-5 inline-flex text-sm font-medium text-primary hover:underline">Abrir área de benchmark</Link></div> : null}{groups.length ? <div className="stray-compare-rack mt-5 grid gap-4 lg:grid-cols-2">{groups.map((group) => <article key={group.label} className="stray-compare-sample rounded-2xl p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-lg font-semibold">{group.label}</p><p className="mt-1 text-sm text-muted-foreground">Média simples de {group.sampleSize} amostra{group.sampleSize === 1 ? "" : "s"} verificada{group.sampleSize === 1 ? "" : "s"}</p></div><Badge variant="outline" className="border-emerald-500/30 bg-emerald-500/10 text-emerald-300">Verified</Badge></div><div className="mt-5"><div className="flex items-end justify-between gap-3"><span className="text-3xl font-semibold">{group.averageFps.toFixed(1)} <span className="text-base text-muted-foreground">FPS</span></span><BarChart3 className="h-5 w-5 text-primary" /></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary transition-[width] duration-200" style={{ width: `${Math.max(6, (group.averageFps / maxFps) * 100)}%` }} /></div></div><p className="mt-4 text-xs leading-5 text-muted-foreground">CPUs: {group.cpuLabels.join(" · ")}<br />Distros: {group.distributions.join(" · ")}</p></article>)}</div> : null}</section> : null}
    {evidence.data?.length ? <section className="stray-product-section mt-7 rounded-2xl p-5"><p className="evidence-label text-primary">03. EVIDÊNCIA PRIMÁRIA</p><h2 className="mt-2 text-xl font-semibold">Todas as amostras usadas na visualização</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[980px] text-left text-sm"><thead className="border-b text-muted-foreground"><tr><th className="p-3">GPU / CPU</th><th className="p-3">Distro</th><th className="p-3">Ambiente</th><th className="p-3">FPS</th><th className="p-3">1% low</th><th className="p-3">Fonte</th></tr></thead><tbody>{evidence.data.map((row) => <tr key={row.id} className="border-b border-border/70"><td className="p-3"><p className="font-medium">{row.gpu}</p><p className="text-xs text-muted-foreground">{row.cpu}</p></td><td className="p-3">{row.distribution}</td><td className="p-3"><p>{row.resolutionWidth}×{row.resolutionHeight} · {row.preset}</p><p className="text-xs text-muted-foreground">{row.protonVersion} · {row.driverVersion}</p></td><td className="p-3 font-medium">{row.averageFps ?? "Não declarado"}</td><td className="p-3">{row.onePercentLowFps ?? "Não declarado"}</td><td className="p-3">{row.sourceUrl ? <a href={row.sourceUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-primary hover:underline">{row.sourceLabel}<ExternalLink className="h-3.5 w-3.5" /></a> : <span className="text-muted-foreground">{row.sourceLabel}</span>}</td></tr>)}</tbody></table></div></section> : null}</main></div>;
}
