import { SiteHeader } from "@/components/platform/SiteHeader";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Gamepad2, RefreshCw, ShieldCheck } from "lucide-react";
import { useState } from "react";

export default function Controllers() {
  const [scan, setScan] = useState<any>(); const [loading, setLoading] = useState(false); const [error, setError] = useState<string>();
  const run = async () => { if (!window.strayDesktop?.scanner) return; setLoading(true); setError(undefined); try { setScan(await window.strayDesktop.scanner.run()); } catch { setError("Não foi possível ler os controles neste dispositivo. Nenhuma alteração foi feita."); } finally { setLoading(false); } };
  const controllers = scan?.system?.controllers;
  return <div className="min-h-screen bg-background"><SiteHeader /><main className="container max-w-[1440px] technical-grid py-6"><header className="flex flex-wrap items-end justify-between gap-4 border-b border-white/8 pb-5"><div><p className="font-tech text-[10px] uppercase tracking-[.14em] text-cyan-200">CONTROLLER CENTER / LEITURA LOCAL</p><h1 className="mt-2 text-3xl font-semibold">Controles conectados</h1><p className="mt-2 max-w-2xl text-sm text-muted-foreground">Inventário local de controles detectados. O Stray Linux não altera drivers, mapeamentos nem configurações do Steam.</p></div>{window.strayDesktop?.scanner ? <Button onClick={run} disabled={loading}><RefreshCw className={`mr-2 h-4 w-4 ${loading ? "animate-spin" : ""}`} />{loading ? "Lendo dispositivos…" : "Detectar controles"}</Button> : null}</header><section className="mt-5 grid gap-5 lg:grid-cols-[1fr_.8fr]"><Card><CardHeader><CardTitle className="flex items-center gap-2"><Gamepad2 className="h-5 w-5 text-primary" />Inventário</CardTitle><CardDescription>Fonte: `/proc/bus/input/devices` e `/dev/input`. Somente leitura durante uma varredura solicitada.</CardDescription></CardHeader><CardContent>{scan ? controllers?.devices?.length ? <div className="space-y-3">{controllers.devices.map((device: any) => <div key={device.path} className="rounded-xl border p-4"><p className="font-medium">{device.name || "Controle sem nome informado"}</p><p className="mt-1 font-tech text-[10px] text-muted-foreground">{device.path} · {device.id}</p></div>)}</div> : <p className="rounded-xl border border-dashed p-5 text-sm text-muted-foreground">Nenhum controle foi detectado no relatório atual.</p> : <p className="rounded-xl border border-dashed p-5 text-sm text-muted-foreground">Execute a detecção no aplicativo desktop para ver dispositivos locais.</p>}{error ? <p className="mt-3 text-sm text-destructive">{error}</p> : null}</CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-primary" />Ações seguras</CardTitle></CardHeader><CardContent className="space-y-3 text-sm leading-6 text-muted-foreground"><p>Este centro ainda não grava perfis de mapeamento. A configuração do controle continua sendo feita no Steam, na distribuição ou no jogo.</p><p>Nenhum dado de entrada, identificador de conta, serial ou evento de controle é enviado ao servidor.</p><p>Futuras ações de configuração só serão exibidas com o comando, o impacto e a confirmação explícita antes de qualquer execução.</p></CardContent></Card></section></main></div>;
}
