import { GameCard } from "@/components/platform/GameCard";
import { SiteHeader } from "@/components/platform/SiteHeader";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Skeleton } from "@/components/ui/skeleton";
import { trpc } from "@/lib/trpc";
import { ChevronDown, Filter, Search, SlidersHorizontal, X } from "lucide-react";
import { useDeferredValue, useMemo, useState } from "react";

const platforms = ["steam", "steam_deck", "proton", "wine", "native_linux"] as const;

export default function Games() {
  const [search, setSearch] = useState(""); const [platform, setPlatform] = useState<(typeof platforms)[number]>(); const [genre, setGenre] = useState<string>(); const [multiplayer, setMultiplayer] = useState(false); const [antiCheat, setAntiCheat] = useState<"has" | "none">(); const [sort, setSort] = useState<"popular" | "title" | "recent" | "featured">("popular"); const [page, setPage] = useState(1); const deferredSearch = useDeferredValue(search);
  const input = useMemo(() => ({ page, pageSize: 30, q: deferredSearch.trim() || undefined, platform, genre, multiplayer: multiplayer || undefined, antiCheat, sort }), [antiCheat, deferredSearch, genre, multiplayer, page, platform, sort]);
  const games = trpc.games.list.useQuery(input); const options = trpc.games.filterOptions.useQuery();
  const active = [platform?.replace("_", " "), genre ? options.data?.genres.find((item) => item.slug === genre)?.name || genre : null, multiplayer ? "multiplayer" : null, antiCheat === "has" ? "com anti-cheat" : antiCheat === "none" ? "sem anti-cheat declarado" : null].filter(Boolean) as string[];
  const reset = () => { setSearch(""); setPlatform(undefined); setGenre(undefined); setMultiplayer(false); setAntiCheat(undefined); setSort("popular"); setPage(1); };

  return <div className="min-h-screen bg-background"><SiteHeader /><main className="container max-w-[1440px] technical-grid py-5 md:py-7"><header className="flex flex-wrap items-end justify-between gap-4 border-b border-white/8 pb-5"><div><p className="font-tech text-[10px] uppercase tracking-[0.15em] text-cyan-200">GAMEHUB / CATALOG INTELLIGENCE</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Catálogo de jogos</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">Pesquisa server-side em registros publicados. Compatibilidade e FPS aparecem somente quando houver evidência revisada.</p></div><span className="flex items-center gap-2 font-tech text-[10px] uppercase tracking-[0.12em] text-white/45"><Filter className="h-3.5 w-3.5 text-cyan-200" />filtros no servidor</span></header><FilterPanel /><section className="mt-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="font-tech text-[10px] uppercase tracking-[0.14em] text-cyan-200">RESULTADOS INDEXADOS</p><p className="mt-1 text-sm text-muted-foreground">{games.data ? `${games.data.meta.total.toLocaleString("pt-BR")} jogos encontrados` : "Carregando catálogo…"}</p></div>{active.length ? <div className="flex flex-wrap items-center gap-1.5">{active.map((filter) => <Badge key={filter} variant="secondary" className="capitalize">{filter}</Badge>)}<Button variant="ghost" size="sm" className="h-7 text-xs" onClick={reset}><X className="mr-1 h-3.5 w-3.5" />Limpar</Button></div> : null}</div>{games.isError ? <Empty text="Não foi possível carregar o catálogo agora. Tente novamente em instantes." /> : games.isLoading ? <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-5">{Array.from({ length: 10 }).map((_, index) => <Skeleton key={index} className="h-64 rounded-2xl" />)}</div> : <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-5">{games.data?.data.map((game) => <GameCard key={game.id} game={game} />)}</div>}{games.data && games.data.data.length === 0 ? <Empty text="Nenhum jogo corresponde aos filtros atuais. Remova alguns critérios ou tente outro termo." action={reset} /> : null}</section><div className="mt-8 flex items-center justify-center gap-3 border-t border-white/8 pt-6"><Button variant="outline" disabled={page === 1} onClick={() => setPage(Math.max(1, page - 1))}>Anterior</Button><span className="font-tech text-xs text-muted-foreground">PÁGINA {page}</span><Button variant="outline" disabled={!games.data || page * games.data.meta.pageSize >= games.data.meta.total} onClick={() => setPage(page + 1)}>Próxima</Button></div></main></div>;

  function FilterPanel() { return <section className="mt-5 rounded-2xl border border-white/8 bg-card/80 p-4"><div className="grid gap-3 lg:grid-cols-[minmax(0,1fr)_13rem_13rem]"><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" /><Input value={search} onChange={(event) => { setSearch(event.target.value); setPage(1); }} placeholder="Pesquisar título no catálogo" className="h-10 border-white/10 bg-black/15 pl-9" /></div><TextSelect label="Ordenar por" value={sort} onChange={(value) => { setSort((value || "popular") as typeof sort); setPage(1); }} options={["popular", "title", "recent", "featured"]} labels={{ popular: "Popularidade da fonte", title: "Título (A–Z)", recent: "Registro mais recente", featured: "Destaques" }} /><TextSelect label="Qualquer gênero" value={genre} onChange={(value) => { setGenre(value); setPage(1); }} options={(options.data?.genres ?? []).map((item) => item.slug)} labels={Object.fromEntries((options.data?.genres ?? []).map((item) => [item.slug, item.name]))} /></div><details className="group mt-3 border-t border-white/8 pt-3"><summary className="flex cursor-pointer list-none items-center justify-between text-xs font-medium text-muted-foreground"><span className="flex items-center gap-2"><SlidersHorizontal className="h-3.5 w-3.5 text-cyan-200" />Filtros de catálogo</span><ChevronDown className="h-3.5 w-3.5 transition-transform group-open:rotate-180" /></summary><div className="mt-3 grid gap-3 sm:grid-cols-3"><TextSelect label="Runtime/plataforma" value={platform} onChange={(value) => { setPlatform(value as typeof platform); setPage(1); }} options={platforms} /><TextSelect label="Anti-cheat" value={antiCheat} onChange={(value) => { setAntiCheat(value as typeof antiCheat); setPage(1); }} options={["has", "none"]} labels={{ has: "Com anti-cheat declarado", none: "Sem anti-cheat declarado" }} /><label className="flex h-10 items-center gap-2 rounded-md border border-white/10 bg-black/15 px-3 text-sm"><input type="checkbox" checked={multiplayer} onChange={(event) => { setMultiplayer(event.target.checked); setPage(1); }} />Multiplayer</label></div><p className="mt-3 text-xs leading-5 text-muted-foreground">Filtros por distro, GPU, CPU e Proton serão habilitados quando existirem registros de compatibilidade publicados. A ausência atual não indica incompatibilidade.</p></details></section>; }
}

function TextSelect({ label, value, onChange, options, labels = {} }: { label: string; value: string | undefined; onChange: (value: string | undefined) => void; options: readonly string[]; labels?: Record<string, string> }) { return <select aria-label={label} className="h-10 rounded-md border border-white/10 bg-black/15 px-3 text-sm" value={value ?? ""} onChange={(event) => onChange(event.target.value || undefined)}><option value="">{label}</option>{options.map((item) => <option key={item} value={item}>{labels[item] || item.replace("_", " ")}</option>)}</select>; }
function Empty({ text, action }: { text: string; action?: () => void }) { return <div className="mt-8 rounded-2xl border border-dashed p-12 text-center"><h2 className="font-semibold">Nenhum resultado disponível</h2><p className="mt-2 text-sm text-muted-foreground">{text}</p>{action ? <Button className="mt-4" variant="outline" onClick={action}>Limpar filtros</Button> : null}</div>; }
