import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { ProvenanceBadge } from "@/components/platform/ProvenanceBadge";
import { SiteHeader } from "@/components/platform/SiteHeader";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Skeleton } from "@/components/ui/skeleton";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, BookOpen, Cpu, Gauge, Heart, Info, MonitorCog, Wrench } from "lucide-react";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { useMemo, useState } from "react";
import { Link, useRoute } from "wouter";

const levelClass: Record<string, string> = { excellent: "text-emerald-500", good: "text-lime-500", playable: "text-amber-500", limited: "text-orange-500", broken: "text-red-500", unknown: "text-muted-foreground" };

export default function GameDetail() {
  const [, params] = useRoute("/games/:slug"); const { isAuthenticated } = useAuth(); const utils = trpc.useUtils(); const [gameVersion, setGameVersion] = useState("");
  const gameQuery = trpc.games.bySlug.useQuery({ slug: params?.slug ?? "" }, { enabled: Boolean(params?.slug) });
  const favorites = trpc.user.favorites.list.useQuery(undefined, { enabled: isAuthenticated }); const toggleFavorite = trpc.user.favorites.toggle.useMutation({ onSuccess: () => { utils.user.favorites.list.invalidate(); utils.user.dashboard.invalidate(); } });
  const benchmarkQuery = trpc.benchmarks.listForGame.useQuery({ gameId: gameQuery.data?.id ?? 1, page: 1, pageSize: 20 }, { enabled: Boolean(gameQuery.data?.id) });
  const activeProfile = trpc.user.compatibilityForActiveProfile.useQuery({ gameId: gameQuery.data?.id ?? 1 }, { enabled: isAuthenticated && Boolean(gameQuery.data?.id) });
  const environmentInput = useMemo(() => ({ gameId: gameQuery.data?.id ?? 1, gameVersion: gameVersion || null, distributionId: activeProfile.data?.profile?.distributionId ?? null, distributionVersionId: activeProfile.data?.profile?.distributionVersionId ?? null, cpuId: activeProfile.data?.profile?.cpuId ?? null, gpuId: activeProfile.data?.profile?.gpuId ?? null, kernelVersion: activeProfile.data?.profile?.kernelVersion ?? null, driverVersion: activeProfile.data?.profile?.driverVersion ?? null, protonVersion: activeProfile.data?.profile?.protonVersion ?? null, wineVersion: activeProfile.data?.profile?.wineVersion ?? null, runtimeVersion: activeProfile.data?.profile?.runtimeVersion ?? null }), [activeProfile.data?.profile, gameQuery.data?.id, gameVersion]);
  const environment = trpc.compatibility.forEnvironment.useQuery(environmentInput, { enabled: isAuthenticated && Boolean(activeProfile.data?.profile) && Boolean(gameQuery.data?.id) });
  const chartData = useMemo(() => (benchmarkQuery.data ?? []).flatMap((benchmark) => benchmark.results.map((result) => ({ id: `${benchmark.id}-${result.id}`, label: `${result.resolutionWidth}×${result.resolutionHeight} · ${result.preset}`, fps: Number(result.averageFps), sourceLabel: benchmark.sourceLabel || "Fonte registrada", sourceUrl: benchmark.sourceUrl })).filter((item) => Number.isFinite(item.fps))), [benchmarkQuery.data]);
  const game = gameQuery.data;
  if (gameQuery.isLoading) return <Loading />;
  if (!game) return <NotFound />;
  const imageUrl = game.steamAppId ? `https://cdn.cloudflare.steamstatic.com/steam/apps/${game.steamAppId}/header.jpg` : null;
  const isFavorite = favorites.data?.some((entry) => entry.game.id === game.id) ?? false;
  const handleFavorite = () => isAuthenticated ? toggleFavorite.mutate({ gameId: game.id }) : startLogin();
  return <div className="min-h-screen bg-background"><SiteHeader /><main className="container py-6 md:py-10"><Link href="/games"><Button variant="ghost" size="sm"><ArrowLeft className="mr-2 h-4 w-4" />Voltar ao catálogo</Button></Link>
    <Hero game={game} imageUrl={imageUrl} isFavorite={isFavorite} onFavorite={handleFavorite} pending={toggleFavorite.isPending} />
    <section className="mt-6 grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><div className="space-y-5"><RegisteredCompatibility items={game.compatibility} />{isAuthenticated ? <ProfileCompatibility profileQuery={activeProfile} environment={environment} gameVersion={gameVersion} onVersionChange={setGameVersion} /> : null}<Guides items={game.guides} /></div><aside className="space-y-5"><PerformanceChart loading={benchmarkQuery.isLoading} data={chartData} /><FixCard /><Card><CardContent className="p-5"><div className="flex gap-3"><Cpu className="mt-0.5 h-5 w-5 text-primary" /><div><p className="font-medium">Personalize com Meu PC</p><p className="mt-1 text-sm leading-6 text-muted-foreground">Crie um perfil ativo para comparar registros publicados com seu ambiente.</p></div></div></CardContent></Card></aside></section>
  </main></div>;
}

function Hero({ game, imageUrl, isFavorite, onFavorite, pending }: { game: any; imageUrl: string | null; isFavorite: boolean; onFavorite: () => void; pending: boolean }) { return <section className="mt-4 overflow-hidden rounded-3xl border bg-card"><div className="relative min-h-72 overflow-hidden bg-gradient-to-br from-primary/25 via-slate-900 to-cyan-600/20 p-7 md:p-10">{imageUrl ? <img src={imageUrl} alt="" className="absolute inset-0 h-full w-full object-cover opacity-35" onError={(event) => { event.currentTarget.style.display = "none"; }} /> : null}<div className="absolute inset-0 bg-gradient-to-r from-background via-background/70 to-transparent" /><div className="relative max-w-2xl"><div className="flex flex-wrap gap-2">{game.platforms.map((platform: any) => <Badge key={platform.id} className="border-0 bg-background/80 text-foreground backdrop-blur">{platform.platform.replace("_", " ")}</Badge>)}</div><h1 className="mt-6 text-4xl font-semibold tracking-tight md:text-5xl">{game.title}</h1><p className="mt-4 max-w-xl leading-7 text-muted-foreground">{game.shortDescription || "Este título possui registro de catálogo, mas ainda não tem resumo editorial disponível."}</p><div className="mt-6 flex flex-wrap gap-2">{game.tags.map((tag: any) => <Badge key={tag.slug} variant="secondary">{tag.name}</Badge>)}</div>{game.sourceUrl ? <a href={game.sourceUrl} target="_blank" rel="noreferrer" className="mt-4 inline-block text-xs text-primary hover:underline">Ver fonte do catálogo</a> : null}<div className="mt-6 flex flex-wrap gap-3"><Button disabled={pending} onClick={onFavorite}><Heart className={`mr-2 h-4 w-4 ${isFavorite ? "fill-current" : ""}`} />{isFavorite ? "Remover dos favoritos" : "Salvar jogo"}</Button><Link href="/benchmark"><Button variant="outline"><Gauge className="mr-2 h-4 w-4" />Consultar benchmark</Button></Link></div></div></div></section>; }
function RegisteredCompatibility({ items }: { items: any[] }) { return <Card><CardHeader><CardTitle className="flex items-center gap-2"><MonitorCog className="h-5 w-5 text-primary" />Compatibilidade registrada</CardTitle></CardHeader><CardContent>{items.length ? <div className="divide-y">{items.map((item) => <div key={item.id} className="flex flex-wrap items-center justify-between gap-3 py-4 first:pt-0"><div><p className={`font-semibold capitalize ${levelClass[item.level]}`}>{item.level}</p><p className="mt-1 text-sm text-muted-foreground">Kernel: {item.kernelConstraint || "não especificado"} · Driver: {item.driverConstraint || "não especificado"}</p></div><div className="text-right"><ProvenanceBadge provenance={item.provenance} /><p className="mt-1 text-xs text-muted-foreground">Confiança: {item.confidence}</p></div></div>)}</div> : <EmptyData title="Sem dado de compatibilidade" text="A ausência de dados não indica que o jogo funcione ou falhe." icon={Info} />}</CardContent></Card>; }
function ProfileCompatibility({ profileQuery, environment, gameVersion, onVersionChange }: { profileQuery: any; environment: any; gameVersion: string; onVersionChange: (value: string) => void }) { const result = environment.data; return <Card className="border-primary/25 bg-primary/[0.03]"><CardHeader><CardTitle className="flex items-center gap-2"><Cpu className="h-5 w-5 text-primary" />Compatibilidade para o seu perfil</CardTitle></CardHeader><CardContent><Input className="mb-4" value={gameVersion} onChange={(event) => onVersionChange(event.target.value)} placeholder="Versão do jogo testada (opcional)" />{profileQuery.isLoading || environment.isLoading ? <Skeleton className="h-32 w-full" /> : !profileQuery.data?.profile ? <EmptyData title="Perfil ativo não configurado" text="Crie e ative um perfil em Meu PC para comparar registros publicados." icon={Cpu} /> : result?.available ? <div className="rounded-xl border bg-background/70 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className={`font-semibold capitalize ${levelClass[result.record.level]}`}>{result.record.level}</p><p className="mt-1 text-sm text-muted-foreground">Perfil: {profileQuery.data.profile.name} · correspondência {labelForMatch(result.match.classification)}</p></div><ProvenanceBadge provenance={result.record.provenance} /></div><CompatibilityCoverage coverage={result.match.coverage} conflicts={result.match.conflictingFactors.length} /><p className="mt-3 text-xs leading-5 text-muted-foreground">A barra descreve a cobertura dos critérios declarados no registro e no perfil; ela não representa FPS ou probabilidade de funcionamento.</p>{result.record.summary ? <p className="mt-3 text-sm leading-6 text-muted-foreground">{result.record.summary}</p> : null}{result.match.missingFactors.length ? <p className="mt-3 text-xs text-muted-foreground">Ainda não informado no perfil: {result.match.missingFactors.join(", ")}.</p> : null}{result.match.conflictingFactors.length ? <p className="mt-3 text-xs text-amber-700 dark:text-amber-300">Critérios divergentes: {result.match.conflictingFactors.join(", ")}. Não trate este registro como previsão para o seu ambiente.</p> : null}</div> : <EmptyData title="Evidência não disponível" text={result?.reason || "Não foi possível localizar um registro aplicável ao perfil ativo."} icon={Info} />}</CardContent></Card>; }
function CompatibilityCoverage({ coverage, conflicts }: { coverage: number; conflicts: number }) { const safeCoverage = Math.max(0, Math.min(100, coverage)); return <div className="mt-4 rounded-lg border bg-muted/30 p-3"><div className="flex justify-between text-xs"><span className="font-medium">Cobertura de critérios</span><span>{safeCoverage}%{conflicts ? ` · ${conflicts} conflito(s)` : ""}</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-muted"><div className={conflicts ? "h-full bg-amber-500 transition-[width] duration-300" : "h-full bg-primary transition-[width] duration-300"} style={{ width: `${safeCoverage}%` }} /></div></div>; }
function PerformanceChart({ loading, data }: { loading: boolean; data: { id: string; label: string; fps: number; sourceLabel: string; sourceUrl: string | null }[] }) { return <Card><CardHeader><CardTitle className="flex items-center gap-2"><Gauge className="h-5 w-5 text-primary" />Performance verificada</CardTitle></CardHeader><CardContent>{loading ? <Skeleton className="h-48 w-full" /> : data.length ? <><div className="h-52"><ResponsiveContainer width="100%" height="100%"><BarChart data={data} margin={{ top: 8, right: 8, left: -20, bottom: 10 }}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="label" tick={{ fontSize: 10 }} interval={0} angle={-24} textAnchor="end" height={56} /><YAxis tick={{ fontSize: 11 }} /><Tooltip formatter={(value) => [`${Number(value).toFixed(1)} FPS`, "FPS médio"]} /><Bar dataKey="fps" fill="hsl(var(--primary))" radius={[5, 5, 0, 0]} /></BarChart></ResponsiveContainer></div><p className="mt-3 text-xs leading-5 text-muted-foreground">A visualização usa exclusivamente registros retornados pela consulta de benchmarks verificados. Consulte a fonte de cada barra.</p><div className="mt-3 space-y-1">{data.map((item) => item.sourceUrl ? <a key={item.id} href={item.sourceUrl} target="_blank" rel="noreferrer" className="block truncate text-xs text-primary hover:underline">{item.sourceLabel} · {item.label}</a> : <p key={item.id} className="truncate text-xs text-muted-foreground">{item.sourceLabel} · {item.label}</p>)}</div></> : <EmptyData title="Sem benchmark verificado" text="Não exibimos FPS sem benchmark com origem declarada." icon={Gauge} />}<Link href="/benchmark"><Button variant="outline" className="mt-4 w-full">Abrir PC Benchmark</Button></Link></CardContent></Card>; }
function Guides({ items }: { items: any[] }) { return <Card><CardHeader><CardTitle className="flex items-center gap-2"><BookOpen className="h-5 w-5 text-primary" />Linux Setup</CardTitle></CardHeader><CardContent>{items.length ? <div className="space-y-3">{items.map((guide) => <Link key={guide.id} href={`/setup/${guide.slug}`} className="block rounded-xl border p-4 transition-colors hover:bg-accent"><p className="font-medium">{guide.title}</p><p className="mt-1 text-sm text-muted-foreground">{guide.description}</p></Link>)}</div> : <EmptyData title="Sem guia específico" text="Não há guia publicado especificamente para este jogo." icon={BookOpen} />}</CardContent></Card>; }
function FixCard() { return <Card><CardHeader><CardTitle className="flex items-center gap-2"><Wrench className="h-5 w-5 text-primary" />LinuxFix</CardTitle></CardHeader><CardContent><EmptyData title="Sem correção conhecida" text="Nenhuma correção específica foi publicada para este jogo até o momento." icon={Wrench} /><Link href="/linuxfix"><Button variant="outline" className="mt-4 w-full">Abrir LinuxFix</Button></Link></CardContent></Card>; }
function Loading() { return <div className="min-h-screen"><SiteHeader /><main className="container py-10"><Skeleton className="h-9 w-40" /><Skeleton className="mt-6 h-80 rounded-2xl" /></main></div>; }
function NotFound() { return <div className="min-h-screen"><SiteHeader /><main className="container py-20 text-center"><h1 className="text-2xl font-semibold">Jogo não encontrado</h1><p className="mt-2 text-muted-foreground">O título pode não estar publicado ou não existir no catálogo.</p><Link href="/games"><Button className="mt-6">Voltar ao GameHub</Button></Link></main></div>; }
function EmptyData({ title, text, icon: Icon }: { title: string; text: string; icon: typeof Info }) { return <div className="rounded-xl border border-dashed bg-muted/30 p-5"><Icon className="h-5 w-5 text-muted-foreground" /><p className="mt-3 font-medium">{title}</p><p className="mt-1 text-sm leading-6 text-muted-foreground">{text}</p></div>; }
function labelForMatch(value: string) { return value === "exact" ? "exata" : value === "partial" ? "parcial" : value === "general" ? "geral" : "com conflito"; }
