import { GameCard } from "@/components/platform/GameCard";
import { SiteHeader } from "@/components/platform/SiteHeader";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { useLanguage } from "@/contexts/LanguageContext";
import { atlasNavigationCopy } from "@/i18n/atlasNavigationCopy";
import { homeDiagnosticsCopy } from "@/i18n/homeDiagnosticsCopy";
import { trpc } from "@/lib/trpc";
import { Activity, ArrowRight, BookOpenCheck, Database, Gamepad2, Map, Search, ShieldCheck, Terminal, Wrench } from "lucide-react";
import { useMemo } from "react";
import { useLocation } from "wouter";

export default function Home() {
  const [, setLocation] = useLocation();
  const { locale, t } = useLanguage();
  const navigationCopy = atlasNavigationCopy[locale];
  const diagnosticsCopy = homeDiagnosticsCopy[locale];
  const featuredInput = useMemo(() => ({ page: 1, pageSize: 8, sort: "featured" as const }), []);
  const gamesQuery = trpc.games.list.useQuery(featuredInput);
  const distributionsQuery = trpc.distributions.list.useQuery();
  const stats = [
    { value: gamesQuery.data?.meta.total ? `${gamesQuery.data.meta.total.toLocaleString(locale)}+` : "—", label: "jogos indexados", icon: Database },
    { value: distributionsQuery.data?.length ? String(distributionsQuery.data.length) : "—", label: "distribuições na wiki", icon: BookOpenCheck },
    { value: "0", label: "FPS sem fonte", icon: ShieldCheck },
  ];

  return <div className="min-h-screen bg-background text-foreground"><SiteHeader /><main className="technical-grid">
    <section className="relative overflow-hidden border-b"><div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_16%_18%,hsl(var(--primary)/0.22),transparent_30%),radial-gradient(circle_at_84%_26%,rgba(34,211,238,0.18),transparent_26%),radial-gradient(circle_at_62%_85%,rgba(167,139,250,0.13),transparent_30%),linear-gradient(180deg,hsl(var(--muted)/0.55),transparent)]" /><div className="container grid gap-10 py-16 md:grid-cols-[1.08fr_.92fr] md:py-24"><div className="max-w-3xl"><Badge variant="outline" className="mb-5 border-cyan-300/35 bg-cyan-300/5 font-tech text-cyan-300">STRAY LINUX / CENTRAL DE GAMING</Badge><h1 className="max-w-3xl text-4xl font-semibold tracking-[-0.04em] md:text-6xl">Seu sistema, seus jogos, <span className="text-primary">seu caminho no Linux.</span></h1><p className="mt-6 max-w-2xl text-base leading-7 text-muted-foreground md:text-lg">Explore jogos, compare compatibilidade por ambiente, siga guias separados por distribuição e investigue problemas com comandos e fontes explícitas.</p><div className="mt-9 flex flex-wrap gap-3"><Button size="lg" className="h-12 px-6 shadow-lg shadow-primary/20" onClick={() => setLocation("/games")}>Explorar jogos <ArrowRight className="ml-2 h-4 w-4" /></Button><Button size="lg" variant="outline" className="h-12 border-violet-300/45 bg-violet-300/10 px-6 text-violet-200 shadow-lg shadow-violet-500/10 hover:bg-violet-300/15 hover:text-violet-100" onClick={() => setLocation("/distros")}><Map className="mr-2 h-4 w-4" />Abrir Atlas Linux</Button></div></div><LinuxFixPreview copy={diagnosticsCopy} onOpen={() => setLocation("/linuxfix")} /></div></section>
    <section className="container grid gap-3 py-8 sm:grid-cols-3">{stats.map((stat) => <div key={stat.label} className="flex items-center gap-4 rounded-xl border bg-card p-4"><span className="grid h-10 w-10 place-items-center rounded-lg bg-primary/10 text-primary"><stat.icon className="h-5 w-5" /></span><div><p className="text-xl font-semibold">{stat.value}</p><p className="text-xs text-muted-foreground">{stat.label}</p></div></div>)}</section>
    <section className="container pb-8 md:pb-12"><div className="grid gap-3 md:grid-cols-3"><HomePath icon={Gamepad2} label={t("gameHub")} action={navigationCopy.openPath} onClick={() => setLocation("/games")} /><HomePath icon={Map} label={navigationCopy.start} description={navigationCopy.startDescription} action={navigationCopy.openPath} onClick={() => setLocation("/distros")} /><HomePath icon={Wrench} label={t("linuxFix")} action={navigationCopy.openPath} onClick={() => setLocation("/linuxfix")} /></div></section>
    <section className="container py-10 md:py-16"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-medium text-primary">CATÁLOGO EM DESTAQUE</p><h2 className="mt-1 text-3xl font-semibold tracking-tight">Comece por um jogo real.</h2></div><Button variant="ghost" onClick={() => setLocation("/games")}>Ver todo o catálogo <ArrowRight className="ml-2 h-4 w-4" /></Button></div><div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{gamesQuery.isLoading ? Array.from({ length: 8 }).map((_, index) => <Skeleton key={index} className="h-72 rounded-2xl" />) : gamesQuery.data?.data.map((game) => <GameCard key={game.id} game={game} />)}</div></section>
    <section className="border-y bg-muted/35"><div className="container grid gap-4 py-12 md:grid-cols-3"><Card className="border-0 bg-transparent shadow-none"><CardContent className="p-0"><Search className="h-6 w-6 text-primary" /><h3 className="mt-4 font-semibold">Pesquisa que respeita filtros</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Filtre por plataforma, gênero, distribuição, hardware e nível de compatibilidade quando houver dados.</p></CardContent></Card><Card className="border-0 bg-transparent shadow-none"><CardContent className="p-0"><Wrench className="h-6 w-6 text-primary" /><h3 className="mt-4 font-semibold">LinuxFix orientado a evidência</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Soluções indicam confiança, origem e limitações antes de sugerir qualquer comando.</p></CardContent></Card><Card className="border-0 bg-transparent shadow-none"><CardContent className="p-0"><BookOpenCheck className="h-6 w-6 text-primary" /><h3 className="mt-4 font-semibold">Wiki versionada</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Guias distinguem instruções gerais de conteúdo específico por distribuição e versão.</p></CardContent></Card></div></section>
  </main></div>;
}

function LinuxFixPreview({ copy, onOpen }: { copy: typeof homeDiagnosticsCopy["pt-BR"]; onOpen: () => void }) {
  const rows = [{ label: copy.gpu, command: "stray-scan --graphics" }, { label: copy.driver, command: "stray-scan --driver" }, { label: copy.kernel, command: "uname -r" }];
  return <section aria-label={copy.title} className="relative overflow-hidden rounded-3xl border border-cyan-300/20 bg-[#0a0d12]/88 shadow-2xl shadow-cyan-950/25 backdrop-blur"><div className="absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-cyan-200/80 to-transparent" /><div className="flex items-start justify-between gap-4 border-b border-white/10 p-5"><div><p className="font-tech text-[10px] font-semibold tracking-[0.18em] text-cyan-300">{copy.eyebrow}</p><h2 className="mt-2 text-xl font-semibold text-white">{copy.title}</h2></div><span className="inline-flex items-center gap-2 rounded-full border border-emerald-300/20 bg-emerald-300/10 px-3 py-1 font-tech text-[10px] text-emerald-200"><span className="system-status-pulse h-1.5 w-1.5 rounded-full bg-emerald-300" />{copy.status}</span></div><div className="p-5"><div className="rounded-2xl border border-white/10 bg-black/30 p-4 font-tech text-xs"><div className="flex items-center gap-2 text-cyan-200"><Terminal className="h-4 w-4" /><span>$ stray-scan --health</span><span className="ml-auto text-white/35">v1.1</span></div><p className="mt-3 flex items-center gap-2 text-white/55"><Activity className="h-3.5 w-3.5 animate-pulse text-cyan-300 motion-reduce:animate-none" />{copy.scanning}</p><div className="mt-4 space-y-3">{rows.map((row) => <div key={row.command} className="flex items-center justify-between gap-3 border-t border-white/5 pt-3"><div><p className="text-white/85">{row.label}</p><p className="mt-1 text-[10px] text-white/35">$ {row.command}</p></div><span className="rounded border border-cyan-300/20 bg-cyan-300/5 px-2 py-1 text-[10px] text-cyan-200">WAIT</span></div>)}</div><div className="mt-4 flex items-center gap-2 border-t border-white/10 pt-4 text-emerald-200"><span className="text-base">✓</span><span>{copy.ready}</span></div></div><p className="mt-4 text-xs leading-5 text-white/45">{copy.previewNote}</p><Button variant="outline" className="mt-5 w-full border-cyan-300/30 bg-cyan-300/5 text-cyan-100 hover:bg-cyan-300/10 hover:text-cyan-50" onClick={onOpen}>{copy.openFix}<ArrowRight className="ml-2 h-4 w-4" /></Button><p className="mt-5 border-t border-white/10 pt-4 font-tech text-[10px] tracking-[0.08em] text-white/40">{copy.credit}</p></div></section>;
}

function HomePath({ icon: Icon, label, description, action, onClick }: { icon: typeof Gamepad2; label: string; description?: string; action: string; onClick: () => void }) {
  return <button type="button" onClick={onClick} className="group rounded-2xl border bg-card/75 p-5 text-left transition-all duration-200 hover:-translate-y-0.5 hover:border-primary/35 hover:bg-primary/5 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><span className="grid h-10 w-10 place-items-center rounded-xl bg-primary/10 text-primary"><Icon className="h-5 w-5" /></span><p className="mt-5 font-semibold">{label}</p>{description ? <p className="mt-2 min-h-12 text-sm leading-6 text-muted-foreground">{description}</p> : null}<span className={`${description ? "mt-5" : "mt-4"} inline-flex items-center gap-1 text-sm font-medium text-primary`}>{action}<ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-0.5" /></span></button>;
}
