import { useAuth } from "@/_core/hooks/useAuth";
import { GameCard } from "@/components/platform/GameCard";
import { SiteHeader } from "@/components/platform/SiteHeader";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { useLanguage } from "@/contexts/LanguageContext";
import { trpc } from "@/lib/trpc";
import { Activity, ArrowRight, BookOpenCheck, CheckCircle2, CircleDotDashed, Database, Gamepad2, Gauge, MonitorCog, ScanLine, ShieldAlert, Sparkles, Wrench, XCircle } from "lucide-react";
import { useMemo } from "react";
import { Link, useLocation } from "wouter";

type ScanDetails = {
  cpu?: { model?: string | null; physicalCores?: number | null; logicalCores?: number | null };
  gpu?: { model?: string | null; vendor?: string | null; vramMb?: number | null };
  memoryGb?: number | null;
  graphics?: { driverVersion?: string | null; mesaVersion?: string | null; vulkanVersion?: string | null };
  runtime?: { steamDetected?: boolean; protonTools?: string[]; gaming?: { gameModeDetected?: boolean; mangoHudDetected?: boolean; gamescopeDetected?: boolean } };
  desktopEnvironment?: string | null;
};

function detailValue(value: string | number | null | undefined, fallback = "Não informado") { return value === null || value === undefined || value === "" ? fallback : String(value); }

export default function Home() {
  const [, setLocation] = useLocation();
  const { locale, t } = useLanguage();
  const { isAuthenticated, user } = useAuth();
  const featuredInput = useMemo(() => ({ page: 1, pageSize: 6, sort: "featured" as const }), []);
  const gamesQuery = trpc.games.list.useQuery(featuredInput);
  const distributionsQuery = trpc.distributions.list.useQuery();
  const contextQuery = trpc.user.recommendations.useQuery(undefined, { enabled: isAuthenticated });
  const dashboardQuery = trpc.user.dashboard.useQuery(undefined, { enabled: isAuthenticated });
  const historyQuery = trpc.user.linuxFixHistory.list.useQuery(undefined, { enabled: isAuthenticated });
  const benchmarksQuery = trpc.benchmarks.mine.useQuery(undefined, { enabled: isAuthenticated });
  const activeProfile = contextQuery.data?.profile ?? dashboardQuery.data?.profiles?.find((profile) => profile.isActive) ?? dashboardQuery.data?.profiles?.[0] ?? null;
  const details = activeProfile?.scanDetails as ScanDetails | null | undefined;
  const gameCount = gamesQuery.data?.meta.total;
  const distroCount = distributionsQuery.data?.length;
  const firstName = user?.name?.split(" ")[0];

  return <div className="min-h-screen bg-background text-foreground"><SiteHeader /><main className="technical-grid min-h-[calc(100vh-3.5rem)]"><div className="container max-w-[1500px] py-5 md:py-6">
    <header className="flex flex-wrap items-end justify-between gap-4 border-b border-white/8 pb-5"><div><p className="font-tech text-[10px] uppercase tracking-[0.16em] text-cyan-200">STRAY LINUX / CENTRAL OPERACIONAL</p><h1 className="mt-2 text-3xl font-semibold tracking-tight md:text-[2.1rem]">{firstName ? `Olá, ${firstName}.` : "Central de gaming Linux"}</h1><p className="mt-1 text-sm text-muted-foreground">Seu sistema, diagnósticos e catálogo em um espaço de trabalho. Ausência de dados permanece visível.</p></div><div className="flex flex-wrap gap-2"><Button size="sm" onClick={() => setLocation("/scanner")}><ScanLine className="mr-2 h-4 w-4" />Executar Scanner</Button><Button size="sm" variant="outline" onClick={() => setLocation("/games")}><Gamepad2 className="mr-2 h-4 w-4" />Abrir GameHub</Button></div></header>

    <section className="mt-5 grid gap-4 xl:grid-cols-4"><EnvironmentPanel details={details} activeProfile={activeProfile} onDiagnose={() => setLocation("/scanner")} /><SystemPanel details={details} activeProfile={activeProfile} onProfile={() => setLocation("/dashboard/pc/scan")} /><QuickStatus details={details} onScanner={() => setLocation("/scanner")} /><ActivityPanel history={historyQuery.data} benchmarks={benchmarksQuery.data} loading={historyQuery.isLoading || benchmarksQuery.isLoading} /></section>

    <section className="mt-5 grid gap-5 xl:grid-cols-[minmax(0,1.65fr)_minmax(20rem,.85fr)]"><div className="space-y-5"><Card className="overflow-hidden border-white/8 bg-card/80 shadow-none"><CardHeader className="flex-row items-start justify-between gap-3 border-b border-white/8 pb-4"><div><p className="font-tech text-[10px] uppercase tracking-[0.14em] text-cyan-200">CATÁLOGO / REGISTROS INDEXADOS</p><CardTitle className="mt-1 text-xl">GameHub</CardTitle><CardDescription className="mt-1">Jogos de catálogo com origem registrada; nenhum selo de desempenho é exibido sem evidência.</CardDescription></div><Link href="/games"><Button size="sm" variant="ghost">Ver catálogo<ArrowRight className="ml-2 h-4 w-4" /></Button></Link></CardHeader><CardContent className="p-4">{gamesQuery.isLoading ? <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{Array.from({ length: 6 }).map((_, index) => <Skeleton key={index} className="h-64 rounded-xl" />)}</div> : gamesQuery.data?.data.length ? <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{gamesQuery.data.data.map((game) => <GameCard key={game.id} game={game} />)}</div> : <EmptyState text="O catálogo não retornou itens nesta consulta." />}</CardContent></Card>
      <section className="grid gap-4 md:grid-cols-3"><OperationalMetric icon={Database} label="Jogos indexados" value={gameCount ? gameCount.toLocaleString(locale) : "—"} note="Metadados de catálogo disponíveis" /><OperationalMetric icon={BookOpenCheck} label={t("distros")} value={distroCount ? String(distroCount) : "—"} note="Atlas e métodos por família" /><OperationalMetric icon={Gauge} label="Benchmarks" value={benchmarksQuery.data?.length ? String(benchmarksQuery.data.length) : "—"} note={benchmarksQuery.data?.length ? "Submissões pessoais" : "Sem amostra pessoal"} /></section>
    </div>
    <aside className="space-y-5"><Card className="border-white/8 bg-card/80 shadow-none"><CardHeader className="pb-3"><p className="font-tech text-[10px] uppercase tracking-[0.14em] text-cyan-200">ATENDIMENTO TÉCNICO</p><CardTitle className="mt-1 text-lg">LinuxFix</CardTitle><CardDescription>Runbooks com fonte, risco, verificação e reversão quando aplicável.</CardDescription></CardHeader><CardContent className="space-y-3"><MiniAction icon={Wrench} title="Abrir diagnóstico" detail="Investigue sintomas por evidência" href="/linuxfix" /><MiniAction icon={Sparkles} title="Perguntar ao Stray AI" detail="Usa apenas contexto publicado e perfil ativo" href="/assistant" /><MiniAction icon={Activity} title="Comparar cenários" detail="Dados ausentes não são estimados" href="/compare" /></CardContent></Card><Card className="border-white/8 bg-card/80 shadow-none"><CardHeader className="pb-3"><p className="font-tech text-[10px] uppercase tracking-[0.14em] text-cyan-200">BIBLIOTECA LOCAL</p><CardTitle className="mt-1 text-lg">Steam no desktop</CardTitle><CardDescription>Leitura local de manifestos e lançamento explícito por URI validada, disponíveis no aplicativo Electron.</CardDescription></CardHeader><CardContent><Button className="w-full" variant="outline" onClick={() => setLocation("/library")}>Abrir jogos instalados<ArrowRight className="ml-2 h-4 w-4" /></Button></CardContent></Card></aside></section>
  </div></main></div>;
}

function EnvironmentPanel({ details, activeProfile, onDiagnose }: { details: ScanDetails | null | undefined; activeProfile: any; onDiagnose: () => void }) { const signals = [Boolean(details?.graphics?.vulkanVersion), Boolean(details?.runtime?.steamDetected), Boolean(details?.graphics?.driverVersion), Boolean(details?.runtime?.protonTools?.length)]; const detected = signals.filter(Boolean).length; return <Card className="border-emerald-400/20 bg-emerald-400/[0.035] shadow-none"><CardHeader className="pb-3"><p className="font-tech text-[10px] uppercase tracking-[0.14em] text-emerald-300">AMBIENTE DE JOGO</p><CardTitle className="mt-1 text-lg">{activeProfile ? "Sinais do sistema" : "Perfil não configurado"}</CardTitle></CardHeader><CardContent><div className="flex items-center gap-4"><div className="grid h-20 w-20 shrink-0 place-items-center rounded-full border-4 border-emerald-400/70 bg-emerald-400/10"><span className="text-xl font-semibold tabular-nums">{activeProfile ? detected : "—"}</span></div><div><p className="font-medium">{activeProfile ? `${detected} de 4 sinais disponíveis` : "Sem leitura local"}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Não é uma nota de saúde ou compatibilidade. Só resume leituras presentes no perfil.</p></div></div><Button className="mt-4 w-full" size="sm" variant="outline" onClick={onDiagnose}><ScanLine className="mr-2 h-4 w-4" />{activeProfile ? "Verificar novamente" : "Configurar sistema"}</Button></CardContent></Card>; }

function SystemPanel({ details, activeProfile, onProfile }: { details: ScanDetails | null | undefined; activeProfile: any; onProfile: () => void }) { return <Card className="border-white/8 bg-card/80 shadow-none"><CardHeader className="pb-3"><p className="font-tech text-[10px] uppercase tracking-[0.14em] text-cyan-200">SEU SISTEMA</p><CardTitle className="mt-1 text-lg">{activeProfile?.name || "Nenhum perfil ativo"}</CardTitle></CardHeader><CardContent className="space-y-2">{activeProfile ? <><SystemLine label="GPU" value={[details?.gpu?.vendor, details?.gpu?.model || activeProfile.detectedGpu].filter(Boolean).join(" ") || "Não informada"} /><SystemLine label="CPU" value={details?.cpu?.model || activeProfile.detectedCpu || "Não informada"} /><SystemLine label="RAM" value={details?.memoryGb ? `${details.memoryGb} GB` : activeProfile.detectedRamGb ? `${activeProfile.detectedRamGb} GB` : "Não informada"} /><SystemLine label="Distro" value={activeProfile.detectedDistribution || activeProfile.distributionName || "Não informada"} /></> : <p className="rounded-xl border border-dashed p-4 text-xs leading-5 text-muted-foreground">Importe uma leitura do Scanner ou configure seu perfil manualmente.</p>}<Button className="mt-2 w-full" size="sm" variant="outline" onClick={onProfile}><MonitorCog className="mr-2 h-4 w-4" />Detalhes do sistema</Button></CardContent></Card>; }

function QuickStatus({ details, onScanner }: { details: ScanDetails | null | undefined; onScanner: () => void }) { const statuses = [{ label: "Vulkan", available: Boolean(details?.graphics?.vulkanVersion), detail: details?.graphics?.vulkanVersion || "Não verificado" }, { label: "Driver", available: Boolean(details?.graphics?.driverVersion), detail: details?.graphics?.driverVersion || "Não verificado" }, { label: "Steam", available: Boolean(details?.runtime?.steamDetected), detail: details?.runtime?.steamDetected ? "Detectada localmente" : "Não detectada" }, { label: "Proton", available: Boolean(details?.runtime?.protonTools?.length), detail: details?.runtime?.protonTools?.[0] || "Não informado" }]; return <Card className="border-white/8 bg-card/80 shadow-none"><CardHeader className="pb-3"><p className="font-tech text-[10px] uppercase tracking-[0.14em] text-cyan-200">STATUS RÁPIDO</p><CardTitle className="mt-1 text-lg">Ambiente técnico</CardTitle></CardHeader><CardContent className="space-y-2">{statuses.map((status) => <div key={status.label} className="flex items-center gap-2 text-xs"><span className={status.available ? "text-emerald-300" : "text-amber-300"}>{status.available ? <CheckCircle2 className="h-4 w-4" /> : <CircleDotDashed className="h-4 w-4" />}</span><span className="w-14 font-medium">{status.label}</span><span className="min-w-0 truncate text-muted-foreground" title={status.detail}>{status.detail}</span></div>)}<Button className="mt-2 w-full" size="sm" variant="outline" onClick={onScanner}>Executar diagnóstico</Button></CardContent></Card>; }

function ActivityPanel({ history, benchmarks, loading }: { history: any[] | undefined; benchmarks: any[] | undefined; loading: boolean }) { const items = [...(history ?? []).slice(0, 2).map((item) => ({ icon: Wrench, title: item.fix?.title || "LinuxFix consultado", detail: item.viewedAt ? new Date(item.viewedAt).toLocaleDateString("pt-BR") : "Registrado" })), ...(benchmarks ?? []).slice(0, 2).map((item) => ({ icon: Gauge, title: item.gameTitle || "Benchmark", detail: item.benchmark?.verificationStatus || "Registrado" }))]; return <Card className="border-white/8 bg-card/80 shadow-none"><CardHeader className="pb-3"><p className="font-tech text-[10px] uppercase tracking-[0.14em] text-cyan-200">ATIVIDADE RECENTE</p><CardTitle className="mt-1 text-lg">Conta e diagnósticos</CardTitle></CardHeader><CardContent>{loading ? <div className="space-y-3"><Skeleton className="h-9" /><Skeleton className="h-9" /></div> : items.length ? <div className="space-y-3">{items.map((item, index) => <div key={`${item.title}-${index}`} className="flex gap-3"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-white/5"><item.icon className="h-4 w-4 text-cyan-200" /></span><div className="min-w-0"><p className="truncate text-sm font-medium">{item.title}</p><p className="mt-0.5 text-xs text-muted-foreground">{item.detail}</p></div></div>)}</div> : <div className="rounded-xl border border-dashed p-4 text-xs leading-5 text-muted-foreground">Nenhuma atividade pessoal registrada. Esse painel mostra somente histórico e benchmarks da sua conta.</div>}</CardContent></Card>; }

function OperationalMetric({ icon: Icon, label, value, note }: { icon: typeof Database; label: string; value: string; note: string }) { return <Card className="border-white/8 bg-card/75 shadow-none"><CardContent className="p-4"><div className="flex items-center justify-between"><span className="font-tech text-[10px] uppercase tracking-[0.12em] text-muted-foreground">{label}</span><Icon className="h-4 w-4 text-cyan-300" /></div><p className="mt-3 text-2xl font-semibold tabular-nums">{value}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{note}</p></CardContent></Card>; }

function SystemLine({ label, value }: { label: string; value: string }) { return <div className="flex items-center gap-2 rounded-lg border border-white/8 bg-black/15 px-3 py-2"><span className="w-11 font-tech text-[10px] text-cyan-200">{label}</span><span className="min-w-0 truncate text-xs text-white/80" title={value}>{value}</span></div>; }
function MiniAction({ icon: Icon, title, detail, href }: { icon: typeof Wrench; title: string; detail: string; href: string }) { return <Link href={href} className="flex items-center gap-3 rounded-xl border border-white/8 bg-black/15 p-3 transition-colors hover:bg-white/5"><span className="grid h-8 w-8 place-items-center rounded-lg bg-cyan-300/10"><Icon className="h-4 w-4 text-cyan-200" /></span><span className="min-w-0 flex-1"><span className="block text-sm font-medium">{title}</span><span className="mt-0.5 block truncate text-xs text-muted-foreground">{detail}</span></span><ArrowRight className="h-4 w-4 text-muted-foreground" /></Link>; }
function EmptyState({ text }: { text: string }) { return <div className="rounded-xl border border-dashed p-5 text-sm text-muted-foreground">{text}</div>; }
