import { ProvenanceBadge } from "@/components/platform/ProvenanceBadge";
import { SiteHeader } from "@/components/platform/SiteHeader";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Skeleton } from "@/components/ui/skeleton";
import { trpc } from "@/lib/trpc";
import { BookOpenCheck, ChevronRight, CircleAlert, Clipboard, Copy, ExternalLink, FileWarning, Search, Terminal, Wrench } from "lucide-react";
import { useMemo, useState } from "react";
import { Link, useRoute } from "wouter";

export function WikiPage() {
  const [query, setQuery] = useState("");
  const input = useMemo(() => ({ page: 1, pageSize: 40, q: query.trim() || undefined }), [query]);
  const articles = trpc.knowledge.wiki.list.useQuery(input);
  return <PublicFrame eyebrow="LINUX WIKI" title="A referência que começa pela sua distribuição." description="Artigos com fonte, versão e status de publicação. Scores de gaming não são exibidos sem metodologia documentada."><SearchField value={query} onChange={setQuery} placeholder="Pesquisar distros, drivers, Steam e Vulkan" /><div className="mt-7 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{articles.isLoading ? Array.from({ length: 12 }).map((_, i) => <Skeleton className="h-52 rounded-2xl" key={i} />) : articles.data?.map(({ article, distributionName }) => <Link key={article.id} href={`/wiki/${article.slug}`} className="group rounded-2xl border bg-card p-5 shadow-sm transition-all hover:-translate-y-0.5 hover:border-primary/40 hover:shadow-md"><div className="flex items-center justify-between gap-2"><Badge variant="secondary">{distributionName || article.category}</Badge><ProvenanceBadge provenance={article.provenance} /></div><h2 className="mt-5 text-lg font-semibold tracking-tight">{article.title}</h2><p className="mt-2 line-clamp-3 text-sm leading-6 text-muted-foreground">{article.excerpt}</p><p className="mt-5 flex items-center text-sm font-medium text-primary">Abrir referência <ChevronRight className="ml-1 h-4 w-4 transition-transform group-hover:translate-x-1" /></p></Link>)}</div>{articles.data?.length === 0 ? <EmptyKnowledge icon={BookOpenCheck} title="Nenhum artigo encontrado" text="Tente outro termo ou consulte a lista de distribuições disponíveis." /> : null}</PublicFrame>;
}

export function WikiDetailPage() {
  const [, params] = useRoute("/wiki/:slug");
  const query = trpc.knowledge.wiki.bySlug.useQuery({ slug: params?.slug ?? "" }, { enabled: Boolean(params?.slug) });
  const item = query.data;
  if (query.isLoading) return <PublicFrame eyebrow="LINUX WIKI" title="Carregando artigo" description=""><Skeleton className="mt-8 h-96 rounded-2xl" /></PublicFrame>;
  if (!item) return <PublicFrame eyebrow="LINUX WIKI" title="Artigo não encontrado" description="Este conteúdo pode não estar publicado."><Link href="/wiki"><Button className="mt-6">Voltar à wiki</Button></Link></PublicFrame>;
  return <PublicFrame eyebrow="LINUX WIKI" title={item.article.title} description={item.article.excerpt || "Referência técnica da plataforma."}><article className="mt-8 max-w-4xl rounded-2xl border bg-card p-6 md:p-8"><div className="flex flex-wrap items-center gap-2"><Badge variant="secondary">{item.distributionName || item.article.category}</Badge><ProvenanceBadge provenance={item.article.provenance} />{item.article.versionLabel ? <Badge variant="outline">Versão: {item.article.versionLabel}</Badge> : null}</div><div className="prose prose-sm mt-7 max-w-none whitespace-pre-wrap text-foreground dark:prose-invert">{item.article.body}</div>{item.article.sourceUrl ? <a className="mt-8 inline-flex items-center text-sm font-medium text-primary hover:underline" href={item.article.sourceUrl} target="_blank" rel="noreferrer">Abrir fonte registrada <ExternalLink className="ml-2 h-4 w-4" /></a> : null}</article></PublicFrame>;
}

export function SetupPage() {
  const [query, setQuery] = useState(""); const [difficulty, setDifficulty] = useState<"beginner" | "intermediate" | "advanced" | undefined>();
  const input = useMemo(() => ({ page: 1, pageSize: 40, q: query.trim() || undefined, difficulty }), [difficulty, query]);
  const guides = trpc.knowledge.guides.list.useQuery(input);
  return <PublicFrame eyebrow="LINUX SETUP" title="Guias que deixam claro o que fazem." description="Comandos copiáveis, nível de dificuldade, fonte e avisos antes de qualquer alteração no sistema."><div className="flex flex-col gap-3 sm:flex-row"><SearchField value={query} onChange={setQuery} placeholder="Pesquisar Steam, Proton, Vulkan, drivers…" /><select className="h-10 rounded-md border bg-background px-3 text-sm" value={difficulty ?? ""} onChange={(event) => setDifficulty((event.target.value || undefined) as typeof difficulty)}><option value="">Qualquer dificuldade</option><option value="beginner">Iniciante</option><option value="intermediate">Intermediário</option><option value="advanced">Avançado</option></select></div><div className="mt-7 grid gap-4 md:grid-cols-2">{guides.isLoading ? Array.from({ length: 4 }).map((_, i) => <Skeleton key={i} className="h-48 rounded-2xl" />) : guides.data?.map(({ guide, distributionName }) => <Link key={guide.id} href={`/setup/${guide.slug}`} className="group rounded-2xl border bg-card p-5 transition-all hover:border-primary/40 hover:shadow-md"><div className="flex flex-wrap items-center gap-2"><Badge variant="secondary" className="capitalize">{guide.difficulty}</Badge>{distributionName ? <Badge variant="outline">{distributionName}</Badge> : null}<ProvenanceBadge provenance={guide.provenance} /></div><h2 className="mt-5 font-semibold">{guide.title}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{guide.description}</p><p className="mt-5 flex items-center text-sm font-medium text-primary">Abrir guia <ChevronRight className="ml-1 h-4 w-4 transition-transform group-hover:translate-x-1" /></p></Link>)}</div>{guides.data?.length === 0 ? <EmptyKnowledge icon={Terminal} title="Nenhum guia encontrado" text="Ajuste o termo de busca ou verifique novamente mais tarde." /> : null}</PublicFrame>;
}

export function SetupDetailPage() {
  const [, params] = useRoute("/setup/:slug"); const guideQuery = trpc.knowledge.guides.bySlug.useQuery({ slug: params?.slug ?? "" }, { enabled: Boolean(params?.slug) }); const guide = guideQuery.data;
  const { isAuthenticated } = useAuth();
  const utils = trpc.useUtils();
  const savedGuides = trpc.user.savedGuides.list.useQuery(undefined, { enabled: isAuthenticated });
  const toggleSavedGuide = trpc.user.savedGuides.toggle.useMutation({ onSuccess: () => { utils.user.savedGuides.list.invalidate(); utils.user.dashboard.invalidate(); } });
  if (guideQuery.isLoading) return <PublicFrame eyebrow="LINUX SETUP" title="Carregando guia" description=""><Skeleton className="mt-8 h-96 rounded-2xl" /></PublicFrame>;
  if (!guide) return <PublicFrame eyebrow="LINUX SETUP" title="Guia não encontrado" description="Este guia pode não estar publicado."><Link href="/setup"><Button className="mt-6">Voltar aos guias</Button></Link></PublicFrame>;
  const isSaved = savedGuides.data?.some((item) => item.guide.id === guide.id) ?? false;
  const saveGuide = () => isAuthenticated ? toggleSavedGuide.mutate({ guideId: guide.id }) : startLogin();
  return <PublicFrame eyebrow="LINUX SETUP" title={guide.title} description={guide.description || "Guia técnico da plataforma."}><div className="mt-7 flex flex-wrap items-center gap-2"><Badge variant="secondary" className="capitalize">{guide.difficulty}</Badge><ProvenanceBadge provenance={guide.provenance} />{guide.guideVersion ? <Badge variant="outline">Versão: {guide.guideVersion}</Badge> : null}<Button variant={isSaved ? "secondary" : "outline"} size="sm" disabled={toggleSavedGuide.isPending} onClick={saveGuide}><BookOpenCheck className="mr-2 h-4 w-4" />{isSaved ? "Remover dos salvos" : "Salvar no painel"}</Button></div><div className="mt-6 space-y-4">{guide.steps.map((step) => <Card key={step.id}><CardContent className="p-5"><div className="flex gap-4"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-primary/10 text-sm font-semibold text-primary">{step.stepOrder}</span><div className="min-w-0 flex-1"><h2 className="font-semibold">{step.title}</h2>{step.explanation ? <p className="mt-2 text-sm leading-6 text-muted-foreground">{step.explanation}</p> : null}{step.command ? <CommandBlock command={step.command} /> : null}{step.warning ? <div className="mt-4 flex gap-2 rounded-lg border border-amber-500/25 bg-amber-500/5 p-3 text-sm text-amber-800 dark:text-amber-200"><CircleAlert className="mt-0.5 h-4 w-4 shrink-0" />{step.warning}</div> : null}</div></div></CardContent></Card>)}</div>{guide.sourceUrl ? <a className="mt-7 inline-flex items-center text-sm font-medium text-primary hover:underline" href={guide.sourceUrl} target="_blank" rel="noreferrer">Abrir fonte registrada <ExternalLink className="ml-2 h-4 w-4" /></a> : null}</PublicFrame>;
}

export function LinuxFixPage() {
  const [query, setQuery] = useState(""); const [category, setCategory] = useState<string | undefined>();
  const input = useMemo(() => ({ page: 1, pageSize: 40, q: query.trim() || undefined, category: category as never }), [category, query]); const fixes = trpc.knowledge.linuxFix.list.useQuery(input);
  return <PublicFrame eyebrow="LINUXFIX" title="Diagnóstico antes de tentativa e erro." description="Cada correção mostra sintomas, causa provável, confiança e origem. Use os comandos somente após ler o alerta."><div className="flex flex-col gap-3 sm:flex-row"><SearchField value={query} onChange={setQuery} placeholder="Pesquisar Steam, Proton, stuttering, tela preta…" /><select className="h-10 rounded-md border bg-background px-3 text-sm" value={category ?? ""} onChange={(event) => setCategory(event.target.value || undefined)}><option value="">Todas as categorias</option>{["steam", "proton", "wine", "vulkan", "amd", "nvidia", "anti_cheat", "audio", "stuttering", "crashes", "black_screen", "launch_errors"].map((item) => <option key={item} value={item}>{item.replace("_", " ")}</option>)}</select></div><div className="mt-7 grid gap-4 md:grid-cols-2">{fixes.isLoading ? Array.from({ length: 4 }).map((_, i) => <Skeleton className="h-52 rounded-2xl" key={i} />) : fixes.data?.map((fix) => <Link key={fix.id} href={`/linuxfix/${fix.slug}`} className="group rounded-2xl border bg-card p-5 transition-all hover:border-primary/40 hover:shadow-md"><div className="flex items-center justify-between gap-2"><Badge variant="secondary" className="capitalize">{fix.category.replace("_", " ")}</Badge><ProvenanceBadge provenance={fix.provenance} /></div><h2 className="mt-5 font-semibold">{fix.title}</h2><p className="mt-2 line-clamp-2 text-sm leading-6 text-muted-foreground">{fix.symptoms}</p><div className="mt-5 flex items-center justify-between"><span className="text-xs text-muted-foreground">Confiança: <strong className="capitalize text-foreground">{fix.confidence}</strong></span><ChevronRight className="h-4 w-4 text-primary transition-transform group-hover:translate-x-1" /></div></Link>)}</div>{fixes.data?.length === 0 ? <EmptyKnowledge icon={Wrench} title="Nenhuma solução encontrada" text="O problema pode ainda não ter uma solução publicada com fonte suficiente." /> : null}</PublicFrame>;
}

export function LinuxFixDetailPage() {
  const [, params] = useRoute("/linuxfix/:slug"); const fixQuery = trpc.knowledge.linuxFix.bySlug.useQuery({ slug: params?.slug ?? "" }, { enabled: Boolean(params?.slug) }); const fix = fixQuery.data;
  const { isAuthenticated } = useAuth();
  const utils = trpc.useUtils();
  const recordHistory = trpc.user.linuxFixHistory.record.useMutation({ onSuccess: () => { utils.user.linuxFixHistory.list.invalidate(); } });
  if (fixQuery.isLoading) return <PublicFrame eyebrow="LINUXFIX" title="Carregando solução" description=""><Skeleton className="mt-8 h-96 rounded-2xl" /></PublicFrame>;
  if (!fix) return <PublicFrame eyebrow="LINUXFIX" title="Solução não encontrada" description="Este conteúdo pode não estar publicado."><Link href="/linuxfix"><Button className="mt-6">Voltar ao LinuxFix</Button></Link></PublicFrame>;
  const addToHistory = () => isAuthenticated ? recordHistory.mutate({ fixId: fix.id }) : startLogin();
  return <PublicFrame eyebrow="LINUXFIX" title={fix.title} description="Solução técnica com origem e confiança indicadas."><div className="mt-7 flex flex-wrap items-center gap-2"><Badge variant="secondary" className="capitalize">{fix.category.replace("_", " ")}</Badge><ProvenanceBadge provenance={fix.provenance} /><Badge variant="outline" className="capitalize">Confiança: {fix.confidence}</Badge><Button variant="outline" size="sm" disabled={recordHistory.isPending} onClick={addToHistory}><Wrench className="mr-2 h-4 w-4" />{recordHistory.isSuccess ? "Adicionado ao histórico" : "Adicionar ao histórico"}</Button></div><div className="mt-6 grid gap-5 lg:grid-cols-2"><Card><CardHeader><CardTitle>Sintomas</CardTitle></CardHeader><CardContent className="text-sm leading-6 text-muted-foreground">{fix.symptoms}</CardContent></Card><Card><CardHeader><CardTitle>Possíveis causas</CardTitle></CardHeader><CardContent className="text-sm leading-6 text-muted-foreground">{fix.possibleCauses}</CardContent></Card></div><section className="mt-6 space-y-4">{fix.solutions.map((solution) => <Card key={solution.id}><CardContent className="p-5"><div className="flex gap-4"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-primary/10 text-sm font-semibold text-primary">{solution.stepOrder}</span><div className="min-w-0 flex-1"><h2 className="font-semibold">{solution.title}</h2>{solution.explanation ? <p className="mt-2 text-sm leading-6 text-muted-foreground">{solution.explanation}</p> : null}{solution.command ? <CommandBlock command={solution.command} /> : null}{solution.warning ? <div className="mt-4 flex gap-2 rounded-lg border border-amber-500/25 bg-amber-500/5 p-3 text-sm text-amber-800 dark:text-amber-200"><FileWarning className="mt-0.5 h-4 w-4 shrink-0" />{solution.warning}</div> : null}</div></div></CardContent></Card>)}</section>{fix.sourceUrl ? <a className="mt-7 inline-flex items-center text-sm font-medium text-primary hover:underline" href={fix.sourceUrl} target="_blank" rel="noreferrer">Abrir fonte registrada <ExternalLink className="ml-2 h-4 w-4" /></a> : null}</PublicFrame>;
}

function PublicFrame({ eyebrow, title, description, children }: { eyebrow: string; title: string; description: string; children: React.ReactNode }) { return <div className="min-h-screen bg-background"><SiteHeader /><main className="container py-8 md:py-12"><Badge variant="outline" className="border-primary/30 bg-primary/5 text-primary">{eyebrow}</Badge><h1 className="mt-3 max-w-4xl text-4xl font-semibold tracking-tight">{title}</h1>{description ? <p className="mt-3 max-w-3xl leading-7 text-muted-foreground">{description}</p> : null}{children}</main></div>; }
function SearchField({ value, onChange, placeholder }: { value: string; onChange: (value: string) => void; placeholder: string }) { return <div className="relative flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" /><Input value={value} onChange={(event) => onChange(event.target.value)} className="pl-9" placeholder={placeholder} /></div>; }
function EmptyKnowledge({ icon: Icon, title, text }: { icon: typeof Wrench; title: string; text: string }) { return <div className="mt-8 rounded-2xl border border-dashed p-10 text-center"><Icon className="mx-auto h-7 w-7 text-muted-foreground" /><h2 className="mt-4 font-semibold">{title}</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-muted-foreground">{text}</p></div>; }
function CommandBlock({ command }: { command: string }) { const [copied, setCopied] = useState(false); const copy = async () => { await navigator.clipboard.writeText(command); setCopied(true); window.setTimeout(() => setCopied(false), 1800); }; return <div className="mt-4 overflow-hidden rounded-lg border bg-muted/40"><div className="flex items-center justify-between gap-3 border-b bg-muted/50 px-3 py-2"><span className="flex items-center gap-2 text-xs font-medium text-muted-foreground"><Terminal className="h-3.5 w-3.5" />Comando</span><Button variant="ghost" size="sm" className="h-7 text-xs" onClick={copy}>{copied ? <Clipboard className="mr-1.5 h-3.5 w-3.5" /> : <Copy className="mr-1.5 h-3.5 w-3.5" />}{copied ? "Copiado" : "Copiar"}</Button></div><pre className="overflow-x-auto p-3 text-xs leading-6 text-foreground"><code>{command}</code></pre></div>; }
