import { PageBreadcrumbs } from "@/components/platform/PageBreadcrumbs";
import { SiteHeader } from "@/components/platform/SiteHeader";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { FileSearch, ShieldCheck } from "lucide-react";
import { useState } from "react";

type Level = "all" | "info" | "warning" | "error";

export default function LogsCenter() {
  const desktopAvailable = Boolean(window.strayDesktop?.scanner);
  const [level, setLevel] = useState<Level>("all");
  const logs = trpc.user.logs.list.useQuery({ level: level === "all" ? undefined : level }, { enabled: desktopAvailable });
  return <div className="min-h-screen bg-background"><SiteHeader /><main className="container max-w-[1180px] technical-grid py-5 md:py-7"><div className="space-y-5"><PageBreadcrumbs items={[{ label: "Sistema", href: "/dashboard/pc" }, { label: "Logs" }]} /><header className="stray-surface rounded-2xl p-5"><p className="stray-kicker">LOG CENTER / LOCAL ONLY</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Verifique o que o Stray registrou.</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground">Logs são mantidos no SQLite local para diagnóstico. Eles registram eventos do aplicativo e não coletam tokens, credenciais, caminhos de bibliotecas ou conteúdo de arquivos de jogos.</p></header>{!desktopAvailable ? <Card className="border-dashed"><CardContent className="p-6 text-center"><p className="font-medium">Logs técnicos disponíveis no aplicativo desktop.</p><p className="mt-2 text-sm text-muted-foreground">O site não recebe nem reproduz logs do dispositivo.</p></CardContent></Card> : <Card><CardHeader><div className="flex flex-wrap items-center justify-between gap-3"><div><CardTitle className="flex items-center gap-2"><FileSearch className="h-5 w-5 text-primary" />Registros locais</CardTitle><CardDescription>Filtre por severidade e revise o módulo que registrou o evento.</CardDescription></div><div className="flex gap-2">{(["all", "info", "warning", "error"] as const).map((item) => <Button key={item} size="sm" variant={level === item ? "default" : "outline"} onClick={() => setLevel(item)}>{item === "all" ? "Todos" : item}</Button>)}</div></div></CardHeader><CardContent>{logs.isLoading ? <p className="text-sm text-muted-foreground">Lendo registros locais…</p> : logs.data?.length ? <div className="space-y-3">{logs.data.map((log) => <div key={log.id} className="rounded-xl border bg-card/40 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div className="flex items-center gap-2"><Badge variant="outline" className={log.level === "error" ? "border-red-400/30 text-red-300" : log.level === "warning" ? "border-amber-400/30 text-amber-200" : "border-emerald-400/30 text-emerald-300"}>{log.level}</Badge><p className="font-medium">{log.message}</p></div><span className="font-tech text-[10px] uppercase tracking-wide text-muted-foreground">{log.module}</span></div><p className="mt-2 text-xs text-muted-foreground">{new Date(log.createdAt).toLocaleString("pt-BR")}</p><p className="mt-3 text-xs leading-5 text-muted-foreground">{log.detailsJson === "{}" ? "Sem detalhes adicionais." : "Detalhes minimizados disponíveis no registro local."}</p></div>)}</div> : <div className="rounded-xl border border-dashed p-8 text-center"><ShieldCheck className="mx-auto h-7 w-7 text-primary" /><p className="mt-3 font-medium">Nenhum registro para este filtro.</p><p className="mt-1 text-sm text-muted-foreground">Novos logs aparecem quando o aplicativo grava eventos técnicos locais.</p></div>}</CardContent></Card>}</div></main></div>;
}
