import { SiteHeader } from "@/components/platform/SiteHeader";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Boxes, RefreshCw, ShieldCheck } from "lucide-react";
import { useState } from "react";

export default function Mods() {
  const [data, setData] = useState<any>(); const [loading, setLoading] = useState(false); const [error, setError] = useState<string>();
  const scan = async () => { if (!window.strayDesktop?.library?.scanMods) return; setLoading(true); setError(undefined); try { setData(await window.strayDesktop.library.scanMods()); } catch { setError("Não foi possível ler as pastas locais de Workshop. Nenhum arquivo foi alterado."); } finally { setLoading(false); } };
  return <div className="min-h-screen bg-background"><SiteHeader /><main className="container max-w-[1440px] technical-grid py-6"><header className="flex flex-wrap items-end justify-between gap-4 border-b border-white/8 pb-5"><div><p className="font-tech text-[10px] uppercase tracking-[.14em] text-cyan-200">MOD MANAGER / DESCOBERTA LOCAL</p><h1 className="mt-2 text-3xl font-semibold">Mods instalados</h1><p className="mt-2 max-w-2xl text-sm text-muted-foreground">Leitura local das pastas Steam Workshop. O Stray Linux não baixa, ativa, remove nem reordena mods automaticamente.</p></div>{window.strayDesktop?.library?.scanMods ? <Button onClick={scan} disabled={loading}><RefreshCw className={`mr-2 h-4 w-4 ${loading ? "animate-spin" : ""}`} />{loading ? "Lendo Workshop…" : "Buscar mods locais"}</Button> : null}</header><section className="mt-5 grid gap-5 lg:grid-cols-[1fr_.8fr]"><Card><CardHeader><CardTitle className="flex items-center gap-2"><Boxes className="h-5 w-5 text-primary" />Workshop detectado</CardTitle><CardDescription>Fonte: caminhos Steam locais. Contagens representam diretórios locais encontrados, não compatibilidade ou qualidade de mods.</CardDescription></CardHeader><CardContent>{data ? data.entries?.length ? <div className="space-y-3">{data.entries.map((entry: any) => <div key={entry.path} className="rounded-xl border p-4"><p className="font-medium">Steam App ID {entry.appId}</p><p className="mt-1 text-sm text-muted-foreground">{entry.modCount} diretório(s) de mod · {entry.installationType}</p><p className="mt-1 font-tech text-[10px] text-muted-foreground">{entry.path}</p></div>)}</div> : <p className="rounded-xl border border-dashed p-5 text-sm text-muted-foreground">Nenhuma pasta Steam Workshop com mods foi detectada neste computador.</p> : <p className="rounded-xl border border-dashed p-5 text-sm text-muted-foreground">Execute a descoberta no aplicativo desktop para consultar somente suas bibliotecas locais.</p>}{error ? <p className="mt-3 text-sm text-destructive">{error}</p> : null}</CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-primary" />Limites seguros</CardTitle></CardHeader><CardContent className="space-y-3 text-sm leading-6 text-muted-foreground"><p>Este inventário não lê o conteúdo dos mods, credenciais, histórico de conta ou arquivos de jogo fora dos diretórios de Workshop.</p><p>Importar um item para o Stray Linux será opcional e manterá uma referência local; nenhuma alteração será aplicada sem confirmação específica.</p><p>Modificações, ordem de carregamento e instalação continuam sob controle do Steam, do gerenciador escolhido pelo usuário ou do próprio jogo.</p></CardContent></Card></section></main></div>;
}
