import { PageBreadcrumbs } from "@/components/platform/PageBreadcrumbs";
import { SiteHeader } from "@/components/platform/SiteHeader";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { BellRing, CircleDotDashed, ScanLine } from "lucide-react";
import { Link } from "wouter";

export default function NotificationsCenter() {
  const desktopAvailable = Boolean(window.strayDesktop?.scanner);
  const timeline = trpc.user.timeline.list.useQuery(undefined, { enabled: desktopAvailable });
  return <div className="min-h-screen bg-background"><SiteHeader /><main className="container max-w-[1080px] technical-grid py-5 md:py-7"><div className="space-y-5"><PageBreadcrumbs items={[{ label: "Sistema", href: "/dashboard/pc" }, { label: "Notificações" }]} /><header className="stray-surface rounded-2xl p-5"><p className="stray-kicker">NOTIFICATIONS / LOCAL EVENTS</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Alertas que partem de fatos locais.</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground">O Stray não envia push nem deduz atualizações de driver. Esta central transforma eventos já registrados pelo aplicativo em notificações locais revisáveis.</p></header>{!desktopAvailable ? <Card className="border-dashed"><CardContent className="p-6 text-center"><p className="font-medium">Notificações técnicas disponíveis no aplicativo desktop.</p><p className="mt-2 text-sm text-muted-foreground">O site não recebe eventos do dispositivo.</p></CardContent></Card> : <Card><CardHeader><CardTitle className="flex items-center gap-2"><BellRing className="h-5 w-5 text-primary" />Eventos relevantes</CardTitle><CardDescription>Uma notificação aparece apenas depois que o aplicativo gravar uma leitura, backup ou outra operação local.</CardDescription></CardHeader><CardContent>{timeline.data?.length ? <div className="space-y-3">{timeline.data.map((event) => <div key={event.id} className="flex gap-3 rounded-xl border bg-card/40 p-4"><span className="mt-1 grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-primary/10"><ScanLine className="h-4 w-4 text-primary" /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-medium">{event.label}</p><Badge variant="outline" className="font-tech text-[9px]">local</Badge></div><p className="mt-1 text-xs text-muted-foreground">{new Date(event.createdAt).toLocaleString("pt-BR")}</p><p className="mt-2 text-xs leading-5 text-muted-foreground">{event.detailsJson === "{}" ? "Evento registrado sem detalhes adicionais." : "Evento com detalhes técnicos minimizados disponíveis localmente."}</p></div></div>)}</div> : <div className="rounded-xl border border-dashed p-8 text-center"><CircleDotDashed className="mx-auto h-7 w-7 text-primary" /><p className="mt-3 font-medium">Nenhuma notificação local ainda.</p><p className="mt-1 text-sm text-muted-foreground">Capture um snapshot ou crie um backup para registrar um evento técnico local.</p><Link href="/snapshots" className="mt-4 inline-flex text-sm font-medium text-primary hover:underline">Abrir Snapshots</Link></div>}</CardContent></Card>}</div></main></div>;
}
