import { PageBreadcrumbs } from "@/components/platform/PageBreadcrumbs";
import { SiteHeader } from "@/components/platform/SiteHeader";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { detectPerformanceRegression } from "@/lib/performanceRegression";
import { Activity, AlertTriangle, ArrowLeftRight, CircleHelp } from "lucide-react";
import { Link } from "wouter";

export default function Regression() {
  const regression = detectPerformanceRegression(undefined, undefined);
  return <div className="min-h-screen bg-background"><SiteHeader /><main className="container max-w-[1120px] technical-grid py-5 md:py-7"><div className="space-y-5"><PageBreadcrumbs items={[{ label: "Sistema", href: "/dashboard/pc" }, { label: "Regressão" }]} /><header className="stray-surface rounded-2xl p-5"><p className="stray-kicker">PERFORMANCE REGRESSION / EVIDENCE REQUIRED</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Compare medições, não impressões.</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground">O detector exige duas medições do mesmo jogo, com FPS médio explícito e configurações comparáveis. Ele descreve uma diferença numérica, mas não declara a causa.</p></header><Card><CardHeader><CardTitle className="flex items-center gap-2"><Activity className="h-5 w-5 text-primary" />Estado atual</CardTitle><CardDescription>Este dispositivo ainda não possui duas medições de performance importadas de forma compatível.</CardDescription></CardHeader><CardContent><div className="rounded-xl border border-dashed bg-card/30 p-6 text-center"><AlertTriangle className="mx-auto h-8 w-8 text-amber-200" /><Badge variant="outline" className="mt-3 border-amber-400/30 text-amber-200">INDISPONÍVEL</Badge><p className="mt-3 font-medium">{regression.reason}</p><p className="mx-auto mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">Sessões locais registram duração, não FPS. Para habilitar uma comparação, conecte no futuro um coletor local autorizado ou importe uma medição com fonte, resolução, preset e FPS médio.</p></div></CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2"><ArrowLeftRight className="h-5 w-5 text-primary" />Como a comparação será validada</CardTitle></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2"><Rule label="Mesmo jogo" detail="Medições de títulos diferentes não são comparadas." /><Rule label="FPS explícito" detail="Duração, estimativas ou notas não viram FPS." /><Rule label="Configuração equivalente" detail="Mudança conhecida em resolução ou preset suspende a comparação." /><Rule label="Sem causalidade" detail="Snapshots podem mostrar fatores alterados, sem provar a causa." /></CardContent></Card><Card className="border-dashed"><CardContent className="flex flex-wrap items-center justify-between gap-4 p-5"><div className="flex gap-3"><CircleHelp className="mt-0.5 h-5 w-5 shrink-0 text-primary" /><p className="max-w-2xl text-sm leading-6 text-muted-foreground">Enquanto não houver medição comparável, use Snapshots para ver mudanças técnicas e Diagnóstico para investigar sinais observados.</p></div><div className="flex gap-2"><Link href="/snapshots"><Button variant="outline">Snapshots</Button></Link><Link href="/diagnostics"><Button variant="outline">Diagnóstico</Button></Link></div></CardContent></Card></div></main></div>;
}

function Rule({ label, detail }: { label: string; detail: string }) { return <div className="rounded-xl border bg-card/40 p-4"><p className="font-medium">{label}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{detail}</p></div>; }
