import { SiteFooter } from "@/components/site/SiteFooter";
import { SiteNav } from "@/components/site/SiteNav";
import { useLanguage } from "@/contexts/LanguageContext";
import { landingCopy } from "@/i18n/landingCopy";
import { roadmapCopy } from "@/i18n/roadmapCopy";

const phases = [
  { number: "01", title: "Centro de Operações", status: "Em desenvolvimento", tone: "border-sky-300/50 bg-sky-50 text-sky-900", detail: "Leitura recente, campos ausentes e recomendações seguras.", limit: "Não transforma ausência de leitura em erro ou diagnóstico." },
  { number: "02", title: "Biblioteca local", status: "Em planejamento", tone: "border-slate-300 bg-slate-50 text-slate-700", detail: "Origem clara, ações explícitas e arte somente quando autorizada ou local.", limit: "Não inicia jogos fora dos launchers e caminhos suportados." },
  { number: "03", title: "Diagnóstico e LinuxFix", status: "Em planejamento", tone: "border-slate-300 bg-slate-50 text-slate-700", detail: "Sintomas, evidência, pré-requisito, risco, verificação e reversão.", limit: "Não executa comandos destrutivos ou altera permissões automaticamente." },
  { number: "04", title: "Stray AI", status: "Validada", tone: "border-emerald-300/60 bg-emerald-50 text-emerald-900", detail: "Contexto consentido, fontes internas, limites e recusa fora do escopo.", limit: "Não promete benchmark, FPS ou compatibilidade que não tenham evidência." },
  { number: "05", title: "Qualidade", status: "Em desenvolvimento", tone: "border-sky-300/50 bg-sky-50 text-sky-900", detail: "Localização, acessibilidade, contratos IPC, segurança e distribuição.", limit: "Uma fase só é publicada após testes, build e validação apropriada." },
];

export default function Roadmap() {
  const { locale } = useLanguage(); const copy = landingCopy[locale]; const roadmap = roadmapCopy[locale];
  return <div className="min-h-screen bg-[#f0f0ec] text-[#0b0c10]"><SiteNav /><main className="px-4 py-10 sm:px-6 sm:py-16 lg:px-8"><div className="mx-auto max-w-[1180px]"><header className="rounded-[1.75rem] bg-[#0b0c10] p-7 text-[#f5f5f0] sm:p-10"><p className="font-tech text-[10px] font-bold tracking-[.2em] text-[#9fbaff]">{copy.station}</p><h1 className="mt-5 max-w-4xl font-serif text-5xl leading-[.88] tracking-[-.065em] sm:text-7xl">{roadmap.title}</h1><p className="mt-6 max-w-3xl text-base leading-7 text-white/65">{roadmap.disclaimer}</p></header><section className="mt-8"><div className="mb-5 flex flex-wrap items-end justify-between gap-3"><div><p className="font-tech text-[10px] font-bold tracking-[.2em] text-black/45">{roadmap.statusLabel}</p><h2 className="mt-2 font-serif text-4xl tracking-[-.05em]">{roadmap.summary}</h2></div><p className="max-w-sm text-sm leading-6 text-black/60">{roadmap.disclaimer}</p></div><div className="grid gap-3">{phases.map((phase) => <article key={phase.number} className="grid gap-4 rounded-2xl border border-black/12 bg-white/55 p-5 sm:grid-cols-[4rem_1fr_auto] sm:items-start"><p className="font-tech text-sm font-bold tracking-[.16em] text-black/38">{phase.number}</p><div><div className="flex flex-wrap items-center gap-3"><h3 className="text-xl font-semibold tracking-tight">{phase.title}</h3><span className={`rounded-full border px-2.5 py-1 text-[10px] font-semibold tracking-[.08em] ${phase.tone}`}>{phase.status}</span></div><p className="mt-3 text-sm leading-6 text-black/68">{phase.detail}</p><p className="mt-3 border-t border-black/10 pt-3 text-xs leading-5 text-black/50">Limite: {phase.limit}</p></div><span className="font-tech text-[10px] tracking-[.14em] text-black/42">EVIDÊNCIA + TESTES</span></article>)}</div></section><section className="mt-10 border-t border-black/12 pt-8"><p className="font-tech text-[10px] font-bold tracking-[.2em] text-black/45">PRINCÍPIOS DE DESENVOLVIMENTO</p><div className="mt-4 grid gap-4 md:grid-cols-3"><article className="rounded-2xl border border-black/12 bg-white/45 p-5"><h2 className="font-semibold">Ação explícita</h2><p className="mt-2 text-sm leading-6 text-black/62">Todo controle executa uma ação, abre uma rota ou explica claramente por que está indisponível.</p></article><article className="rounded-2xl border border-black/12 bg-white/45 p-5"><h2 className="font-semibold">Local-first</h2><p className="mt-2 text-sm leading-6 text-black/62">Recursos locais pertencem ao Electron; navegador e aplicativo não fingem ter as mesmas capacidades.</p></article><article className="rounded-2xl border border-black/12 bg-white/45 p-5"><h2 className="font-semibold">Privacidade e revisão</h2><p className="mt-2 text-sm leading-6 text-black/62">Credenciais e dados pessoais não entram no bundle; mudanças passam por testes, build e validação.</p></article></div></section></div></main><SiteFooter /></div>;
}
