import { PageBreadcrumbs } from "@/components/platform/PageBreadcrumbs";
import { SiteHeader } from "@/components/platform/SiteHeader";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { scannerReportInput, type ScannerReport } from "../../../server/lib/scannerReport";
import { compareConfigurations } from "@/lib/snapshotComparison";
import { trpc } from "@/lib/trpc";
import { ArrowLeftRight, Camera, RefreshCw, ScanLine, Trash2 } from "lucide-react";
import { useMemo, useState } from "react";

type Snapshot = { id: number; label: string; createdAt: string; scan: ScannerReport };

export default function Snapshots() {
  const utils = trpc.useUtils();
  const desktopAvailable = Boolean(window.strayDesktop?.scanner);
  const snapshots = trpc.user.snapshots.list.useQuery(undefined, { enabled: desktopAvailable });
  const create = trpc.user.snapshots.create.useMutation({ onSuccess: () => utils.user.snapshots.list.invalidate() });
  const remove = trpc.user.snapshots.remove.useMutation({ onSuccess: () => utils.user.snapshots.list.invalidate() });
  const [label, setLabel] = useState("Snapshot local"); const [running, setRunning] = useState(false); const [error, setError] = useState<string | null>(null); const [beforeId, setBeforeId] = useState<number>(); const [afterId, setAfterId] = useState<number>();
  const entries = (snapshots.data ?? []) as Snapshot[];
  const before = entries.find((item) => item.id === beforeId); const after = entries.find((item) => item.id === afterId);
  const capture = async () => { if (!window.strayDesktop?.scanner || !label.trim()) return; setRunning(true); setError(null); try { const scan = scannerReportInput.parse(await window.strayDesktop.scanner.run()); await create.mutateAsync({ label: label.trim(), scan }); setLabel("Snapshot local"); } catch { setError("Não foi possível registrar o snapshot local. Nenhum dado foi sincronizado ou enviado."); } finally { setRunning(false); } };
  return <div className="min-h-screen bg-background"><SiteHeader /><main className="container max-w-[1440px] technical-grid py-5 md:py-7"><div className="space-y-6"><PageBreadcrumbs items={[{ label: "Sistema", href: "/dashboard/pc" }, { label: "Snapshots" }]} /><header className="stray-surface rounded-2xl p-5"><p className="stray-kicker">SYSTEM SNAPSHOTS / LOCAL ONLY</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Compare leituras do seu sistema.</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground">Cada snapshot é criado somente após sua ação, salvo no SQLite local e compara campos técnicos sem inferir impacto em FPS, compatibilidade ou estabilidade.</p></header><section className="grid gap-5 xl:grid-cols-[.85fr_1.15fr]"><Card><CardHeader><CardTitle className="flex items-center gap-2"><Camera className="h-5 w-5 text-primary" />Capturar snapshot</CardTitle><CardDescription>CPU, GPU, driver, Mesa, kernel, Vulkan, distro, Proton, Wine e ambiente quando o Scanner conseguir detectar.</CardDescription></CardHeader><CardContent className="space-y-3"><Input value={label} onChange={(event) => setLabel(event.target.value)} aria-label="Nome do snapshot" /><Button className="w-full" onClick={capture} disabled={running || create.isPending || !window.strayDesktop?.scanner || !label.trim()}><ScanLine className="mr-2 h-4 w-4" />{running ? "Lendo sistema…" : "Salvar leitura local"}</Button>{!window.strayDesktop?.scanner ? <p className="text-xs leading-5 text-muted-foreground">Disponível no aplicativo desktop. No navegador, use o Scanner para revisar um JSON sem salvar um snapshot local.</p> : null}{error ? <p className="text-sm text-destructive">{error}</p> : null}</CardContent></Card><SnapshotList entries={entries} beforeId={beforeId} afterId={afterId} setBeforeId={setBeforeId} setAfterId={setAfterId} remove={(id) => remove.mutate({ id })} /></section>{before && after ? <SnapshotCompare before={before} after={after} /> : <Card className="border-dashed"><CardContent className="flex items-center gap-3 p-6 text-sm text-muted-foreground"><ArrowLeftRight className="h-5 w-5 text-primary" />Selecione dois snapshots locais para comparar campos conhecidos antes e depois.</CardContent></Card>}</div></main></div>;
}

function SnapshotList({ entries, beforeId, afterId, setBeforeId, setAfterId, remove }: { entries: Snapshot[]; beforeId?: number; afterId?: number; setBeforeId: (id: number | undefined) => void; setAfterId: (id: number | undefined) => void; remove: (id: number) => void }) { return <Card><CardHeader><CardTitle>Leituras salvas</CardTitle><CardDescription>{entries.length ? "Escolha uma leitura anterior e outra posterior." : "Nenhuma leitura foi salva neste dispositivo."}</CardDescription></CardHeader><CardContent className="space-y-3">{entries.map((item) => <div key={item.id} className="grid gap-3 rounded-xl border p-4 md:grid-cols-[1fr_auto_auto_auto]"><div><p className="font-medium">{item.label}</p><p className="mt-1 text-xs text-muted-foreground">{new Date(item.createdAt).toLocaleString("pt-BR")} · {item.scan.system.distribution.name || "Distro não informada"}</p></div><Button size="sm" variant={beforeId === item.id ? "default" : "outline"} onClick={() => setBeforeId(item.id)}>Antes</Button><Button size="sm" variant={afterId === item.id ? "default" : "outline"} onClick={() => setAfterId(item.id)}>Depois</Button><Button size="icon" variant="ghost" aria-label={`Excluir ${item.label}`} onClick={() => remove(item.id)}><Trash2 className="h-4 w-4" /></Button></div>)}</CardContent></Card>; }

function SnapshotCompare({ before, after }: { before: Snapshot; after: Snapshot }) { const rows = useMemo(() => compareConfigurations(before.scan, after.scan), [before, after]); return <Card><CardHeader><CardTitle className="flex items-center gap-2"><RefreshCw className="h-5 w-5 text-primary" />Configuração A vs. B</CardTitle><CardDescription>{before.label} → {after.label}. Alterado e sem mudança dependem de dois campos observados; qualquer lacuna fica como desconhecida.</CardDescription></CardHeader><CardContent className="divide-y rounded-xl border">{rows.map((row) => <div key={row.label} className="grid gap-2 p-4 md:grid-cols-[.7fr_1fr_1fr_auto]"><p className="font-tech text-[10px] tracking-[.12em] text-muted-foreground">{row.label}</p><p className="text-sm">{row.before}</p><p className="text-sm">{row.after}</p><span className={`font-tech text-[9px] uppercase tracking-[.12em] ${row.status === "changed" ? "text-amber-200" : row.status === "unchanged" ? "text-emerald-300" : "text-muted-foreground"}`}>{row.status === "changed" ? "Alterado" : row.status === "unchanged" ? "Sem mudança" : "Desconhecido"}</span></div>)}</CardContent></Card>; }
