import { SiteHeader } from "@/components/platform/SiteHeader";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { AlertTriangle, CheckCircle2, RefreshCw, ServerCog } from "lucide-react";
import { useEffect, useState } from "react";

type Status = { status: "operational" | "degraded"; checkedAt: string; checks: { api: "operational"; database: "operational" | "unavailable" | "desktop_local"; externalRefresh: "manual_only" } };

const labels = { api: "API", database: "Banco de dados", externalRefresh: "Atualização de fontes" } as const;
const values = { operational: "Operacional", unavailable: "Indisponível", desktop_local: "SQLite local", manual_only: "Manual, sem conta externa" } as const;

export default function StatusPage() {
  const [data, setData] = useState<Status>();
  const [error, setError] = useState(false);
  const [loading, setLoading] = useState(true);
  const load = async () => { setLoading(true); setError(false); try { const response = await fetch("/api/status", { headers: { accept: "application/json" } }); if (!response.ok) throw new Error("Status indisponível"); setData(await response.json() as Status); } catch { setError(true); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const degraded = data?.status === "degraded" || error;
  return <div className="min-h-screen bg-background"><SiteHeader /><main className="container py-8 md:py-12"><section className="diagnostic-panel rounded-2xl border border-primary/15 p-6 md:p-8"><p className="evidence-label text-primary">STATUS / OPERAÇÃO AUTÔNOMA</p><div className="mt-4 flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-4xl font-semibold tracking-tight">Status do Stray Linux</h1><p className="mt-3 max-w-2xl leading-7 text-muted-foreground">Verificação local do serviço e do banco. Esta página não usa serviço de monitoramento, CDN ou conta de terceiros.</p></div><Badge variant="outline" className={degraded ? "border-amber-500/40 bg-amber-500/10 text-amber-700 dark:text-amber-200" : "border-emerald-500/40 bg-emerald-500/10 text-emerald-700 dark:text-emerald-200"}>{degraded ? "DEGRADADO" : "OPERACIONAL"}</Badge></div></section><section className="mt-6 grid gap-4 md:grid-cols-3">{loading ? <Card className="md:col-span-3"><CardContent className="p-6 text-sm text-muted-foreground">Verificando estado operacional…</CardContent></Card> : error ? <Card className="border-amber-500/25 md:col-span-3"><CardContent className="flex gap-3 p-6 text-sm text-muted-foreground"><AlertTriangle className="h-5 w-5 shrink-0 text-amber-500" />Não foi possível consultar o endpoint interno de status. Isso não confirma indisponibilidade total; tente novamente.</CardContent></Card> : Object.entries(data!.checks).map(([key, value]) => <Card key={key} className="border-primary/15"><CardHeader className="pb-3"><CardTitle className="flex items-center gap-2 text-base"><ServerCog className="h-4 w-4 text-primary" />{labels[key as keyof typeof labels]}</CardTitle><CardDescription>{value === "manual_only" ? "Nenhuma sincronização ou conta externa está ativa." : "Estado reportado pelo servidor nesta consulta."}</CardDescription></CardHeader><CardContent><p className="flex items-center gap-2 font-medium"><CheckCircle2 className="h-4 w-4 text-primary" />{values[value as keyof typeof values]}</p></CardContent></Card>)}</section><Card className="mt-6"><CardHeader><CardTitle>Limites da operação sem conta externa</CardTitle><CardDescription>A aplicação mantém health check, headers de segurança, rate limiting local e histórico de fontes. Ela não oferece CDN global, alertas fora do servidor ou monitoramento independente de indisponibilidade.</CardDescription></CardHeader><CardContent className="flex flex-wrap items-center justify-between gap-3 gap-y-2 text-sm text-muted-foreground"><span>{data?.checkedAt ? `Última verificação: ${new Date(data.checkedAt).toLocaleString("pt-BR")}` : "Sem horário disponível"}</span><button className="inline-flex items-center gap-2 font-medium text-primary hover:underline" onClick={() => void load()}><RefreshCw className="h-4 w-4" />Verificar novamente</button></CardContent></Card></main></div>;
}
