import { PageBreadcrumbs } from "@/components/platform/PageBreadcrumbs";
import { SiteHeader } from "@/components/platform/SiteHeader";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { CalendarClock, CheckCircle2, CircleDotDashed, ScanLine } from "lucide-react";
import { Link } from "wouter";

export default function SystemTimeline() {
  const timeline = trpc.user.timeline.list.useQuery();
  return <div className="min-h-screen bg-background"><SiteHeader /><main className="container max-w-[1440px] technical-grid py-5 md:py-7"><div className="space-y-6"><PageBreadcrumbs items={[{ label: "Sistema", href: "/dashboard/pc" }, { label: "Timeline" }]} /><header className="stray-surface rounded-2xl p-5"><p className="stray-kicker">SYSTEM TIMELINE / LOCAL ONLY</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Acompanhe mudanças que foram realmente registradas.</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground">A timeline não adivinha atualizações, regressões ou causas. Ela lista eventos gravados pelo aplicativo, como snapshots locais, e permite revisar o contexto técnico associado.</p></header><Card><CardHeader><CardTitle className="flex items-center gap-2"><CalendarClock className="h-5 w-5 text-primary" />Eventos locais</CardTitle><CardDescription>Ordenados pelo horário de registro neste dispositivo.</CardDescription></CardHeader><CardContent>{timeline.isLoading ? <p className="text-sm text-muted-foreground">Carregando eventos locais…</p> : timeline.data?.length ? <ol className="relative space-y-4 border-s border-white/10 ps-6">{timeline.data.map((event) => <li key={event.id} className="relative"><span className="absolute -start-[31px] top-1 grid h-4 w-4 place-items-center rounded-full border border-emerald-400/30 bg-background"><CheckCircle2 className="h-2.5 w-2.5 text-emerald-300" /></span><div className="rounded-xl border bg-card/40 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-medium">{event.label}</p><Badge variant="outline" className="font-tech text-[9px]">{event.eventType}</Badge></div><p className="mt-1 text-xs text-muted-foreground">{new Date(event.createdAt).toLocaleString("pt-BR")}</p><p className="mt-3 text-xs leading-5 text-muted-foreground">{event.detailsJson === "{}" ? "Sem detalhes adicionais registrados." : "Detalhes técnicos disponíveis no registro local."}</p></div></li>)}</ol> : <div className="rounded-xl border border-dashed p-8 text-center"><CircleDotDashed className="mx-auto h-7 w-7 text-primary" /><p className="mt-3 font-medium">Nenhum evento técnico foi salvo neste dispositivo.</p><p className="mt-1 text-sm text-muted-foreground">Ao capturar um snapshot, o Stray registra a leitura na timeline local.</p><Link href="/snapshots" className="mt-4 inline-flex items-center gap-2 text-sm font-medium text-primary hover:underline"><ScanLine className="h-4 w-4" />Abrir Snapshots</Link></div>}</CardContent></Card></div></main></div>;
}
