import { Button } from "@/components/ui/button";
import { appImageInstallPath } from "@/lib/distribution";
import { AlertTriangle, ArrowDownRight, ArrowLeft, CheckCircle2, ExternalLink, FileWarning, HardDrive, MonitorSmartphone, ShieldCheck } from "lucide-react";
import { Link } from "wouter";

const removalTargets = [
  { title: "Windows 10/11", label: "INSTALADOR NSIS", instruction: "Abra Configurações › Aplicativos › Aplicativos instalados, localize Stray Linux e escolha Desinstalar.", command: "Use o atalho ‘Desinstalar Stray Linux’ criado pelo instalador, se ele estiver disponível no menu Iniciar.", note: "O instalador Windows registra a remoção do aplicativo. Não apague arquivos do programa manualmente antes de concluir esse processo.", source: "Orientações da Microsoft", sourceUrl: "https://support.microsoft.com/windows/repair-apps-and-programs-in-windows-0b6afbd4-45f0-3b3a-2b05-5a035a604c5a" },
  { title: "Debian · Ubuntu", label: "PACOTE .DEB", instruction: "Remova o pacote instalado pelo APT.", command: "sudo apt remove stray-linux", note: "Use purge apenas se você souber que deseja remover também arquivos de configuração tratados pelo gerenciador de pacotes.", source: "Manual do APT", sourceUrl: "https://manpages.debian.org/apt/apt.8.en.html" },
  { title: "Fedora · RHEL", label: "PACOTE .RPM", instruction: "Remova o pacote pelo DNF.", command: "sudo dnf remove stray-linux", note: "O comando trata o pacote instalado; dados da sua conta e perfis locais não são parte desse pedido de remoção.", source: "Documentação do DNF", sourceUrl: "https://dnf.readthedocs.io/en/latest/command_ref.html" },
  { title: "openSUSE", label: "PACOTE .RPM", instruction: "Remova o pacote pelo Zypper.", command: "sudo zypper remove stray-linux", note: "Confirme a lista exibida pelo Zypper antes de aceitar qualquer mudança no sistema.", source: "Documentação do Zypper", sourceUrl: "https://documentation.suse.com/sles/15-SP4/html/SLES-all/cha-sw-cl.html" },
  { title: "Arch · derivadas", label: "PACOTE LOCAL", instruction: "Remova o pacote pelo Pacman.", command: "sudo pacman -R stray-linux", note: "O pacote foi instalado localmente; ele não pertence ao repositório oficial do Arch. Este comando remove o aplicativo, não os dados locais.", source: "Manual do Pacman", sourceUrl: "https://man.archlinux.org/man/pacman.8" },
  { title: "AppImage", label: "ARQUIVO PORTÁTIL", instruction: "Remova o executável AppImage instalado pelo comando publicado.", command: `rm -f "${appImageInstallPath}"`, note: "Se você criou manualmente um atalho no menu do sistema, remova esse atalho de forma separada. Este comando não remove configurações ou dados locais.", source: "Documentação AppImage", sourceUrl: "https://docs.appimage.org/" },
];

export default function Uninstall() {
  return <div className="min-h-screen bg-[#f0f0ec] text-[#0b0c10]"><PublicHeader /><main>
    <section className="border-b border-black/15 px-4 pb-6 pt-4 sm:px-6 lg:px-8"><div className="relative mx-auto max-w-[1536px] overflow-hidden rounded-[1.75rem] bg-[#0b0c10] px-6 py-8 text-[#f5f5f0] sm:px-9 sm:py-12 lg:px-12">
      <div className="editorial-grid absolute inset-0 opacity-35" aria-hidden="true" />
      <div className="relative"><Link href="/"><Button variant="ghost" size="sm" className="-ml-3 text-white/62 hover:bg-white/8 hover:text-white"><ArrowLeft className="mr-2 h-4 w-4" />Voltar ao site</Button></Link>
        <div className="mt-12 grid gap-10 lg:grid-cols-[1fr_.78fr] lg:items-end"><div><p className="font-tech text-[10px] tracking-[.2em] text-[#b7d3ff]">STRAY LINUX / REMOÇÃO CONSCIENTE</p><h1 className="mt-5 max-w-4xl font-serif text-5xl leading-[.86] tracking-[-.07em] sm:text-7xl">Remova com<br /><em className="font-normal text-[#b7d3ff]">clareza.</em></h1><p className="mt-7 max-w-2xl text-sm leading-7 text-white/65 sm:text-base">Escolha o método que corresponde ao formato instalado. A remoção do aplicativo e a exclusão de dados locais são decisões separadas para evitar perda acidental de perfis, relatórios e configurações.</p></div>
          <aside className="border border-white/15 bg-white/[.055] p-5 backdrop-blur-sm"><p className="font-tech text-[9px] tracking-[.18em] text-white/50">ANTES DE REMOVER</p><div className="mt-6 space-y-5"><InfoItem icon={ShieldCheck} title="A remoção não é limpeza total" text="Desinstalar o aplicativo não apaga automaticamente configurações ou dados locais." /><InfoItem icon={HardDrive} title="Dados locais continuam sendo seus" text="Perfis, histórico e SQLite podem ser úteis em uma reinstalação futura." /><InfoItem icon={FileWarning} title="Exporte antes, se precisar" text="Copie uma leitura do Scanner ou dados do aplicativo antes de qualquer exclusão manual." /></div></aside>
        </div>
        <div className="mt-10 border-t border-white/12 pt-5"><div className="flex gap-3 rounded-xl border border-[#b7d3ff]/25 bg-[#b7d3ff]/[.07] p-4"><AlertTriangle className="mt-0.5 h-4 w-4 shrink-0 text-[#d6e4ff]" /><p className="text-xs leading-6 text-white/68"><strong className="font-medium text-white">Não execute comandos de outra distribuição.</strong> Os comandos abaixo usam o nome de pacote confirmado nos artefatos publicados da versão atual: <code className="text-[#d6e4ff]">stray-linux</code>.</p></div></div>
      </div>
    </div></section>

    <section className="px-4 py-20 sm:px-6 sm:py-28 lg:px-8"><div className="mx-auto max-w-[1536px]"><div className="grid gap-8 border-b border-black/15 pb-10 lg:grid-cols-[.72fr_1.28fr] lg:items-end"><div><p className="font-tech text-[10px] tracking-[.2em] text-black/48">MÉTODO POR PLATAFORMA</p><p className="mt-5 max-w-xs text-sm leading-6 text-black/60">Use somente o comando que corresponde ao formato instalado. Cada cartão descreve escopo, risco e fonte oficial.</p></div><h2 className="font-serif text-5xl leading-[.9] tracking-[-.07em] sm:text-7xl">Remoção por<br /><em className="font-normal">formato instalado.</em></h2></div><div className="mt-8 grid gap-px overflow-hidden border border-black/15 bg-black/15 md:grid-cols-2 xl:grid-cols-3">{removalTargets.map((target) => <RemovalCard key={target.title} {...target} />)}</div></div></section>

    <section className="bg-[#d9e4ff] px-4 py-20 sm:px-6 sm:py-24 lg:px-8"><div className="mx-auto grid max-w-[1536px] gap-8 lg:grid-cols-[.72fr_1.28fr]"><div><p className="font-tech text-[10px] tracking-[.2em] text-black/50">DADOS LOCAIS / ESCOLHA EXPLÍCITA</p><h2 className="mt-5 font-serif text-4xl leading-[.92] tracking-[-.06em] sm:text-6xl">Remover o app<br /><em className="font-normal">não apaga seus dados.</em></h2><p className="mt-6 max-w-md text-sm leading-7 text-black/62">Não há um comando automático de limpeza porque essa decisão pode apagar históricos úteis. Primeiro desinstale; depois avalie separadamente se seus dados ainda devem ficar no dispositivo.</p></div><div className="space-y-3"><DataLocation platform="Windows" location="%APPDATA%\Stray Linux" detail="Local típico de dados de usuário do aplicativo Electron." /><DataLocation platform="Linux" location="$XDG_CONFIG_HOME/Stray Linux ou ~/.config/Stray Linux" detail="Local típico de preferências e dados de usuário conforme o ambiente." /><div className="border border-black/15 bg-[#f8f8f5] p-5 text-xs leading-6 text-black/60"><CheckCircle2 className="mr-2 inline h-4 w-4 text-black" />Se decidir apagar dados manualmente, confirme o caminho no seu sistema e feche o Stray Linux antes. Essa remoção é opcional e não é necessária para desinstalar o aplicativo.</div></div></div></section>
  </main><PublicFooter /></div>;
}

function PublicHeader() { return <header className="sticky top-0 z-40 border-b border-black/10 bg-[#f0f0ec]/90 text-black backdrop-blur-xl"><div className="mx-auto flex h-[72px] max-w-[1536px] items-center justify-between px-4 sm:px-6 lg:px-8"><Link href="/" className="group flex items-center gap-3" aria-label="Stray Linux, início"><span className="grid h-11 w-11 place-items-center overflow-hidden rounded-full border border-black/15 bg-[#0b0c10]"><img className="h-full w-full object-contain p-0.5" src="/manus-storage/stray-linux-logo-2026_a7444aa6.png" alt="Logo Stray Linux" /></span><span className="text-xs font-bold leading-[.85] tracking-[-.03em]">STRAY<br />LINUX</span></Link><Link href="/download"><Button size="sm" className="rounded-full bg-[#0b0c10] px-4 text-white hover:bg-[#252936]">Downloads <ArrowDownRight className="ml-2 h-3.5 w-3.5" /></Button></Link></div></header>; }
function PublicFooter() { return <footer className="border-t border-white/12 bg-[#0b0c10] text-white/55"><div className="mx-auto flex max-w-[1536px] flex-col gap-3 px-4 py-8 text-xs sm:flex-row sm:items-center sm:justify-between sm:px-6 lg:px-8"><span>© 2026 Stray Linux.</span><span>Criado por Pedro, Brasil.</span><Link href="/download" className="inline-flex items-center gap-1 hover:text-white">Downloads <ExternalLink className="h-3 w-3" /></Link></div></footer>; }
function InfoItem({ icon: Icon, title, text }: { icon: typeof ShieldCheck; title: string; text: string }) { return <div className="flex gap-3"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full border border-white/12 bg-white/[.04]"><Icon className="h-4 w-4 text-[#b7d3ff]" /></span><div><p className="text-sm font-medium text-white">{title}</p><p className="mt-1 text-xs leading-5 text-white/52">{text}</p></div></div>; }
function RemovalCard({ title, label, instruction, command, note, source, sourceUrl }: (typeof removalTargets)[number]) { return <article className="flex min-h-[285px] flex-col bg-[#f8f8f5] p-5"><p className="font-tech text-[9px] tracking-[.15em] text-black/48">{label}</p><h3 className="mt-3 text-xl font-medium tracking-[-.04em]">{title}</h3><p className="mt-4 text-sm leading-6 text-black/60">{instruction}</p><code className="mt-5 block rounded-xl border border-black/12 bg-black/[.035] p-3 font-tech text-[11px] leading-6 text-black/78">{command}</code><p className="mt-4 text-xs leading-5 text-black/48">{note}</p><a className="mt-auto pt-5 text-xs text-black/58 transition-colors hover:text-black" href={sourceUrl} target="_blank" rel="noreferrer"><ExternalLink className="mr-1.5 inline h-3.5 w-3.5" />{source}</a></article>; }
function DataLocation({ platform, location, detail }: { platform: string; location: string; detail: string }) { return <div className="border border-black/15 bg-[#f8f8f5] p-5"><div className="flex items-center gap-2"><MonitorSmartphone className="h-4 w-4" /><span className="text-sm font-medium">{platform}</span></div><code className="mt-3 block break-all font-tech text-[11px] leading-6 text-black/78">{location}</code><p className="mt-2 text-xs leading-5 text-black/50">{detail}</p></div>; }
