import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Activity, Cpu, HardDrive, MemoryStick, Monitor, ScanSearch } from "lucide-react";
import { Link } from "wouter";
import { Button } from "@/components/ui/button";

type ScanDetails = {
  architecture?: string | null;
  cpu?: { model?: string | null; physicalCores?: number | null; logicalCores?: number | null; maxMhz?: number | null };
  gpu?: { model?: string | null; vendor?: string | null; vramMb?: number | null; adapters?: { model?: string | null; vendor?: string | null; vramMb?: number | null }[] };
  memoryGb?: number | null;
  storage?: { totalGb?: number | null; usedGb?: number | null; filesystem?: string | null } | null;
  displays?: { name?: string | null; resolution?: string | null; refreshHz?: number | null }[];
  graphics?: { driverVersion?: string | null; mesaVersion?: string | null; vulkanVersion?: string | null; openGlRenderer?: string | null };
  runtime?: { protonTools?: string[]; steamDetected?: boolean; steamInstallKinds?: string[]; installedGameCount?: number; gaming?: { sessionType?: string | null; waylandDetected?: boolean; x11Detected?: boolean; gameModeDetected?: boolean; mangoHudDetected?: boolean; gamescopeDetected?: boolean } };
  desktopEnvironment?: string | null;
};

function field(value: string | number | null | undefined, fallback = "Não informado") { return value === null || value === undefined || value === "" ? fallback : String(value); }

export function HardwareScanSnapshot({ profile }: { profile: any }) {
  const details = profile?.scanDetails as ScanDetails | null | undefined;
  if (!profile || !details) return <Card className="border-dashed"><CardContent className="p-8 text-center"><ScanSearch className="mx-auto h-7 w-7 text-primary" /><h2 className="mt-4 font-semibold">Ainda não há snapshot técnico neste perfil</h2><p className="mx-auto mt-2 max-w-lg text-sm leading-6 text-muted-foreground">Execute o Stray Scan para registrar localmente CPU, GPUs, APIs gráficas, sessão, ferramentas e capacidade detectada. Campos não disponíveis continuam explícitos.</p><Link href="/scanner"><Button className="mt-5" variant="outline">Abrir Scanner</Button></Link></CardContent></Card>;
  const capacities = [{ label: "RAM", value: details.memoryGb }, { label: "VRAM", value: details.gpu?.vramMb ? Math.round(details.gpu.vramMb / 1024) : null }, { label: "Disco", value: details.storage?.totalGb ?? null }].filter((item): item is { label: string; value: number } => typeof item.value === "number" && item.value > 0);
  const signals = [{ label: "Steam", active: Boolean(details.runtime?.steamDetected) }, { label: "Vulkan", active: Boolean(details.graphics?.vulkanVersion) }, { label: "Wayland", active: Boolean(details.runtime?.gaming?.waylandDetected) }, { label: "X11", active: Boolean(details.runtime?.gaming?.x11Detected) }, { label: "GameMode", active: Boolean(details.runtime?.gaming?.gameModeDetected) }, { label: "MangoHud", active: Boolean(details.runtime?.gaming?.mangoHudDetected) }, { label: "Gamescope", active: Boolean(details.runtime?.gaming?.gamescopeDetected) }];
  return <section className="space-y-5"><Card className="border-cyan-400/20 bg-cyan-400/[0.035]"><CardHeader><p className="evidence-label text-cyan-300">STRAY SCAN / INVENTÁRIO LOCAL</p><CardTitle className="mt-2 flex items-center gap-2"><Activity className="h-5 w-5 text-cyan-300" />{profile.name}</CardTitle><CardDescription>Snapshot local registrado em {profile.scannedAt ? new Date(profile.scannedAt).toLocaleString() : "data não informada"}. Estes dados não representam benchmark, FPS ou garantia de compatibilidade.</CardDescription></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><SnapshotMetric icon={Cpu} label="CPU" value={field(details.cpu?.model, profile.detectedCpu)} note={[details.cpu?.physicalCores && `${details.cpu.physicalCores} físicos`, details.cpu?.logicalCores && `${details.cpu.logicalCores} lógicos`].filter(Boolean).join(" · ") || field(details.architecture)} /><SnapshotMetric icon={MemoryStick} label="Memória" value={details.memoryGb ? `${details.memoryGb} GB` : field(profile.detectedRamGb ? `${profile.detectedRamGb} GB` : null)} note={details.cpu?.maxMhz ? `${details.cpu.maxMhz} MHz máx. da CPU` : "Capacidade detectada"} /><SnapshotMetric icon={Monitor} label="GPU principal" value={[details.gpu?.vendor, details.gpu?.model || profile.detectedGpu].filter(Boolean).join(" ") || "Não informada"} note={details.gpu?.vramMb ? `${details.gpu.vramMb} MB VRAM` : "VRAM não informada"} /><SnapshotMetric icon={HardDrive} label="Armazenamento" value={details.storage?.totalGb ? `${details.storage.usedGb ?? "—"} / ${details.storage.totalGb} GB` : "Não informado"} note={field(details.storage?.filesystem, "Sistema de arquivos não informado")} /></CardContent></Card>
    <div className="grid gap-5 xl:grid-cols-[1.05fr_.95fr]"><Card><CardHeader><p className="evidence-label text-primary">CAPACIDADES DETECTADAS</p><CardTitle className="mt-1 text-lg">Memória e armazenamento</CardTitle><CardDescription>Unidades em GB. O gráfico apenas apresenta as leituras do Scanner, sem estimar velocidade ou desempenho.</CardDescription></CardHeader><CardContent>{capacities.length ? <div className="h-56"><ResponsiveContainer width="100%" height="100%"><BarChart data={capacities} layout="vertical" margin={{ left: 8, right: 20, top: 4, bottom: 4 }}><CartesianGrid horizontal={false} strokeDasharray="3 3" stroke="hsl(var(--border))" /><XAxis type="number" tickLine={false} axisLine={false} unit=" GB" /><YAxis type="category" dataKey="label" width={72} tickLine={false} axisLine={false} /><Tooltip formatter={(value) => [`${value} GB`, "Detectado"]} /><Bar dataKey="value" fill="hsl(var(--primary))" radius={[0, 5, 5, 0]} /></BarChart></ResponsiveContainer></div> : <p className="rounded-xl border border-dashed p-5 text-sm text-muted-foreground">Não há leituras numéricas suficientes neste snapshot para criar um gráfico.</p>}</CardContent></Card><Card><CardHeader><p className="evidence-label text-cyan-300">AMBIENTE GRÁFICO</p><CardTitle className="mt-1 text-lg">APIs e ferramentas observadas</CardTitle><CardDescription>Marcadores de disponibilidade local; eles não constituem um score de saúde.</CardDescription></CardHeader><CardContent className="grid grid-cols-2 gap-2">{signals.map((signal) => <div key={signal.label} className={`rounded-xl border p-3 ${signal.active ? "border-emerald-400/25 bg-emerald-400/[0.05]" : "border-white/10 bg-card/40"}`}><span className={`block h-1.5 w-8 rounded-full ${signal.active ? "bg-emerald-400" : "bg-muted-foreground/30"}`} /><p className="mt-3 font-tech text-xs tracking-wide">{signal.label}</p><p className="mt-1 text-xs text-muted-foreground">{signal.active ? "Detectado" : "Não detectado"}</p></div>)}</CardContent></Card></div>
    <div className="grid gap-5 xl:grid-cols-2"><DetailPanel title="Pilha gráfica" rows={["Driver", field(details.graphics?.driverVersion, profile.driverVersion), "Mesa", field(details.graphics?.mesaVersion), "Vulkan", field(details.graphics?.vulkanVersion), "Renderer OpenGL", field(details.graphics?.openGlRenderer)]} /><DetailPanel title="Runtime e telas" rows={["Steam", details.runtime?.steamDetected ? `Detectado${details.runtime.installedGameCount !== undefined ? ` · ${details.runtime.installedGameCount} instalações` : ""}` : "Não detectado", "Instalação", details.runtime?.steamInstallKinds?.join(" + ") || "Não informada", "Proton", details.runtime?.protonTools?.join(", ") || profile.protonVersion || "Não informado", "Monitores", details.displays?.length ? details.displays.map((display) => `${display.name || "Monitor"} ${display.resolution || ""}${display.refreshHz ? ` @ ${display.refreshHz} Hz` : ""}`).join(" · ") : "Não informados"]} /></div>
  </section>;
}

function SnapshotMetric({ icon: Icon, label, value, note }: { icon: typeof Cpu; label: string; value: string; note: string }) { return <div className="rounded-xl border border-cyan-400/15 bg-background/45 p-4"><Icon className="h-4 w-4 text-cyan-300" /><p className="mt-3 font-tech text-[10px] tracking-[0.1em] text-muted-foreground">{label}</p><p className="mt-1 font-medium">{value}</p><p className="mt-1 text-xs text-muted-foreground">{note}</p></div>; }

function DetailPanel({ title, rows }: { title: string; rows: string[] }) { const pairs = Array.from({ length: Math.ceil(rows.length / 2) }, (_, index) => [rows[index * 2], rows[index * 2 + 1]]); return <Card><CardHeader><CardTitle className="text-base">{title}</CardTitle></CardHeader><CardContent className="space-y-3">{pairs.map(([label, value]) => <div key={label} className="flex items-start justify-between gap-4 border-b border-white/8 pb-3 last:border-0 last:pb-0"><span className="text-xs text-muted-foreground">{label}</span><span className="max-w-[65%] text-right text-sm">{value}</span></div>)}</CardContent></Card>; }
