import { Activity, Check, Cpu, HardDrive, MemoryStick, Monitor, ScanSearch, X } from "lucide-react";
import { RadialBar, RadialBarChart, ResponsiveContainer } from "recharts";
import { Link } from "wouter";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";

type ScanDetails = {
  architecture?: string | null;
  cpu?: { model?: string | null; physicalCores?: number | null; logicalCores?: number | null; maxMhz?: number | null };
  gpu?: { model?: string | null; vendor?: string | null; vramMb?: number | null; adapters?: { model?: string | null; vendor?: string | null; vramMb?: number | null }[] };
  memoryGb?: number | null;
  storage?: { totalGb?: number | null; usedGb?: number | null; filesystem?: string | null; mount?: string | null } | null;
  displays?: { name?: string | null; resolution?: string | null; refreshHz?: number | null }[];
  graphics?: { driverVersion?: string | null; mesaVersion?: string | null; vulkanVersion?: string | null; openGlRenderer?: string | null };
  runtime?: { protonTools?: string[]; steamDetected?: boolean; installedGameCount?: number; discovery?: { heroicDetected?: boolean; heroicInstalledGameCount?: number }; gaming?: { sessionType?: string | null; gameModeDetected?: boolean; mangoHudDetected?: boolean; gamescopeDetected?: boolean; renderGroupDetected?: boolean } };
};

function field(value: string | number | null | undefined, fallback = "Não informado") { return value === null || value === undefined || value === "" ? fallback : String(value); }

export function HardwareScanSnapshot({ profile }: { profile: any }) {
  const details = profile?.scanDetails as ScanDetails | null | undefined;
  if (!profile || !details) return <Card className="border-dashed"><CardContent className="p-8 text-center"><ScanSearch className="mx-auto h-7 w-7 text-primary" /><h2 className="mt-4 font-semibold">Ainda não há snapshot técnico neste perfil</h2><p className="mx-auto mt-2 max-w-lg text-sm leading-6 text-muted-foreground">Execute o Stray Scan para registrar localmente CPU, GPUs, APIs gráficas, sessão, ferramentas e capacidade detectada. Campos não disponíveis continuam explícitos.</p><Link href="/scanner"><Button className="mt-5" variant="outline">Abrir Scanner</Button></Link></CardContent></Card>;

  const storageTotal = details.storage?.totalGb ?? null;
  const storageUsed = details.storage?.usedGb ?? null;
  const storagePercent = storageTotal && storageUsed !== null ? Math.min(100, Math.max(0, Math.round((storageUsed / storageTotal) * 100))) : null;
  const adapters = details.gpu?.adapters?.length ? details.gpu.adapters : [{ model: details.gpu?.model, vendor: details.gpu?.vendor, vramMb: details.gpu?.vramMb }];
  const signals = [
    { label: "Vulkan", active: Boolean(details.graphics?.vulkanVersion), detail: details.graphics?.vulkanVersion || "não informado" },
    { label: "Steam", active: Boolean(details.runtime?.steamDetected), detail: details.runtime?.installedGameCount !== undefined ? `${details.runtime.installedGameCount} instalação(ões)` : "não detectado" },
    { label: "Heroic", active: Boolean(details.runtime?.discovery?.heroicDetected), detail: details.runtime?.discovery?.heroicInstalledGameCount !== undefined ? `${details.runtime.discovery.heroicInstalledGameCount} instalação(ões)` : "não detectado" },
    { label: "GameMode", active: Boolean(details.runtime?.gaming?.gameModeDetected), detail: details.runtime?.gaming?.gameModeDetected ? "binário disponível" : "não detectado" },
    { label: "MangoHud", active: Boolean(details.runtime?.gaming?.mangoHudDetected), detail: details.runtime?.gaming?.mangoHudDetected ? "binário disponível" : "não detectado" },
    { label: "Gamescope", active: Boolean(details.runtime?.gaming?.gamescopeDetected), detail: details.runtime?.gaming?.gamescopeDetected ? "binário disponível" : "não detectado" },
  ];

  return <section className="space-y-5">
    <Card className="border-white/15 bg-card/55 shadow-[0_20px_70px_rgba(0,0,0,.16)]"><CardHeader><p className="evidence-label text-primary">STRAY SCAN / INVENTÁRIO LOCAL</p><CardTitle className="mt-2 flex items-center gap-2"><Activity className="h-5 w-5 text-primary" />{profile.name}</CardTitle><CardDescription>Snapshot local registrado em {profile.scannedAt ? new Date(profile.scannedAt).toLocaleString() : "data não informada"}. Capacidades são inventário; somente o uso de disco é mostrado como proporção.</CardDescription></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><InventoryMetric icon={Cpu} label="CPU" value={field(details.cpu?.model, profile.detectedCpu)} note={[details.cpu?.physicalCores && `${details.cpu.physicalCores} núcleos`, details.cpu?.logicalCores && `${details.cpu.logicalCores} threads`].filter(Boolean).join(" · ") || field(details.architecture)} /><InventoryMetric icon={MemoryStick} label="MEMÓRIA" value={details.memoryGb ? `${details.memoryGb} GB` : field(profile.detectedRamGb ? `${profile.detectedRamGb} GB` : null)} note={details.cpu?.maxMhz ? `${details.cpu.maxMhz} MHz máx. reportado` : "capacidade detectada"} /><InventoryMetric icon={Monitor} label="GPU PRINCIPAL" value={[details.gpu?.vendor, details.gpu?.model || profile.detectedGpu].filter(Boolean).join(" ") || "Não informada"} note={details.gpu?.vramMb ? `${Math.round(details.gpu.vramMb / 1024 * 10) / 10} GB VRAM` : "VRAM não informada"} /><InventoryMetric icon={HardDrive} label="ARMAZENAMENTO" value={storageTotal ? `${storageUsed ?? "—"} / ${storageTotal} GB` : "Não informado"} note={[details.storage?.mount, details.storage?.filesystem].filter(Boolean).join(" · ") || "ponto não informado"} /></CardContent></Card>
    <div className="grid gap-5 xl:grid-cols-[.78fr_1.22fr]"><Card><CardHeader><p className="evidence-label text-primary">LEITURA PROPORCIONAL</p><CardTitle className="mt-1 text-lg">Ocupação do armazenamento</CardTitle><CardDescription>Espaço usado sobre a capacidade detectada na montagem observada.</CardDescription></CardHeader><CardContent>{storagePercent === null ? <AbsentState label="Uso do disco indisponível" text="O Scanner não recebeu capacidade e uso suficientes para criar uma proporção segura." /> : <div className="grid min-h-60 grid-cols-[10rem_1fr] items-center gap-3"><div className="h-40"><ResponsiveContainer width="100%" height="100%"><RadialBarChart cx="50%" cy="50%" innerRadius="65%" outerRadius="94%" startAngle={90} endAngle={-270} barSize={14} data={[{ value: storagePercent, fill: "hsl(var(--primary))" }]}><RadialBar background={{ fill: "hsl(var(--muted))" }} dataKey="value" cornerRadius={10} /></RadialBarChart></ResponsiveContainer></div><div><p className="font-tech text-4xl font-medium tabular-nums">{storagePercent}%</p><p className="mt-1 text-sm text-muted-foreground">{storageUsed} GB usados de {storageTotal} GB</p><p className="mt-5 border-t pt-4 text-sm">{field(details.storage?.mount, "/")}</p></div></div>}</CardContent></Card><Card><CardHeader><p className="evidence-label text-primary">AMBIENTE DE EXECUÇÃO</p><CardTitle className="mt-1 text-lg">Matriz de runtime local</CardTitle><CardDescription>Presença observada de APIs e ferramentas. Não é uma nota de saúde, benchmark ou garantia de compatibilidade.</CardDescription></CardHeader><CardContent className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{signals.map((signal) => <RuntimeSignal key={signal.label} {...signal} />)}</CardContent></Card></div>
    <div className="grid gap-5 xl:grid-cols-[1.08fr_.92fr]"><Card><CardHeader><p className="evidence-label text-primary">TOPOLOGIA GRÁFICA</p><CardTitle className="mt-1 text-lg">Adaptadores e telas detectados</CardTitle><CardDescription>Inventário de dispositivos; nenhuma preferência de GPU ou desempenho é presumido.</CardDescription></CardHeader><CardContent className="space-y-3">{adapters.map((adapter, index) => <div key={`${adapter.model}-${index}`} className="grid gap-2 rounded-xl border border-white/10 bg-black/[.12] p-4 sm:grid-cols-[auto_1fr_auto]"><span className="grid h-9 w-9 place-items-center rounded-lg border border-white/10"><Monitor className="h-4 w-4 text-primary" /></span><div><p className="font-medium">{[adapter.vendor, adapter.model].filter(Boolean).join(" ") || "Adaptador não identificado"}</p><p className="mt-1 text-xs text-muted-foreground">{adapter.vramMb ? `${Math.round(adapter.vramMb / 1024 * 10) / 10} GB VRAM reportada` : "VRAM não reportada"}</p></div><span className="font-tech text-[10px] tracking-[.12em] text-muted-foreground">GPU {index + 1}</span></div>)}{details.displays?.length ? <div className="border-t border-white/10 pt-3 text-sm text-muted-foreground">{details.displays.map((display) => <p key={`${display.name}-${display.resolution}`}>{display.name || "Monitor"} · {display.resolution || "resolução não informada"}{display.refreshHz ? ` · ${display.refreshHz} Hz` : ""}</p>)}</div> : <p className="border-t border-white/10 pt-3 text-sm text-muted-foreground">Nenhum monitor foi reportado nesta sessão.</p>}</CardContent></Card><div className="grid gap-5"><DetailPanel title="Pilha gráfica" rows={["Driver", field(details.graphics?.driverVersion, profile.driverVersion), "Mesa", field(details.graphics?.mesaVersion), "Vulkan", field(details.graphics?.vulkanVersion), "Renderer OpenGL", field(details.graphics?.openGlRenderer)]} /><DetailPanel title="Runtime detectado" rows={["Sessão", field(details.runtime?.gaming?.sessionType), "Steam", details.runtime?.steamDetected ? `Detectado${details.runtime.installedGameCount !== undefined ? ` · ${details.runtime.installedGameCount} instalação(ões)` : ""}` : "Não detectado", "Proton", details.runtime?.protonTools?.join(", ") || profile.protonVersion || "Não informado", "Render/video", details.runtime?.gaming?.renderGroupDetected ? "Grupo detectado" : "Não confirmado"]} /></div></div>
  </section>;
}

function InventoryMetric({ icon: Icon, label, value, note }: { icon: typeof Cpu; label: string; value: string; note: string }) { return <div className="rounded-xl border border-white/10 bg-black/[.12] p-4"><Icon className="h-4 w-4 text-primary" /><p className="mt-3 font-tech text-[10px] tracking-[.13em] text-muted-foreground">{label}</p><p className="mt-1 line-clamp-2 min-h-10 font-medium leading-5">{value}</p><p className="mt-1 text-xs text-muted-foreground">{note}</p></div>; }
function RuntimeSignal({ label, active, detail }: { label: string; active: boolean; detail: string }) { return <div className={`rounded-xl border p-3 ${active ? "border-white/25 bg-white/[.04]" : "border-white/10 bg-black/[.12]"}`}><div className="flex items-center justify-between gap-3"><p className="font-tech text-xs tracking-[.08em]">{label}</p><span className={`grid h-5 w-5 place-items-center rounded-full border ${active ? "border-white/50 bg-white text-black" : "border-white/15 text-muted-foreground"}`}>{active ? <Check className="h-3 w-3" /> : <X className="h-3 w-3" />}</span></div><p className="mt-3 text-xs text-muted-foreground">{detail}</p></div>; }
function AbsentState({ label, text }: { label: string; text: string }) { return <div className="grid min-h-60 place-items-center rounded-xl border border-dashed p-6 text-center"><div><p className="font-medium">{label}</p><p className="mt-2 max-w-sm text-sm leading-6 text-muted-foreground">{text}</p></div></div>; }
function DetailPanel({ title, rows }: { title: string; rows: string[] }) { const pairs = Array.from({ length: Math.ceil(rows.length / 2) }, (_, index) => [rows[index * 2], rows[index * 2 + 1]]); return <Card><CardHeader className="pb-3"><CardTitle className="text-base">{title}</CardTitle></CardHeader><CardContent className="space-y-3">{pairs.map(([label, value]) => <div key={label} className="flex items-start justify-between gap-4 border-b border-white/8 pb-3 last:border-0 last:pb-0"><span className="font-tech text-[10px] tracking-[.1em] text-muted-foreground">{label}</span><span className="max-w-[65%] text-right text-sm">{value}</span></div>)}</CardContent></Card>; }
