import { ArrowUpRight, Boxes, LockKeyhole, PackageCheck } from "lucide-react";

const principles = [
  { code: "01 / LOCAL", icon: Boxes, title: "Leitura no seu ambiente.", body: "Scanner, biblioteca e sessões começam no dispositivo. O app declara ausência de dados em vez de completar hardware, runtimes ou resultados por suposição.", href: "/download", action: "Ver formatos" },
  { code: "02 / CONTROLE", icon: LockKeyhole, title: "Nenhuma ação escondida.", body: "Prévia de pacotes é somente leitura. Importação MangoHud é escolhida pelo usuário. O Stray não limpa, remove, eleva privilégio ou envia telemetria automaticamente.", href: "/uninstall", action: "Ver desinstalação" },
  { code: "03 / ENTREGA", icon: PackageCheck, title: "Um formato para cada sistema.", body: "Downloads estáveis usam o pacote correto por família e sidecar SHA-256. O atualizador usa feed HTTPS separado e pede confirmação antes de reiniciar.", href: "/download", action: "Abrir downloads" },
];

export function SiteTrustGrid() {
  return <section className="bg-[#0b0c10] px-4 py-20 text-[#f5f5f0] sm:px-6 sm:py-28 lg:px-8"><div className="mx-auto max-w-[1536px]"><div className="grid gap-8 border-b border-white/12 pb-10 lg:grid-cols-[.72fr_1.28fr] lg:items-end"><div><p className="font-tech text-[10px] font-bold tracking-[.2em] text-[#a9c7ff]">PRINCÍPIOS DE PRODUTO</p><p className="mt-5 max-w-xs text-sm leading-6 text-white/58">O site descreve limites verificáveis do produto. Não substitui a leitura do computador nem promete compatibilidade sem registro.</p></div><h2 className="max-w-4xl font-serif text-5xl leading-[.9] tracking-[-.07em] sm:text-7xl">Clareza antes<br /><em className="font-normal text-[#b7d3ff]">de qualquer ação.</em></h2></div><div className="grid lg:grid-cols-3">{principles.map(({ code, icon: Icon, title, body, href, action }, index) => <article key={code} className={`group min-h-[290px] px-1 py-10 lg:px-8 ${index > 0 ? "lg:border-l lg:border-white/12" : "lg:pl-0"}`}><div className="flex items-start justify-between"><span className="font-tech text-[10px] tracking-[.18em] text-white/42">{code}</span><Icon className="h-5 w-5 text-[#a9c7ff]" /></div><h3 className="mt-14 max-w-sm text-3xl font-medium leading-[.96] tracking-[-.055em]">{title}</h3><p className="mt-5 max-w-sm text-sm leading-7 text-white/60">{body}</p><a href={href} className="mt-8 inline-flex items-center gap-2 border-b border-white/35 pb-1 text-xs font-medium text-white transition-colors hover:border-[#a9c7ff] hover:text-[#a9c7ff]">{action}<ArrowUpRight className="h-3.5 w-3.5 transition-transform group-hover:-translate-y-0.5 group-hover:translate-x-0.5" /></a></article>)}</div></div></section>;
}
