import { ArrowDownRight, ArrowUpRight } from "lucide-react";
import { LetterReveal } from "./LetterReveal";
import type { LandingCopy } from "./types";

const orbitWords = ["LOCAL FIRST", "FONTES EXPLÍCITAS", "GUIAS POR DISTRO", "SEM FPS FALSO", "DIAGNÓSTICO REAL"];

function ConsoleLine({ label, value }: { label: string; value: string }) { return <div className="flex items-center justify-between gap-4 text-sm"><span className="text-white/52">{label}</span><span className="font-tech text-[10px] tracking-[.12em] text-white">{value}</span></div>; }

export function SiteHero({ copy }: { copy: LandingCopy }) {
  return <section className="relative border-b border-black/15 px-4 pb-6 pt-4 sm:px-6 lg:px-8"><div className="editorial-hero site-hero-depth relative overflow-hidden rounded-[1.75rem] bg-[#0b0c10] text-[#f5f5f0]"><div className="editorial-grid absolute inset-0 opacity-35" aria-hidden="true" /><div className="editorial-sparkles" aria-hidden="true"><i /><i /><i /><i /><i /><i /><i /><i /><i /><i /><i /><i /></div><div className="relative mx-auto grid min-h-[650px] max-w-[1536px] grid-rows-[auto_1fr_auto] p-6 sm:p-9 lg:min-h-[760px] lg:p-12"><div className="flex items-start justify-between gap-5 text-[10px] font-semibold tracking-[.18em] text-white/55"><span>STRAY LINUX — 01/01</span><span className="hidden sm:block">{copy.station}</span></div><div className="relative z-10 grid items-end gap-10 py-12 lg:grid-cols-[1fr_330px] lg:py-16"><div className="max-w-5xl editorial-reveal"><p className="mb-7 font-tech text-[10px] font-bold tracking-[.22em] text-[#8fafff]">{copy.eyebrow}</p><h1 className="font-serif text-[clamp(4rem,11vw,10.5rem)] font-medium leading-[.75] tracking-[-.08em] text-white"><LetterReveal text={copy.heroMain} /><br /><em className="font-normal text-[#b7d3ff]"><LetterReveal text={copy.heroAccent} delay={360} /></em></h1><div className="mt-10 grid max-w-2xl gap-6 sm:grid-cols-[1fr_auto] sm:items-end"><p className="max-w-md text-base leading-7 text-white/66 sm:text-lg">{copy.heroBody}</p><a href="#downloads" className="group inline-flex items-center gap-3 border-b border-white/45 pb-2 text-sm font-medium text-white transition-colors hover:border-[#8fafff] hover:text-[#8fafff]">{copy.chooseFormat} <ArrowDownRight className="h-4 w-4 transition-transform duration-200 group-hover:translate-y-1" /></a></div></div><div className="editorial-console editorial-reveal-delay site-console-glow border border-white/15 bg-white/[.055] p-5 backdrop-blur-sm"><div className="flex items-center justify-between font-tech text-[9px] tracking-[.16em] text-white/45"><span>{copy.statusLocal}</span><span className="h-2 w-2 rounded-full bg-[#a9c7ff] shadow-[0_0_18px_#8fafff]" /></div><div className="mt-8 space-y-5"><ConsoleLine label="Scanner" value={copy.scannerValue} /><ConsoleLine label="Biblioteca" value={copy.libraryValue} /><ConsoleLine label="Evidência" value={copy.evidenceValue} /></div><a href="#como-funciona" className="mt-10 flex items-center justify-between border-t border-white/12 pt-4 text-xs text-white/72 transition-colors hover:text-white"><span>{copy.viewPrinciples}</span><ArrowUpRight className="h-4 w-4" /></a></div></div><div className="flex flex-wrap items-center gap-x-6 gap-y-2 border-t border-white/12 pt-5 font-tech text-[9px] tracking-[.16em] text-white/45">{orbitWords.map((word) => <span key={word} className="inline-flex items-center gap-2"><i className="h-1 w-1 rounded-full bg-[#8fafff]" />{word}</span>)}</div></div></div></section>;
}
