import type { Locale } from "@/contexts/LanguageContext";

type AtlasCopy = {
  guides: string;
  tools: string;
  openMenu: string;
  menuTitle: string;
  menuDescription: string;
  heroTitle: string;
  heroDescription: string;
  start: string;
  startDescription: string;
  family: string;
  familyDescription: string;
  catalog: string;
  catalogDescription: string;
  openPath: string;
  startEyebrow: string;
  startHeading: string;
  startHelp: string;
  catalogCta: string;
  familyEyebrow: string;
  familyHeading: string;
  familyHelp: string;
  catalogEyebrow: string;
  catalogHeading: string;
  catalogHelp: string;
  catalogResultHelp: string;
  profileLink: string;
  referenceLink: string;
  mappedFamily: (count: number) => string;
};

export const atlasNavigationCopy: Record<Locale, AtlasCopy> = {
  "pt-BR": { guides: "Guias", tools: "Ferramentas", openMenu: "Abrir menu de navegação", menuTitle: "Menu de navegação", menuDescription: "Escolha uma área da plataforma.", heroTitle: "Encontre seu caminho no Linux.", heroDescription: "Comece por uma distribuição conhecida, escolha a família de pacotes do seu sistema ou pesquise a lista completa. Os comandos ficam no perfil da distribuição, no momento certo — não em cada resultado.", start: "Começar", startDescription: "Distribuições populares para gaming e seus perfis técnicos.", family: "Por família", familyDescription: "Escolha APT, Pacman, DNF ou Zypper sem comparar dezenas de variantes.", catalog: "Catálogo completo", catalogDescription: "Pesquise as entradas quando já souber o nome.", openPath: "Abrir caminho", startEyebrow: "COMECE AQUI", startHeading: "Distribuições com perfil direto", startHelp: "Escolha uma distribuição. O perfil reúne a verificação do sistema, o formato correto e os próximos passos sem repetir comandos em toda a lista.", catalogCta: "Não encontrou a sua? Pesquisar catálogo", familyEyebrow: "INSTALAÇÃO POR FAMÍLIA", familyHeading: "Escolha o gerenciador de pacotes", familyHelp: "Cada família mostra uma distribuição de referência. Abra o perfil correspondente para conferir formato, arquitetura e a instalação segura.", catalogEyebrow: "CATÁLOGO COMPLETO", catalogHeading: "Pesquise uma distribuição específica", catalogHelp: "Use a busca quando já conhece o nome da distribuição, variante ou família.", catalogResultHelp: "A busca mantém variantes históricas e referências separadas; abra o perfil para ver um comando somente quando houver uma política de instalação segura.", profileLink: "Ver perfil e instalação", referenceLink: "Abrir referência", mappedFamily: (count) => `${count} distribuições mapeadas` },
  en: { guides: "Guides", tools: "Tools", openMenu: "Open navigation menu", menuTitle: "Navigation menu", menuDescription: "Choose an area of the platform.", heroTitle: "Find your way through Linux.", heroDescription: "Start with a known distribution, choose your system's package family, or search the complete list. Commands stay in the distribution profile, at the right moment — not in every result.", start: "Start here", startDescription: "Popular gaming distributions and their technical profiles.", family: "By family", familyDescription: "Choose APT, Pacman, DNF, or Zypper without comparing dozens of variants.", catalog: "Full catalog", catalogDescription: "Search the entries when you already know the name.", openPath: "Open path", startEyebrow: "START HERE", startHeading: "Distributions with a direct profile", startHelp: "Choose a distribution. Its profile gathers the system check, correct format, and next steps without repeating commands throughout the list.", catalogCta: "Can't find yours? Search the catalog", familyEyebrow: "INSTALL BY FAMILY", familyHeading: "Choose the package manager", familyHelp: "Each family shows a reference distribution. Open its profile to check format, architecture, and safe installation.", catalogEyebrow: "FULL CATALOG", catalogHeading: "Search a specific distribution", catalogHelp: "Use search when you already know the distribution, variant, or family name.", catalogResultHelp: "Search keeps historical variants and references separate; open a profile to see a command only when a safe installation policy exists.", profileLink: "View profile and installation", referenceLink: "Open reference", mappedFamily: (count) => `${count} mapped distributions` },
  es: { guides: "Guías", tools: "Herramientas", openMenu: "Abrir menú de navegación", menuTitle: "Menú de navegación", menuDescription: "Elige un área de la plataforma.", heroTitle: "Encuentra tu camino en Linux.", heroDescription: "Empieza con una distribución conocida, elige la familia de paquetes de tu sistema o busca en la lista completa. Los comandos están en el perfil de la distribución, en el momento adecuado, no en cada resultado.", start: "Empezar", startDescription: "Distribuciones populares para gaming y sus perfiles técnicos.", family: "Por familia", familyDescription: "Elige APT, Pacman, DNF o Zypper sin comparar decenas de variantes.", catalog: "Catálogo completo", catalogDescription: "Busca las entradas cuando ya conozcas el nombre.", openPath: "Abrir ruta", startEyebrow: "EMPIEZA AQUÍ", startHeading: "Distribuciones con perfil directo", startHelp: "Elige una distribución. El perfil reúne la comprobación del sistema, el formato correcto y los siguientes pasos sin repetir comandos en toda la lista.", catalogCta: "¿No encuentras la tuya? Buscar catálogo", familyEyebrow: "INSTALACIÓN POR FAMILIA", familyHeading: "Elige el gestor de paquetes", familyHelp: "Cada familia muestra una distribución de referencia. Abre su perfil para comprobar formato, arquitectura e instalación segura.", catalogEyebrow: "CATÁLOGO COMPLETO", catalogHeading: "Busca una distribución específica", catalogHelp: "Usa la búsqueda cuando ya conozcas el nombre de la distribución, variante o familia.", catalogResultHelp: "La búsqueda mantiene separadas variantes históricas y referencias; abre un perfil para ver un comando solo cuando exista una política de instalación segura.", profileLink: "Ver perfil e instalación", referenceLink: "Abrir referencia", mappedFamily: (count) => `${count} distribuciones mapeadas` },
  fr: { guides: "Guides", tools: "Outils", openMenu: "Ouvrir le menu de navigation", menuTitle: "Menu de navigation", menuDescription: "Choisissez une zone de la plateforme.", heroTitle: "Trouvez votre chemin dans Linux.", heroDescription: "Commencez avec une distribution connue, choisissez la famille de paquets de votre système ou recherchez dans la liste complète. Les commandes restent dans le profil de la distribution, au bon moment — pas dans chaque résultat.", start: "Commencer", startDescription: "Distributions populaires pour le jeu et leurs profils techniques.", family: "Par famille", familyDescription: "Choisissez APT, Pacman, DNF ou Zypper sans comparer des dizaines de variantes.", catalog: "Catalogue complet", catalogDescription: "Recherchez les entrées lorsque vous connaissez déjà le nom.", openPath: "Ouvrir le parcours", startEyebrow: "COMMENCEZ ICI", startHeading: "Distributions avec profil direct", startHelp: "Choisissez une distribution. Son profil réunit la vérification du système, le bon format et les prochaines étapes sans répéter les commandes dans toute la liste.", catalogCta: "Vous ne trouvez pas la vôtre ? Rechercher le catalogue", familyEyebrow: "INSTALLATION PAR FAMILLE", familyHeading: "Choisissez le gestionnaire de paquets", familyHelp: "Chaque famille affiche une distribution de référence. Ouvrez son profil pour vérifier le format, l’architecture et l’installation sûre.", catalogEyebrow: "CATALOGUE COMPLET", catalogHeading: "Rechercher une distribution précise", catalogHelp: "Utilisez la recherche lorsque vous connaissez le nom de la distribution, de la variante ou de la famille.", catalogResultHelp: "La recherche sépare les variantes historiques et les références ; ouvrez un profil pour voir une commande seulement lorsqu’une politique d’installation sûre existe.", profileLink: "Voir le profil et l’installation", referenceLink: "Ouvrir la référence", mappedFamily: (count) => `${count} distributions répertoriées` },
  de: { guides: "Anleitungen", tools: "Werkzeuge", openMenu: "Navigationsmenü öffnen", menuTitle: "Navigationsmenü", menuDescription: "Wählen Sie einen Bereich der Plattform.", heroTitle: "Finden Sie Ihren Weg in Linux.", heroDescription: "Beginnen Sie mit einer bekannten Distribution, wählen Sie die Paketfamilie Ihres Systems oder durchsuchen Sie die vollständige Liste. Befehle stehen im Distributionsprofil zum passenden Zeitpunkt — nicht in jedem Ergebnis.", start: "Starten", startDescription: "Beliebte Gaming-Distributionen und ihre technischen Profile.", family: "Nach Familie", familyDescription: "Wählen Sie APT, Pacman, DNF oder Zypper ohne Dutzende Varianten zu vergleichen.", catalog: "Vollständiger Katalog", catalogDescription: "Durchsuchen Sie die Einträge, wenn Sie den Namen bereits kennen.", openPath: "Pfad öffnen", startEyebrow: "HIER STARTEN", startHeading: "Distributionen mit direktem Profil", startHelp: "Wählen Sie eine Distribution. Ihr Profil bündelt Systemprüfung, passendes Format und nächste Schritte ohne Befehle in der gesamten Liste zu wiederholen.", catalogCta: "Nicht gefunden? Katalog durchsuchen", familyEyebrow: "INSTALLATION NACH FAMILIE", familyHeading: "Paketmanager auswählen", familyHelp: "Jede Familie zeigt eine Referenzdistribution. Öffnen Sie ihr Profil, um Format, Architektur und sichere Installation zu prüfen.", catalogEyebrow: "VOLLSTÄNDIGER KATALOG", catalogHeading: "Nach einer bestimmten Distribution suchen", catalogHelp: "Nutzen Sie die Suche, wenn Sie den Namen der Distribution, Variante oder Familie bereits kennen.", catalogResultHelp: "Die Suche trennt historische Varianten und Referenzen; öffnen Sie ein Profil, um einen Befehl nur bei einer sicheren Installationsrichtlinie zu sehen.", profileLink: "Profil und Installation anzeigen", referenceLink: "Referenz öffnen", mappedFamily: (count) => `${count} zugeordnete Distributionen` },
  it: { guides: "Guide", tools: "Strumenti", openMenu: "Apri menu di navigazione", menuTitle: "Menu di navigazione", menuDescription: "Scegli un’area della piattaforma.", heroTitle: "Trova la tua strada in Linux.", heroDescription: "Inizia con una distribuzione conosciuta, scegli la famiglia di pacchetti del sistema o cerca nell’elenco completo. I comandi restano nel profilo della distribuzione, al momento giusto — non in ogni risultato.", start: "Inizia", startDescription: "Distribuzioni popolari per il gaming e i relativi profili tecnici.", family: "Per famiglia", familyDescription: "Scegli APT, Pacman, DNF o Zypper senza confrontare decine di varianti.", catalog: "Catalogo completo", catalogDescription: "Cerca le voci quando conosci già il nome.", openPath: "Apri percorso", startEyebrow: "INIZIA QUI", startHeading: "Distribuzioni con profilo diretto", startHelp: "Scegli una distribuzione. Il profilo riunisce il controllo del sistema, il formato corretto e i passaggi successivi senza ripetere comandi nell’intero elenco.", catalogCta: "Non trovi la tua? Cerca nel catalogo", familyEyebrow: "INSTALLAZIONE PER FAMIGLIA", familyHeading: "Scegli il gestore di pacchetti", familyHelp: "Ogni famiglia mostra una distribuzione di riferimento. Apri il profilo per verificare formato, architettura e installazione sicura.", catalogEyebrow: "CATALOGO COMPLETO", catalogHeading: "Cerca una distribuzione specifica", catalogHelp: "Usa la ricerca quando conosci già il nome della distribuzione, variante o famiglia.", catalogResultHelp: "La ricerca mantiene separate varianti storiche e riferimenti; apri un profilo per vedere un comando solo quando esiste una politica di installazione sicura.", profileLink: "Vedi profilo e installazione", referenceLink: "Apri riferimento", mappedFamily: (count) => `${count} distribuzioni mappate` },
  ru: { guides: "Руководства", tools: "Инструменты", openMenu: "Открыть меню навигации", menuTitle: "Меню навигации", menuDescription: "Выберите раздел платформы.", heroTitle: "Найдите свой путь в Linux.", heroDescription: "Начните со знакомого дистрибутива, выберите семейство пакетов вашей системы или выполните поиск по полному списку. Команды находятся в профиле дистрибутива в нужный момент, а не в каждом результате.", start: "Начать", startDescription: "Популярные игровые дистрибутивы и их технические профили.", family: "По семейству", familyDescription: "Выберите APT, Pacman, DNF или Zypper без сравнения десятков вариантов.", catalog: "Полный каталог", catalogDescription: "Ищите записи, если уже знаете название.", openPath: "Открыть путь", startEyebrow: "НАЧНИТЕ ЗДЕСЬ", startHeading: "Дистрибутивы с прямым профилем", startHelp: "Выберите дистрибутив. В профиле собраны проверка системы, правильный формат и следующие шаги без повторения команд во всём списке.", catalogCta: "Не нашли свой? Искать в каталоге", familyEyebrow: "УСТАНОВКА ПО СЕМЕЙСТВУ", familyHeading: "Выберите менеджер пакетов", familyHelp: "Для каждого семейства показан эталонный дистрибутив. Откройте профиль, чтобы проверить формат, архитектуру и безопасную установку.", catalogEyebrow: "ПОЛНЫЙ КАТАЛОГ", catalogHeading: "Поиск конкретного дистрибутива", catalogHelp: "Используйте поиск, когда знаете название дистрибутива, варианта или семейства.", catalogResultHelp: "Поиск разделяет исторические варианты и справочные записи; откройте профиль, чтобы увидеть команду только при наличии безопасной политики установки.", profileLink: "Открыть профиль и установку", referenceLink: "Открыть справку", mappedFamily: (count) => `${count} дистрибутивов в карте` },
  "zh-CN": { guides: "指南", tools: "工具", openMenu: "打开导航菜单", menuTitle: "导航菜单", menuDescription: "选择平台的一个区域。", heroTitle: "找到你的 Linux 路径。", heroDescription: "从熟悉的发行版开始，选择系统的软件包家族，或搜索完整列表。命令会在正确的时机显示在发行版资料中，而不是每个结果里。", start: "开始", startDescription: "热门游戏发行版及其技术资料。", family: "按家族", familyDescription: "选择 APT、Pacman、DNF 或 Zypper，无需比较数十个变体。", catalog: "完整目录", catalogDescription: "已知名称时可搜索条目。", openPath: "打开路径", startEyebrow: "从这里开始", startHeading: "具有直接资料的发行版", startHelp: "选择一个发行版。资料会集中系统检查、正确格式和后续步骤，不会在整个列表中重复命令。", catalogCta: "没有找到？搜索目录", familyEyebrow: "按家族安装", familyHeading: "选择软件包管理器", familyHelp: "每个家族都会显示一个参考发行版。打开资料以检查格式、架构和安全安装。", catalogEyebrow: "完整目录", catalogHeading: "搜索特定发行版", catalogHelp: "已知发行版、变体或家族名称时使用搜索。", catalogResultHelp: "搜索会将历史变体和参考条目分开；仅在存在安全安装策略时，打开资料才会显示命令。", profileLink: "查看资料和安装", referenceLink: "打开参考", mappedFamily: (count) => `已映射 ${count} 个发行版` },
  ja: { guides: "ガイド", tools: "ツール", openMenu: "ナビゲーションメニューを開く", menuTitle: "ナビゲーションメニュー", menuDescription: "プラットフォームのエリアを選択してください。", heroTitle: "Linux の道筋を見つけましょう。", heroDescription: "よく知られたディストリビューションから始めるか、システムのパッケージファミリーを選択するか、完全な一覧を検索してください。コマンドは各結果ではなく、適切なタイミングでディストリビューションのプロフィールに表示されます。", start: "開始", startDescription: "人気のゲーミングディストリビューションと技術プロフィール。", family: "ファミリー別", familyDescription: "数十のバリアントを比較せずに APT、Pacman、DNF、Zypper を選択できます。", catalog: "完全なカタログ", catalogDescription: "名前が分かっている場合にエントリを検索します。", openPath: "開く", startEyebrow: "ここから開始", startHeading: "直接プロフィールを持つディストリビューション", startHelp: "ディストリビューションを選択してください。プロフィールには、一覧全体でコマンドを繰り返すことなく、システム確認、正しい形式、次の手順がまとめられています。", catalogCta: "見つかりませんか？カタログを検索", familyEyebrow: "ファミリー別インストール", familyHeading: "パッケージマネージャーを選択", familyHelp: "各ファミリーは参照用ディストリビューションを示します。プロフィールを開いて形式、アーキテクチャ、安全なインストールを確認してください。", catalogEyebrow: "完全なカタログ", catalogHeading: "特定のディストリビューションを検索", catalogHelp: "ディストリビューション、バリアント、ファミリーの名前が分かっているときに検索を使用します。", catalogResultHelp: "検索では履歴上のバリアントと参照を分けます。安全なインストール方針がある場合にのみ、プロフィールでコマンドを確認できます。", profileLink: "プロフィールとインストールを見る", referenceLink: "参照を開く", mappedFamily: (count) => `${count} 件のディストリビューションをマッピング` },
  ko: { guides: "가이드", tools: "도구", openMenu: "탐색 메뉴 열기", menuTitle: "탐색 메뉴", menuDescription: "플랫폼의 영역을 선택하세요.", heroTitle: "Linux에서 길을 찾으세요.", heroDescription: "익숙한 배포판으로 시작하거나 시스템의 패키지 계열을 선택하거나 전체 목록을 검색하세요. 명령은 모든 결과가 아니라 적절한 순간에 배포판 프로필에 표시됩니다.", start: "시작", startDescription: "인기 게임용 배포판과 기술 프로필입니다.", family: "계열별", familyDescription: "수십 개 변형을 비교하지 않고 APT, Pacman, DNF 또는 Zypper를 선택하세요.", catalog: "전체 카탈로그", catalogDescription: "이름을 이미 알고 있을 때 항목을 검색하세요.", openPath: "경로 열기", startEyebrow: "여기서 시작", startHeading: "직접 프로필이 있는 배포판", startHelp: "배포판을 선택하세요. 프로필에는 목록 전체에 명령을 반복하지 않고 시스템 확인, 올바른 형식 및 다음 단계가 모여 있습니다.", catalogCta: "찾지 못했나요? 카탈로그 검색", familyEyebrow: "계열별 설치", familyHeading: "패키지 관리자 선택", familyHelp: "각 계열에는 참조 배포판이 표시됩니다. 프로필을 열어 형식, 아키텍처 및 안전한 설치를 확인하세요.", catalogEyebrow: "전체 카탈로그", catalogHeading: "특정 배포판 검색", catalogHelp: "배포판, 변형 또는 계열 이름을 이미 알고 있을 때 검색을 사용하세요.", catalogResultHelp: "검색은 역사적 변형과 참조를 분리합니다. 안전한 설치 정책이 있는 경우에만 프로필을 열어 명령을 볼 수 있습니다.", profileLink: "프로필 및 설치 보기", referenceLink: "참조 열기", mappedFamily: (count) => `${count}개 배포판 매핑됨` },
  ar: { guides: "الأدلة", tools: "الأدوات", openMenu: "فتح قائمة التنقل", menuTitle: "قائمة التنقل", menuDescription: "اختر قسماً من المنصة.", heroTitle: "اعثر على طريقك في لينكس.", heroDescription: "ابدأ بتوزيعة معروفة، أو اختر عائلة الحزم لنظامك، أو ابحث في القائمة الكاملة. تبقى الأوامر في ملف التوزيعة في الوقت المناسب، لا في كل نتيجة.", start: "ابدأ", startDescription: "توزيعات ألعاب شائعة وملفاتها التقنية.", family: "حسب العائلة", familyDescription: "اختر APT أو Pacman أو DNF أو Zypper دون مقارنة عشرات المتغيرات.", catalog: "الفهرس الكامل", catalogDescription: "ابحث في الإدخالات عندما تعرف الاسم مسبقاً.", openPath: "فتح المسار", startEyebrow: "ابدأ من هنا", startHeading: "توزيعات بملف مباشر", startHelp: "اختر توزيعة. يجمع ملفها فحص النظام والتنسيق الصحيح والخطوات التالية دون تكرار الأوامر في القائمة كاملة.", catalogCta: "لم تجد توزيعتك؟ ابحث في الفهرس", familyEyebrow: "التثبيت حسب العائلة", familyHeading: "اختر مدير الحزم", familyHelp: "تعرض كل عائلة توزيعة مرجعية. افتح ملفها للتحقق من التنسيق والمعمارية والتثبيت الآمن.", catalogEyebrow: "الفهرس الكامل", catalogHeading: "ابحث عن توزيعة محددة", catalogHelp: "استخدم البحث عندما تعرف اسم التوزيعة أو المتغير أو العائلة.", catalogResultHelp: "يفصل البحث بين المتغيرات التاريخية والمراجع؛ افتح ملفاً لرؤية أمر فقط عند وجود سياسة تثبيت آمنة.", profileLink: "عرض الملف والتثبيت", referenceLink: "فتح المرجع", mappedFamily: (count) => `${count} توزيعات معيّنة` },
};
