import type { Locale } from "@/contexts/LanguageContext";

type ProfileCopy = {
  backToAtlas: string;
  eyebrow: string;
  familyPrefix: string;
  profilePurpose: string;
  overview: string;
  family: string;
  format: string;
  policy: string;
  route: string;
  routeIntro: string;
  checkSystem: string;
  selectPackage: string;
  continueSafely: string;
  commands: string;
  commandsIntro: string;
  identifySystem: string;
  installArtifact: (artifact: string) => string;
  updateFamily: string;
  copy: string;
  copied: string;
  safety: string;
  source: string;
  sourceText: string;
  noInstallerTitle: string;
  noInstallerText: string;
  bigLinuxTitle: string;
  bigLinuxText: string;
  bigLinuxLive: string;
  bigLinuxGaming: string;
  bigLinuxDownload: string;
  bigLinuxCommunity: string;
};

export const distroProfileCopy: Record<Locale, ProfileCopy> = {
  "pt-BR": { backToAtlas: "Voltar ao Atlas", eyebrow: "PERFIL DE DISTRIBUIÇÃO", familyPrefix: "Família classificada", profilePurpose: "Um caminho curto para conferir o sistema, escolher o formato publicado e avançar sem misturar instruções de outras distribuições.", overview: "Visão rápida", family: "Família", format: "Formato do app", policy: "Política", route: "Seu caminho seguro", routeIntro: "Siga estas etapas na ordem. Os comandos aparecem só depois que você confirma o contexto.", checkSystem: "Confira sistema e arquitetura", selectPackage: "Use o formato publicado", continueSafely: "Prossiga com contexto", commands: "Instalar o Stray Linux", commandsIntro: "Confira e copie somente o passo que se aplica ao seu sistema.", identifySystem: "1. Identifique a distribuição e a arquitetura", installArtifact: (artifact) => `2. Instale o artefato ${artifact}`, updateFamily: "3. Atualize pelo método da família", copy: "Copiar", copied: "Copiado", safety: "Configuração e limites", source: "Fonte e rastreabilidade", sourceText: "O catálogo preserva a classificação da distribuição e mostra comandos apenas quando há uma política de formato segura. Confirme release, arquitetura e checksum no canal oficial antes de instalar.", noInstallerTitle: "Sem instalador automatizado para esta entrada", noInstallerText: "Esta entrada permanece no catálogo por contexto. Sem uma release suportada e uma política de formato verificável, o Stray Linux não exibe comandos atuais de instalação.", bigLinuxTitle: "BigLinux: perfil atual e verificável", bigLinuxText: "O BigLinux informa derivação dos repositórios Manjaro e mantém canais oficiais de download, comunidade e código aberto. Este perfil usa a rota Pacman apenas para o pacote desktop publicado pelo Stray Linux.", bigLinuxLive: "Teste primeiro no modo Live e confira os dispositivos antes de instalar.", bigLinuxGaming: "O projeto cita Steam e Lutris e oferece opções de Kernel/Mesa; isso não é uma promessa de FPS ou compatibilidade de jogo.", bigLinuxDownload: "Abrir download oficial", bigLinuxCommunity: "Comunidade oficial" },
  en: { backToAtlas: "Back to Atlas", eyebrow: "DISTRIBUTION PROFILE", familyPrefix: "Classified family", profilePurpose: "A short path to check the system, choose the published format, and continue without mixing instructions from other distributions.", overview: "At a glance", family: "Family", format: "App format", policy: "Policy", route: "Your safe path", routeIntro: "Follow these steps in order. Commands appear only after you confirm the context.", checkSystem: "Check system and architecture", selectPackage: "Use the published format", continueSafely: "Continue with context", commands: "Install Stray Linux", commandsIntro: "Review and copy only the step that applies to your system.", identifySystem: "1. Identify the distribution and architecture", installArtifact: (artifact) => `2. Install the ${artifact} artifact`, updateFamily: "3. Update with the family method", copy: "Copy", copied: "Copied", safety: "Configuration and limits", source: "Source and traceability", sourceText: "The catalog preserves the distribution classification and shows commands only when a safe format policy exists. Confirm release, architecture, and checksum through the official channel before installing.", noInstallerTitle: "No automated installer for this entry", noInstallerText: "This entry remains in the catalog for context. Without a supported release and verifiable format policy, Stray Linux does not show current installation commands.", bigLinuxTitle: "BigLinux: current and verifiable profile", bigLinuxText: "BigLinux states that it derives from Manjaro repositories and maintains official download, community, and open-source channels. This profile uses the Pacman route only for the published Stray Linux desktop package.", bigLinuxLive: "Test in Live mode first and check devices before installing.", bigLinuxGaming: "The project mentions Steam and Lutris and offers Kernel/Mesa options; this is not a promise of FPS or game compatibility.", bigLinuxDownload: "Open official download", bigLinuxCommunity: "Official community" },
  es: { backToAtlas: "Volver al Atlas", eyebrow: "PERFIL DE DISTRIBUCIÓN", familyPrefix: "Familia clasificada", profilePurpose: "Un camino corto para comprobar el sistema, elegir el formato publicado y avanzar sin mezclar instrucciones de otras distribuciones.", overview: "Vista rápida", family: "Familia", format: "Formato de la app", policy: "Política", route: "Tu ruta segura", routeIntro: "Sigue estos pasos en orden. Los comandos aparecen solo después de confirmar el contexto.", checkSystem: "Comprueba sistema y arquitectura", selectPackage: "Usa el formato publicado", continueSafely: "Continúa con contexto", commands: "Instalar Stray Linux", commandsIntro: "Revisa y copia solo el paso que se aplica a tu sistema.", identifySystem: "1. Identifica la distribución y la arquitectura", installArtifact: (artifact) => `2. Instala el artefacto ${artifact}`, updateFamily: "3. Actualiza con el método de la familia", copy: "Copiar", copied: "Copiado", safety: "Configuración y límites", source: "Fuente y trazabilidad", sourceText: "El catálogo conserva la clasificación de la distribución y muestra comandos solo cuando existe una política de formato segura. Confirma la versión, arquitectura y suma de verificación en el canal oficial antes de instalar.", noInstallerTitle: "No hay instalador automatizado para esta entrada", noInstallerText: "Esta entrada permanece en el catálogo como contexto. Sin una versión compatible y una política de formato verificable, Stray Linux no muestra comandos de instalación actuales.", bigLinuxTitle: "BigLinux: perfil actual y verificable", bigLinuxText: "BigLinux indica que deriva de los repositorios de Manjaro y mantiene canales oficiales de descarga, comunidad y código abierto. Este perfil usa Pacman solo para el paquete de escritorio publicado por Stray Linux.", bigLinuxLive: "Prueba primero en modo Live y comprueba los dispositivos antes de instalar.", bigLinuxGaming: "El proyecto menciona Steam y Lutris y ofrece opciones de Kernel/Mesa; esto no es una promesa de FPS ni de compatibilidad de juegos.", bigLinuxDownload: "Abrir descarga oficial", bigLinuxCommunity: "Comunidad oficial" },
  fr: { backToAtlas: "Retour à l’Atlas", eyebrow: "PROFIL DE DISTRIBUTION", familyPrefix: "Famille classée", profilePurpose: "Un parcours court pour vérifier le système, choisir le format publié et avancer sans mélanger les instructions d’autres distributions.", overview: "Vue rapide", family: "Famille", format: "Format de l’application", policy: "Politique", route: "Votre parcours sûr", routeIntro: "Suivez ces étapes dans l’ordre. Les commandes apparaissent seulement après confirmation du contexte.", checkSystem: "Vérifiez le système et l’architecture", selectPackage: "Utilisez le format publié", continueSafely: "Continuez avec le contexte", commands: "Installer Stray Linux", commandsIntro: "Vérifiez et copiez uniquement l’étape applicable à votre système.", identifySystem: "1. Identifiez la distribution et l’architecture", installArtifact: (artifact) => `2. Installez l’artefact ${artifact}`, updateFamily: "3. Mettez à jour avec la méthode de la famille", copy: "Copier", copied: "Copié", safety: "Configuration et limites", source: "Source et traçabilité", sourceText: "Le catalogue conserve la classification de la distribution et n’affiche des commandes que lorsqu’une politique de format sûre existe. Vérifiez la version, l’architecture et la somme de contrôle via le canal officiel avant l’installation.", noInstallerTitle: "Aucun installateur automatisé pour cette entrée", noInstallerText: "Cette entrée reste dans le catalogue à titre de contexte. Sans version prise en charge et politique de format vérifiable, Stray Linux n’affiche pas de commandes d’installation actuelles.", bigLinuxTitle: "BigLinux : profil actuel et vérifiable", bigLinuxText: "BigLinux indique dériver des dépôts Manjaro et maintient des canaux officiels de téléchargement, communauté et code source ouvert. Ce profil utilise Pacman uniquement pour le paquet bureau publié par Stray Linux.", bigLinuxLive: "Testez d’abord en mode Live et vérifiez les périphériques avant d’installer.", bigLinuxGaming: "Le projet mentionne Steam et Lutris et propose des options Kernel/Mesa ; cela ne garantit ni FPS ni compatibilité de jeu.", bigLinuxDownload: "Ouvrir le téléchargement officiel", bigLinuxCommunity: "Communauté officielle" },
  de: { backToAtlas: "Zurück zum Atlas", eyebrow: "DISTRIBUTIONSPROFIL", familyPrefix: "Klassifizierte Familie", profilePurpose: "Ein kurzer Weg, das System zu prüfen, das veröffentlichte Format zu wählen und ohne gemischte Anweisungen anderer Distributionen fortzufahren.", overview: "Überblick", family: "Familie", format: "App-Format", policy: "Richtlinie", route: "Ihr sicherer Weg", routeIntro: "Folgen Sie diesen Schritten der Reihe nach. Befehle erscheinen erst, nachdem Sie den Kontext bestätigt haben.", checkSystem: "System und Architektur prüfen", selectPackage: "Veröffentlichtes Format verwenden", continueSafely: "Mit Kontext fortfahren", commands: "Stray Linux installieren", commandsIntro: "Prüfen und kopieren Sie nur den Schritt, der für Ihr System gilt.", identifySystem: "1. Distribution und Architektur bestimmen", installArtifact: (artifact) => `2. ${artifact}-Artefakt installieren`, updateFamily: "3. Mit der Familienmethode aktualisieren", copy: "Kopieren", copied: "Kopiert", safety: "Konfiguration und Grenzen", source: "Quelle und Nachvollziehbarkeit", sourceText: "Der Katalog bewahrt die Klassifizierung der Distribution und zeigt Befehle nur bei einer sicheren Formatrichtlinie. Prüfen Sie Release, Architektur und Prüfsumme vor der Installation über den offiziellen Kanal.", noInstallerTitle: "Kein automatischer Installer für diesen Eintrag", noInstallerText: "Dieser Eintrag bleibt als Kontext im Katalog. Ohne unterstütztes Release und überprüfbare Formatrichtlinie zeigt Stray Linux keine aktuellen Installationsbefehle.", bigLinuxTitle: "BigLinux: aktuelles und überprüfbares Profil", bigLinuxText: "BigLinux gibt an, von Manjaro-Repositories abzustammen, und unterhält offizielle Download-, Community- und Open-Source-Kanäle. Dieses Profil nutzt Pacman nur für das veröffentlichte Stray-Linux-Desktoppaket.", bigLinuxLive: "Testen Sie zuerst im Live-Modus und prüfen Sie die Geräte vor der Installation.", bigLinuxGaming: "Das Projekt erwähnt Steam und Lutris sowie Kernel/Mesa-Optionen; dies ist keine Zusage für FPS oder Spielkompatibilität.", bigLinuxDownload: "Offiziellen Download öffnen", bigLinuxCommunity: "Offizielle Community" },
  it: { backToAtlas: "Torna all’Atlas", eyebrow: "PROFILO DISTRIBUZIONE", familyPrefix: "Famiglia classificata", profilePurpose: "Un percorso breve per controllare il sistema, scegliere il formato pubblicato e procedere senza mescolare istruzioni di altre distribuzioni.", overview: "Panoramica", family: "Famiglia", format: "Formato dell’app", policy: "Politica", route: "Il tuo percorso sicuro", routeIntro: "Segui questi passaggi nell’ordine. I comandi appaiono solo dopo aver confermato il contesto.", checkSystem: "Controlla sistema e architettura", selectPackage: "Usa il formato pubblicato", continueSafely: "Procedi con contesto", commands: "Installa Stray Linux", commandsIntro: "Controlla e copia solo il passaggio applicabile al tuo sistema.", identifySystem: "1. Identifica distribuzione e architettura", installArtifact: (artifact) => `2. Installa l’artefatto ${artifact}`, updateFamily: "3. Aggiorna con il metodo della famiglia", copy: "Copia", copied: "Copiato", safety: "Configurazione e limiti", source: "Fonte e tracciabilità", sourceText: "Il catalogo preserva la classificazione della distribuzione e mostra comandi solo quando esiste una politica di formato sicura. Conferma release, architettura e checksum nel canale ufficiale prima di installare.", noInstallerTitle: "Nessun installatore automatico per questa voce", noInstallerText: "Questa voce rimane nel catalogo come contesto. Senza una release supportata e una politica di formato verificabile, Stray Linux non mostra comandi di installazione attuali.", bigLinuxTitle: "BigLinux: profilo attuale e verificabile", bigLinuxText: "BigLinux dichiara di derivare dai repository Manjaro e mantiene canali ufficiali di download, community e codice aperto. Questo profilo usa Pacman solo per il pacchetto desktop pubblicato da Stray Linux.", bigLinuxLive: "Prova prima in modalità Live e controlla i dispositivi prima di installare.", bigLinuxGaming: "Il progetto cita Steam e Lutris e offre opzioni Kernel/Mesa; questo non promette FPS né compatibilità dei giochi.", bigLinuxDownload: "Apri download ufficiale", bigLinuxCommunity: "Community ufficiale" },
  ru: { backToAtlas: "Назад к Атласу", eyebrow: "ПРОФИЛЬ ДИСТРИБУТИВА", familyPrefix: "Классифицированное семейство", profilePurpose: "Короткий путь для проверки системы, выбора опубликованного формата и продолжения без смешивания инструкций от других дистрибутивов.", overview: "Кратко", family: "Семейство", format: "Формат приложения", policy: "Политика", route: "Безопасный путь", routeIntro: "Выполняйте шаги по порядку. Команды появляются только после подтверждения контекста.", checkSystem: "Проверьте систему и архитектуру", selectPackage: "Используйте опубликованный формат", continueSafely: "Продолжайте с контекстом", commands: "Установить Stray Linux", commandsIntro: "Проверьте и скопируйте только шаг, применимый к вашей системе.", identifySystem: "1. Определите дистрибутив и архитектуру", installArtifact: (artifact) => `2. Установите артефакт ${artifact}`, updateFamily: "3. Обновите методом семейства", copy: "Копировать", copied: "Скопировано", safety: "Настройка и ограничения", source: "Источник и отслеживаемость", sourceText: "Каталог сохраняет классификацию дистрибутива и показывает команды только при наличии безопасной политики формата. Перед установкой проверьте релиз, архитектуру и контрольную сумму в официальном канале.", noInstallerTitle: "Нет автоматического установщика для этой записи", noInstallerText: "Эта запись остается в каталоге для контекста. Без поддерживаемого релиза и проверяемой политики формата Stray Linux не показывает актуальные команды установки.", bigLinuxTitle: "BigLinux: актуальный и проверяемый профиль", bigLinuxText: "BigLinux заявляет, что основан на репозиториях Manjaro, и поддерживает официальные каналы загрузки, сообщества и открытого кода. Этот профиль использует Pacman только для опубликованного настольного пакета Stray Linux.", bigLinuxLive: "Сначала протестируйте режим Live и проверьте устройства перед установкой.", bigLinuxGaming: "Проект упоминает Steam и Lutris и предлагает варианты Kernel/Mesa; это не обещание FPS или совместимости игр.", bigLinuxDownload: "Открыть официальный загрузчик", bigLinuxCommunity: "Официальное сообщество" },
  "zh-CN": { backToAtlas: "返回 Atlas", eyebrow: "发行版资料", familyPrefix: "已分类的软件包家族", profilePurpose: "用简短路径检查系统、选择已发布格式，并避免混用其他发行版的说明。", overview: "快速概览", family: "家族", format: "应用格式", policy: "策略", route: "你的安全路径", routeIntro: "按顺序执行这些步骤。只有确认环境后才会显示命令。", checkSystem: "检查系统与架构", selectPackage: "使用已发布格式", continueSafely: "结合环境继续", commands: "安装 Stray Linux", commandsIntro: "仅检查并复制适用于你系统的步骤。", identifySystem: "1. 识别发行版和架构", installArtifact: (artifact) => `2. 安装 ${artifact} 制品`, updateFamily: "3. 使用家族方法更新", copy: "复制", copied: "已复制", safety: "配置与限制", source: "来源与可追溯性", sourceText: "目录保留发行版分类，并且只在存在安全格式策略时显示命令。安装前请通过官方渠道确认版本、架构和校验和。", noInstallerTitle: "此条目没有自动安装程序", noInstallerText: "此条目作为背景保留在目录中。没有受支持版本和可验证格式策略时，Stray Linux 不显示当前安装命令。", bigLinuxTitle: "BigLinux：当前且可验证的资料", bigLinuxText: "BigLinux 表示它源自 Manjaro 仓库，并维护官方的下载、社区和开源渠道。此资料仅为已发布的 Stray Linux 桌面包使用 Pacman 路径。", bigLinuxLive: "请先在 Live 模式下测试，并在安装前检查设备。", bigLinuxGaming: "项目提及 Steam、Lutris 和 Kernel/Mesa 选项；这不代表 FPS 或游戏兼容性承诺。", bigLinuxDownload: "打开官方下载", bigLinuxCommunity: "官方社区" },
  ja: { backToAtlas: "Atlas に戻る", eyebrow: "ディストリビューションプロフィール", familyPrefix: "分類済みファミリー", profilePurpose: "システムを確認し、公開済み形式を選び、他のディストリビューションの手順を混在させずに進むための短い経路です。", overview: "概要", family: "ファミリー", format: "アプリ形式", policy: "方針", route: "安全な手順", routeIntro: "順番に進めてください。コマンドは環境を確認した後にのみ表示されます。", checkSystem: "システムとアーキテクチャを確認", selectPackage: "公開済み形式を使用", continueSafely: "環境を踏まえて続行", commands: "Stray Linux をインストール", commandsIntro: "自分のシステムに当てはまる手順だけを確認してコピーしてください。", identifySystem: "1. ディストリビューションとアーキテクチャを確認", installArtifact: (artifact) => `2. ${artifact} の成果物をインストール`, updateFamily: "3. ファミリーの方法で更新", copy: "コピー", copied: "コピー済み", safety: "設定と制限", source: "出典と追跡可能性", sourceText: "カタログはディストリビューションの分類を保持し、安全な形式方針がある場合にのみコマンドを表示します。インストール前に公式チャネルでリリース、アーキテクチャ、チェックサムを確認してください。", noInstallerTitle: "この項目には自動インストーラーがありません", noInstallerText: "この項目は文脈のためにカタログに残されています。サポート対象リリースと検証可能な形式方針がなければ、Stray Linux は現在のインストールコマンドを表示しません。", bigLinuxTitle: "BigLinux：現在かつ検証可能なプロフィール", bigLinuxText: "BigLinux は Manjaro リポジトリ由来であると説明し、公式ダウンロード、コミュニティ、オープンソースのチャネルを維持しています。このプロフィールでは公開済み Stray Linux デスクトップパッケージに限り Pacman 経路を使用します。", bigLinuxLive: "まず Live モードで試し、インストール前にデバイスを確認してください。", bigLinuxGaming: "プロジェクトは Steam、Lutris、Kernel/Mesa の選択肢に言及していますが、FPS やゲーム互換性を保証するものではありません。", bigLinuxDownload: "公式ダウンロードを開く", bigLinuxCommunity: "公式コミュニティ" },
  ko: { backToAtlas: "Atlas로 돌아가기", eyebrow: "배포판 프로필", familyPrefix: "분류된 계열", profilePurpose: "시스템을 확인하고 공개된 형식을 선택하며 다른 배포판의 안내를 섞지 않고 진행하는 짧은 경로입니다.", overview: "빠른 개요", family: "계열", format: "앱 형식", policy: "정책", route: "안전한 경로", routeIntro: "이 단계를 순서대로 따르세요. 환경을 확인한 뒤에만 명령이 나타납니다.", checkSystem: "시스템 및 아키텍처 확인", selectPackage: "공개된 형식 사용", continueSafely: "환경을 고려해 계속", commands: "Stray Linux 설치", commandsIntro: "시스템에 적용되는 단계만 확인하고 복사하세요.", identifySystem: "1. 배포판과 아키텍처 확인", installArtifact: (artifact) => `2. ${artifact} 아티팩트 설치`, updateFamily: "3. 계열 방식으로 업데이트", copy: "복사", copied: "복사됨", safety: "구성 및 제한", source: "출처 및 추적성", sourceText: "카탈로그는 배포판 분류를 보존하고 안전한 형식 정책이 있을 때만 명령을 표시합니다. 설치 전에 공식 채널에서 릴리스, 아키텍처 및 체크섬을 확인하세요.", noInstallerTitle: "이 항목에는 자동 설치 프로그램이 없습니다", noInstallerText: "이 항목은 문맥을 위해 카탈로그에 남아 있습니다. 지원되는 릴리스와 검증 가능한 형식 정책이 없으면 Stray Linux는 현재 설치 명령을 표시하지 않습니다.", bigLinuxTitle: "BigLinux: 현재이며 검증 가능한 프로필", bigLinuxText: "BigLinux는 Manjaro 저장소에서 파생되었다고 밝히며 공식 다운로드, 커뮤니티 및 오픈 소스 채널을 유지합니다. 이 프로필은 공개된 Stray Linux 데스크톱 패키지에만 Pacman 경로를 사용합니다.", bigLinuxLive: "먼저 Live 모드에서 테스트하고 설치 전에 장치를 확인하세요.", bigLinuxGaming: "프로젝트는 Steam, Lutris 및 Kernel/Mesa 옵션을 언급하지만 FPS나 게임 호환성을 보장하지 않습니다.", bigLinuxDownload: "공식 다운로드 열기", bigLinuxCommunity: "공식 커뮤니티" },
  ar: { backToAtlas: "العودة إلى الأطلس", eyebrow: "ملف التوزيعة", familyPrefix: "العائلة المصنفة", profilePurpose: "مسار قصير لفحص النظام واختيار التنسيق المنشور والمتابعة دون خلط تعليمات توزيعات أخرى.", overview: "نظرة سريعة", family: "العائلة", format: "تنسيق التطبيق", policy: "السياسة", route: "مسارك الآمن", routeIntro: "اتبع هذه الخطوات بالترتيب. تظهر الأوامر فقط بعد تأكيد السياق.", checkSystem: "تحقق من النظام والبنية", selectPackage: "استخدم التنسيق المنشور", continueSafely: "تابع مع السياق", commands: "تثبيت Stray Linux", commandsIntro: "راجع وانسخ الخطوة التي تنطبق على نظامك فقط.", identifySystem: "1. حدد التوزيعة والبنية", installArtifact: (artifact) => `2. ثبّت حزمة ${artifact}`, updateFamily: "3. حدّث بطريقة العائلة", copy: "نسخ", copied: "تم النسخ", safety: "الإعداد والحدود", source: "المصدر وإمكانية التتبع", sourceText: "يحافظ الفهرس على تصنيف التوزيعة ويعرض الأوامر فقط عند وجود سياسة تنسيق آمنة. تحقق من الإصدار والبنية والمجموع الاختباري عبر القناة الرسمية قبل التثبيت.", noInstallerTitle: "لا يوجد مثبّت تلقائي لهذا الإدخال", noInstallerText: "يبقى هذا الإدخال في الفهرس للسياق. من دون إصدار مدعوم وسياسة تنسيق قابلة للتحقق، لا يعرض Stray Linux أوامر تثبيت حالية.", bigLinuxTitle: "BigLinux: ملف حالي وقابل للتحقق", bigLinuxText: "يذكر BigLinux أنه مشتق من مستودعات Manjaro ويحافظ على قنوات رسمية للتنزيل والمجتمع والمصدر المفتوح. يستخدم هذا الملف مسار Pacman فقط لحزمة سطح مكتب Stray Linux المنشورة.", bigLinuxLive: "اختبر وضع Live أولاً وتحقق من الأجهزة قبل التثبيت.", bigLinuxGaming: "يذكر المشروع Steam وLutris وخيارات Kernel/Mesa؛ وهذا ليس وعداً بمعدل الإطارات أو توافق الألعاب.", bigLinuxDownload: "فتح التنزيل الرسمي", bigLinuxCommunity: "المجتمع الرسمي" },
};
