import type { Locale } from "@/contexts/LanguageContext";

type IntroCopy = {
  skip: string;
  enableSound: string;
  muteSound: string;
  soundHint: string;
  eyebrow: string;
  title: string;
  subtitle: string;
  continue: string;
  keyboardHint: string;
  accessEyebrow: string;
  accessTitle: string;
  accessBody: string;
  localMode: string;
  localModeBody: string;
  localContinue: string;
  signIn: string;
  providerHint: string;
};

export const introCopy: Record<Locale, IntroCopy> = {
  "pt-BR": { skip: "Pular abertura", enableSound: "Ativar som", muteSound: "Silenciar", soundHint: "Trilha ambiente opcional", eyebrow: "STRAY LINUX / INICIALIZANDO", title: "O SEU CAMINHO NO LINUX", subtitle: "Explore, configure e jogue com contexto técnico, fontes claras e decisões que respeitam o seu sistema.", continue: "Entrar na central", keyboardHint: "Pressione Enter para continuar", accessEyebrow: "ACESSO PROTEGIDO", accessTitle: "Entre para abrir sua central.", accessBody: "Seu painel sincroniza perfis, favoritos, guias salvos, histórico de correções e reports. A autenticação usa o provedor seguro já configurado.", localMode: "Modo local detectado", localModeBody: "A versão desktop funciona com SQLite local e não exige banco remoto.", localContinue: "Abrir modo local", signIn: "Continuar com sua conta", providerHint: "Se o provedor conectado oferecer Google, a escolha aparece na próxima etapa segura. Nenhum login paralelo é criado." },
  en: { skip: "Skip opening", enableSound: "Enable sound", muteSound: "Mute", soundHint: "Optional ambient track", eyebrow: "STRAY LINUX / INITIALIZING", title: "YOUR PATH THROUGH LINUX", subtitle: "Explore, configure, and play with technical context, clear sources, and decisions that respect your system.", continue: "Enter the hub", keyboardHint: "Press Enter to continue", accessEyebrow: "PROTECTED ACCESS", accessTitle: "Sign in to open your hub.", accessBody: "Your dashboard syncs profiles, favorites, saved guides, repair history, and reports. Authentication uses the configured secure provider.", localMode: "Local mode detected", localModeBody: "The desktop version works with local SQLite and does not require a remote database.", localContinue: "Open local mode", signIn: "Continue with your account", providerHint: "If the connected provider offers Google, the option appears at the next secure step. No parallel login is created." },
  es: { skip: "Omitir apertura", enableSound: "Activar sonido", muteSound: "Silenciar", soundHint: "Pista ambiental opcional", eyebrow: "STRAY LINUX / INICIANDO", title: "TU CAMINO EN LINUX", subtitle: "Explora, configura y juega con contexto técnico, fuentes claras y decisiones que respetan tu sistema.", continue: "Entrar al centro", keyboardHint: "Pulsa Intro para continuar", accessEyebrow: "ACCESO PROTEGIDO", accessTitle: "Inicia sesión para abrir tu centro.", accessBody: "Tu panel sincroniza perfiles, favoritos, guías guardadas, historial de correcciones e informes. La autenticación usa el proveedor seguro configurado.", localMode: "Modo local detectado", localModeBody: "La versión de escritorio funciona con SQLite local y no requiere una base de datos remota.", localContinue: "Abrir modo local", signIn: "Continuar con tu cuenta", providerHint: "Si el proveedor conectado ofrece Google, la opción aparece en el siguiente paso seguro. No se crea un inicio de sesión paralelo." },
  fr: { skip: "Passer l’ouverture", enableSound: "Activer le son", muteSound: "Couper le son", soundHint: "Piste d’ambiance facultative", eyebrow: "STRAY LINUX / INITIALISATION", title: "VOTRE CHEMIN DANS LINUX", subtitle: "Explorez, configurez et jouez avec un contexte technique, des sources claires et des décisions qui respectent votre système.", continue: "Entrer dans le centre", keyboardHint: "Appuyez sur Entrée pour continuer", accessEyebrow: "ACCÈS PROTÉGÉ", accessTitle: "Connectez-vous pour ouvrir votre centre.", accessBody: "Votre tableau de bord synchronise profils, favoris, guides enregistrés, historique des corrections et rapports. L’authentification utilise le fournisseur sécurisé configuré.", localMode: "Mode local détecté", localModeBody: "La version bureau fonctionne avec SQLite local et ne nécessite pas de base distante.", localContinue: "Ouvrir le mode local", signIn: "Continuer avec votre compte", providerHint: "Si le fournisseur connecté propose Google, le choix apparaît à l’étape sécurisée suivante. Aucune connexion parallèle n’est créée." },
  de: { skip: "Einführung überspringen", enableSound: "Ton aktivieren", muteSound: "Stummschalten", soundHint: "Optionale Ambient-Spur", eyebrow: "STRAY LINUX / INITIALISIERUNG", title: "IHR WEG IN LINUX", subtitle: "Entdecken, konfigurieren und spielen Sie mit technischem Kontext, klaren Quellen und Entscheidungen, die Ihr System berücksichtigen.", continue: "Zentrale öffnen", keyboardHint: "Zum Fortfahren Enter drücken", accessEyebrow: "GESCHÜTZTER ZUGANG", accessTitle: "Melden Sie sich an, um Ihre Zentrale zu öffnen.", accessBody: "Ihr Dashboard synchronisiert Profile, Favoriten, gespeicherte Anleitungen, Korrekturverlauf und Berichte. Die Anmeldung nutzt den eingerichteten sicheren Anbieter.", localMode: "Lokaler Modus erkannt", localModeBody: "Die Desktop-Version arbeitet mit lokalem SQLite und benötigt keine entfernte Datenbank.", localContinue: "Lokalen Modus öffnen", signIn: "Mit Ihrem Konto fortfahren", providerHint: "Wenn der verbundene Anbieter Google anbietet, erscheint die Auswahl im nächsten sicheren Schritt. Es wird keine parallele Anmeldung erstellt." },
  it: { skip: "Salta apertura", enableSound: "Attiva audio", muteSound: "Disattiva audio", soundHint: "Traccia ambiente opzionale", eyebrow: "STRAY LINUX / INIZIALIZZAZIONE", title: "IL TUO PERCORSO IN LINUX", subtitle: "Esplora, configura e gioca con contesto tecnico, fonti chiare e decisioni che rispettano il tuo sistema.", continue: "Entra nel centro", keyboardHint: "Premi Invio per continuare", accessEyebrow: "ACCESSO PROTETTO", accessTitle: "Accedi per aprire il tuo centro.", accessBody: "Il pannello sincronizza profili, preferiti, guide salvate, cronologia delle correzioni e report. L’autenticazione usa il provider sicuro configurato.", localMode: "Modalità locale rilevata", localModeBody: "La versione desktop funziona con SQLite locale e non richiede un database remoto.", localContinue: "Apri modalità locale", signIn: "Continua con il tuo account", providerHint: "Se il provider connesso offre Google, l’opzione appare nel prossimo passaggio sicuro. Non viene creato alcun accesso parallelo." },
  ru: { skip: "Пропустить заставку", enableSound: "Включить звук", muteSound: "Выключить звук", soundHint: "Необязательная фоновая дорожка", eyebrow: "STRAY LINUX / ЗАПУСК", title: "ВАШ ПУТЬ В LINUX", subtitle: "Исследуйте, настраивайте и играйте с техническим контекстом, ясными источниками и решениями, учитывающими вашу систему.", continue: "Открыть центр", keyboardHint: "Нажмите Enter для продолжения", accessEyebrow: "ЗАЩИЩЁННЫЙ ДОСТУП", accessTitle: "Войдите, чтобы открыть свой центр.", accessBody: "Панель синхронизирует профили, избранное, сохранённые руководства, историю исправлений и отчёты. Аутентификация использует настроенного безопасного провайдера.", localMode: "Обнаружен локальный режим", localModeBody: "Версия для ПК работает с локальным SQLite и не требует удалённой базы данных.", localContinue: "Открыть локальный режим", signIn: "Продолжить с аккаунтом", providerHint: "Если подключённый провайдер предлагает Google, выбор появится на следующем безопасном шаге. Параллельный вход не создаётся." },
  "zh-CN": { skip: "跳过开场", enableSound: "开启声音", muteSound: "静音", soundHint: "可选环境音轨", eyebrow: "STRAY LINUX / 正在初始化", title: "你的 LINUX 之路", subtitle: "结合技术环境、清晰来源和尊重系统的决策来探索、配置和游玩。", continue: "进入中心", keyboardHint: "按 Enter 继续", accessEyebrow: "受保护访问", accessTitle: "登录以打开你的中心。", accessBody: "仪表板会同步资料、收藏、已保存指南、修复历史和报告。身份验证使用已配置的安全提供商。", localMode: "检测到本地模式", localModeBody: "桌面版本使用本地 SQLite，无需远程数据库。", localContinue: "打开本地模式", signIn: "使用账户继续", providerHint: "如果已连接的提供商提供 Google，选项会在下一个安全步骤出现。不会创建并行登录。" },
  ja: { skip: "オープニングをスキップ", enableSound: "サウンドを有効化", muteSound: "ミュート", soundHint: "任意の環境音トラック", eyebrow: "STRAY LINUX / 初期化中", title: "あなたの LINUX への道", subtitle: "技術的な文脈、明確な情報源、システムを尊重する判断とともに探索、設定、プレイします。", continue: "センターに入る", keyboardHint: "Enter を押して続行", accessEyebrow: "保護されたアクセス", accessTitle: "センターを開くにはログインしてください。", accessBody: "ダッシュボードはプロフィール、お気に入り、保存済みガイド、修正履歴、レポートを同期します。認証には設定済みの安全なプロバイダーを使用します。", localMode: "ローカルモードを検出", localModeBody: "デスクトップ版はローカル SQLite で動作し、リモートデータベースは必要ありません。", localContinue: "ローカルモードを開く", signIn: "アカウントで続行", providerHint: "接続済みプロバイダーが Google を提供する場合、次の安全なステップで選択肢が表示されます。並行ログインは作成されません。" },
  ko: { skip: "오프닝 건너뛰기", enableSound: "사운드 켜기", muteSound: "음소거", soundHint: "선택적 앰비언트 트랙", eyebrow: "STRAY LINUX / 초기화 중", title: "나의 LINUX 경로", subtitle: "기술적 맥락, 명확한 출처, 시스템을 존중하는 선택으로 탐색하고 구성하고 플레이하세요.", continue: "센터로 들어가기", keyboardHint: "Enter를 눌러 계속", accessEyebrow: "보호된 접근", accessTitle: "센터를 열려면 로그인하세요.", accessBody: "대시보드는 프로필, 즐겨찾기, 저장된 가이드, 수정 기록 및 보고서를 동기화합니다. 인증은 구성된 보안 제공자를 사용합니다.", localMode: "로컬 모드 감지", localModeBody: "데스크톱 버전은 로컬 SQLite로 작동하며 원격 데이터베이스가 필요하지 않습니다.", localContinue: "로컬 모드 열기", signIn: "계정으로 계속", providerHint: "연결된 제공자가 Google을 제공하면 다음 보안 단계에서 선택지가 표시됩니다. 별도 로그인이 생성되지 않습니다." },
  ar: { skip: "تخطي الافتتاحية", enableSound: "تفعيل الصوت", muteSound: "كتم الصوت", soundHint: "مسار أجواء اختياري", eyebrow: "STRAY LINUX / تهيئة", title: "طريقك في LINUX", subtitle: "استكشف واضبط والعب بسياق تقني ومصادر واضحة وقرارات تحترم نظامك.", continue: "دخول المركز", keyboardHint: "اضغط Enter للمتابعة", accessEyebrow: "وصول محمي", accessTitle: "سجّل الدخول لفتح مركزك.", accessBody: "تزامن لوحة التحكم الملفات الشخصية والمفضلة والأدلة المحفوظة وسجل الإصلاحات والتقارير. تستخدم المصادقة الموفر الآمن المُعَدّ.", localMode: "تم اكتشاف الوضع المحلي", localModeBody: "تعمل نسخة سطح المكتب مع SQLite محلي ولا تتطلب قاعدة بيانات بعيدة.", localContinue: "فتح الوضع المحلي", signIn: "المتابعة بالحساب", providerHint: "إذا كان الموفر المتصل يقدم Google، يظهر الاختيار في الخطوة الآمنة التالية. لا يتم إنشاء تسجيل دخول موازٍ." },
};
