import type { Locale } from "@/contexts/LanguageContext";

type StepKind = "inspect" | "change" | "verify" | "recover";

type LinuxFixStepMetadata = {
  prerequisite: string;
  byKind: Record<StepKind, string>;
  noRollback: string;
};

export const linuxFixStepMetadata: Record<Locale, LinuxFixStepMetadata> = {
  "pt-BR": { prerequisite: "Pré-requisito", byKind: { inspect: "Confirme o sintoma e leia o resultado antes de avançar.", change: "Confirme distribuição, versão e escopo do comando na fonte antes de alterar o sistema.", verify: "Aplique somente a etapa anterior que foi revisada e registre o resultado observado.", recover: "Mantenha a alteração anterior identificável; não recupere arquivos ou configurações sem uma cópia revisável." }, noRollback: "Nenhuma reversão foi registrada para esta etapa; não a trate como reversível." },
  en: { prerequisite: "Prerequisite", byKind: { inspect: "Confirm the symptom and read the result before proceeding.", change: "Confirm the distribution, version and command scope in the source before changing the system.", verify: "Apply only the prior step that was reviewed and record the observed result.", recover: "Keep the prior change identifiable; do not restore files or configuration without a reviewable copy." }, noRollback: "No rollback was recorded for this step; do not treat it as reversible." },
  es: { prerequisite: "Requisito previo", byKind: { inspect: "Confirma el síntoma y lee el resultado antes de continuar.", change: "Confirma la distribución, la versión y el alcance del comando en la fuente antes de cambiar el sistema.", verify: "Aplica solo el paso anterior que fue revisado y registra el resultado observado.", recover: "Mantén identificable el cambio anterior; no restaures archivos ni configuración sin una copia revisable." }, noRollback: "No se registró reversión para este paso; no lo trates como reversible." },
  fr: { prerequisite: "Prérequis", byKind: { inspect: "Confirmez le symptôme et lisez le résultat avant de poursuivre.", change: "Confirmez la distribution, la version et le périmètre de la commande dans la source avant de modifier le système.", verify: "Appliquez uniquement l’étape précédente qui a été vérifiée et consignez le résultat observé.", recover: "Gardez la modification précédente identifiable ; ne restaurez pas de fichiers ou de configuration sans copie vérifiable." }, noRollback: "Aucune annulation n’est enregistrée pour cette étape ; ne la considérez pas comme réversible." },
  de: { prerequisite: "Voraussetzung", byKind: { inspect: "Bestätigen Sie das Symptom und lesen Sie das Ergebnis, bevor Sie fortfahren.", change: "Bestätigen Sie Distribution, Version und Befehlsumfang in der Quelle, bevor Sie das System ändern.", verify: "Wenden Sie nur den zuvor geprüften Schritt an und dokumentieren Sie das beobachtete Ergebnis.", recover: "Halten Sie die vorherige Änderung nachvollziehbar; stellen Sie keine Dateien oder Konfiguration ohne prüfbare Kopie wieder her." }, noRollback: "Für diesen Schritt ist kein Rollback dokumentiert; behandeln Sie ihn nicht als umkehrbar." },
  it: { prerequisite: "Prerequisito", byKind: { inspect: "Conferma il sintomo e leggi il risultato prima di procedere.", change: "Conferma distribuzione, versione e ambito del comando nella fonte prima di modificare il sistema.", verify: "Applica solo il passaggio precedente che è stato verificato e registra il risultato osservato.", recover: "Mantieni identificabile la modifica precedente; non ripristinare file o configurazione senza una copia verificabile." }, noRollback: "Non è registrato alcun ripristino per questo passaggio; non trattarlo come reversibile." },
  ru: { prerequisite: "Предварительное условие", byKind: { inspect: "Подтвердите симптом и прочитайте результат перед продолжением.", change: "Подтвердите дистрибутив, версию и область действия команды в источнике перед изменением системы.", verify: "Применяйте только проверенный предыдущий шаг и зафиксируйте наблюдаемый результат.", recover: "Сохраняйте возможность идентифицировать предыдущее изменение; не восстанавливайте файлы или настройки без проверяемой копии." }, noRollback: "Для этого шага не записан откат; не считайте его обратимым." },
  "zh-CN": { prerequisite: "前提条件", byKind: { inspect: "确认症状并阅读结果后再继续。", change: "更改系统前，请在来源中确认发行版、版本和命令范围。", verify: "仅应用已审核的前一步，并记录观察到的结果。", recover: "保持之前更改可识别；没有可审查的副本时，请勿恢复文件或配置。" }, noRollback: "此步骤未记录回退方式；请勿将其视为可逆。" },
  ja: { prerequisite: "前提条件", byKind: { inspect: "症状を確認し、結果を読んでから続行してください。", change: "システムを変更する前に、ソースでディストリビューション、バージョン、コマンドの対象範囲を確認してください。", verify: "確認済みの前の手順だけを適用し、観測結果を記録してください。", recover: "前の変更を識別できる状態に保ち、確認可能なコピーなしにファイルや設定を復元しないでください。" }, noRollback: "この手順にはロールバックが記録されていません。可逆的とは扱わないでください。" },
  ko: { prerequisite: "선행 조건", byKind: { inspect: "증상을 확인하고 결과를 읽은 후 진행하세요.", change: "시스템을 변경하기 전에 출처에서 배포판, 버전 및 명령 범위를 확인하세요.", verify: "검토된 이전 단계만 적용하고 관찰된 결과를 기록하세요.", recover: "이전 변경 사항을 식별할 수 있게 유지하고 검토 가능한 사본 없이 파일이나 구성을 복원하지 마세요." }, noRollback: "이 단계에는 되돌리기가 기록되지 않았습니다. 되돌릴 수 있는 것으로 간주하지 마세요." },
  ar: { prerequisite: "متطلب سابق", byKind: { inspect: "أكد العَرَض واقرأ النتيجة قبل المتابعة.", change: "أكد التوزيعة والإصدار ونطاق الأمر في المصدر قبل تغيير النظام.", verify: "طبّق فقط الخطوة السابقة التي تمت مراجعتها وسجّل النتيجة المرصودة.", recover: "أبقِ التغيير السابق قابلاً للتحديد؛ لا تستعد الملفات أو الإعدادات دون نسخة قابلة للمراجعة." }, noRollback: "لا توجد طريقة تراجع مسجلة لهذه الخطوة؛ لا تعاملها على أنها قابلة للعكس." },
};
