import type { Locale } from "@/contexts/LanguageContext";

export type LinuxFixCopy = {
  catalogEyebrow: string;
  catalogTitle: string;
  catalogDescription: string;
  searchPlaceholder: string;
  allCategories: string;
  sourceRule: string;
  noResultsTitle: string;
  noResultsDescription: string;
  openRunbook: string;
  confidence: string;
  detailsEyebrow: string;
  detailsDescription: string;
  contextTitle: string;
  contextReady: string;
  contextEmpty: string;
  configureProfile: string;
  diagnosis: string;
  symptoms: string;
  likelyCause: string;
  runbook: string;
  beforeYouStart: string;
  changeOneThing: string;
  step: string;
  verify: string;
  rollback: string;
  evidence: string;
  source: string;
  noSource: string;
  feedbackTitle: string;
  feedbackDescription: string;
  noCommunityData: string;
  reportTitle: string;
  reportDescription: string;
  reportButton: string;
  kind: Record<"inspect" | "change" | "verify" | "recover", string>;
  risk: Record<"read_only" | "reversible" | "system_change", string>;
};

export const linuxFixCopy: Record<Locale, LinuxFixCopy> = {
  "pt-BR": {
    catalogEyebrow: "LINUXFIX / RUNBOOKS", catalogTitle: "Encontre a hipótese antes de alterar o sistema.", catalogDescription: "Cada runbook separa inspeção, alteração, verificação, reversão e fonte. Dados ausentes continuam explícitos.", searchPlaceholder: "Pesquisar Steam, Proton, stuttering, tela preta…", allCategories: "Todas as categorias", sourceRule: "Somente procedimentos com origem registrada aparecem aqui.", noResultsTitle: "Nenhum runbook publicado", noResultsDescription: "O problema ainda não tem um procedimento com fonte suficiente. Você pode reportar a lacuna após entrar.", openRunbook: "Abrir runbook", confidence: "Confiança", detailsEyebrow: "LINUXFIX / DIAGNÓSTICO", detailsDescription: "Execute uma variável por vez. A confirmação de usuários não substitui a evidência técnica da fonte.", contextTitle: "Contexto técnico", contextReady: "Perfil ativo disponível para orientar a leitura. Nenhum dado local é enviado por abrir este runbook.", contextEmpty: "Não há perfil ativo. Configure ou importe um scan local para comparar distro, kernel, driver e Proton.", configureProfile: "Configurar Meu PC", diagnosis: "Mapa do diagnóstico", symptoms: "Sintomas observados", likelyCause: "Hipótese principal", runbook: "Procedimento técnico", beforeYouStart: "Antes de começar", changeOneThing: "Altere uma variável por vez; registre o resultado antes de seguir.", step: "Etapa", verify: "Como verificar", rollback: "Como reverter", evidence: "Evidência e escopo", source: "Abrir fonte", noSource: "Nenhuma fonte adicional registrada para esta etapa.", feedbackTitle: "Relatos de ambiente", feedbackDescription: "Votos, confirmações e comentários descrevem experiências de usuários; eles não promovem uma correção a verificada.", noCommunityData: "Ainda não há relatos publicados. Seja o primeiro a registrar o resultado do seu ambiente, sem incluir dados sensíveis.", reportTitle: "Revisão editorial", reportDescription: "Reporte uma instrução desatualizada, uma fonte quebrada ou um risco não documentado. A decisão fica registrada para moderação.", reportButton: "Reportar problema", kind: { inspect: "INSPECIONAR", change: "ALTERAR", verify: "VERIFICAR", recover: "RECUPERAR" }, risk: { read_only: "SOMENTE LEITURA", reversible: "REVERSÍVEL", system_change: "ALTERAÇÃO DE SISTEMA" },
  },
  en: {
    catalogEyebrow: "LINUXFIX / RUNBOOKS", catalogTitle: "Find the hypothesis before changing the system.", catalogDescription: "Each runbook separates inspection, change, verification, rollback and source. Missing data stays explicit.", searchPlaceholder: "Search Steam, Proton, stuttering, black screen…", allCategories: "All categories", sourceRule: "Only procedures with a recorded source appear here.", noResultsTitle: "No published runbook", noResultsDescription: "This issue does not yet have a sufficiently sourced procedure. You can report the gap after signing in.", openRunbook: "Open runbook", confidence: "Confidence", detailsEyebrow: "LINUXFIX / DIAGNOSIS", detailsDescription: "Test one variable at a time. User confirmations do not replace source-backed technical evidence.", contextTitle: "Technical context", contextReady: "An active profile is available to guide this reading. Opening this runbook sends no local data.", contextEmpty: "No active profile. Configure or import a local scan to compare distro, kernel, driver and Proton.", configureProfile: "Configure My PC", diagnosis: "Diagnostic map", symptoms: "Observed symptoms", likelyCause: "Primary hypothesis", runbook: "Technical procedure", beforeYouStart: "Before you start", changeOneThing: "Change one variable at a time; record the outcome before continuing.", step: "Step", verify: "How to verify", rollback: "How to roll back", evidence: "Evidence and scope", source: "Open source", noSource: "No additional source recorded for this step.", feedbackTitle: "Environment reports", feedbackDescription: "Votes, confirmations and comments describe user experiences; they do not promote a fix to verified.", noCommunityData: "There are no published reports yet. Be the first to record your environment result without including sensitive data.", reportTitle: "Editorial review", reportDescription: "Report an outdated instruction, broken source or undocumented risk. The decision is retained for moderation.", reportButton: "Report an issue", kind: { inspect: "INSPECT", change: "CHANGE", verify: "VERIFY", recover: "RECOVER" }, risk: { read_only: "READ ONLY", reversible: "REVERSIBLE", system_change: "SYSTEM CHANGE" },
  },
  es: {
    catalogEyebrow: "LINUXFIX / RUNBOOKS", catalogTitle: "Encuentra la hipótesis antes de cambiar el sistema.", catalogDescription: "Cada runbook separa inspección, cambio, verificación, reversión y fuente. Los datos ausentes siguen explícitos.", searchPlaceholder: "Buscar Steam, Proton, stuttering, pantalla negra…", allCategories: "Todas las categorías", sourceRule: "Aquí solo aparecen procedimientos con fuente registrada.", noResultsTitle: "No hay runbook publicado", noResultsDescription: "El problema todavía no tiene un procedimiento con fuente suficiente. Puedes reportar la ausencia al iniciar sesión.", openRunbook: "Abrir runbook", confidence: "Confianza", detailsEyebrow: "LINUXFIX / DIAGNÓSTICO", detailsDescription: "Prueba una variable cada vez. Las confirmaciones de usuarios no reemplazan evidencia técnica de la fuente.", contextTitle: "Contexto técnico", contextReady: "Hay un perfil activo para orientar la lectura. Abrir este runbook no envía datos locales.", contextEmpty: "No hay perfil activo. Configura o importa un escaneo local para comparar distro, kernel, driver y Proton.", configureProfile: "Configurar Mi PC", diagnosis: "Mapa de diagnóstico", symptoms: "Síntomas observados", likelyCause: "Hipótesis principal", runbook: "Procedimiento técnico", beforeYouStart: "Antes de empezar", changeOneThing: "Cambia una variable a la vez; registra el resultado antes de continuar.", step: "Paso", verify: "Cómo verificar", rollback: "Cómo revertir", evidence: "Evidencia y alcance", source: "Abrir fuente", noSource: "No hay fuente adicional registrada para este paso.", feedbackTitle: "Informes de entorno", feedbackDescription: "Los votos, confirmaciones y comentarios describen experiencias; no elevan una corrección a verificada.", noCommunityData: "Todavía no hay informes publicados. Sé el primero en registrar el resultado de tu entorno sin datos sensibles.", reportTitle: "Revisión editorial", reportDescription: "Reporta una instrucción desactualizada, fuente rota o riesgo no documentado. La decisión queda registrada para moderación.", reportButton: "Reportar problema", kind: { inspect: "INSPECCIONAR", change: "CAMBIAR", verify: "VERIFICAR", recover: "RECUPERAR" }, risk: { read_only: "SOLO LECTURA", reversible: "REVERSIBLE", system_change: "CAMBIO DEL SISTEMA" },
  },
  fr: {
    catalogEyebrow: "LINUXFIX / RUNBOOKS", catalogTitle: "Trouvez l’hypothèse avant de modifier le système.", catalogDescription: "Chaque runbook sépare inspection, modification, vérification, annulation et source. Les données absentes restent explicites.", searchPlaceholder: "Rechercher Steam, Proton, stuttering, écran noir…", allCategories: "Toutes les catégories", sourceRule: "Seules les procédures avec une source enregistrée apparaissent ici.", noResultsTitle: "Aucun runbook publié", noResultsDescription: "Ce problème ne dispose pas encore d’une procédure suffisamment sourcée. Vous pouvez signaler ce manque après connexion.", openRunbook: "Ouvrir le runbook", confidence: "Confiance", detailsEyebrow: "LINUXFIX / DIAGNOSTIC", detailsDescription: "Testez une variable à la fois. Les confirmations d’utilisateurs ne remplacent pas l’évidence technique de la source.", contextTitle: "Contexte technique", contextReady: "Un profil actif guide cette lecture. Ouvrir ce runbook n’envoie aucune donnée locale.", contextEmpty: "Aucun profil actif. Configurez ou importez une analyse locale pour comparer distribution, noyau, pilote et Proton.", configureProfile: "Configurer Mon PC", diagnosis: "Carte du diagnostic", symptoms: "Symptômes observés", likelyCause: "Hypothèse principale", runbook: "Procédure technique", beforeYouStart: "Avant de commencer", changeOneThing: "Modifiez une variable à la fois ; notez le résultat avant de continuer.", step: "Étape", verify: "Comment vérifier", rollback: "Comment annuler", evidence: "Preuves et périmètre", source: "Ouvrir la source", noSource: "Aucune source supplémentaire n’est enregistrée pour cette étape.", feedbackTitle: "Rapports d’environnement", feedbackDescription: "Votes, confirmations et commentaires décrivent des expériences ; ils ne rendent pas un correctif vérifié.", noCommunityData: "Aucun rapport n’est encore publié. Soyez le premier à consigner le résultat de votre environnement sans données sensibles.", reportTitle: "Révision éditoriale", reportDescription: "Signalez une instruction obsolète, une source cassée ou un risque non documenté. La décision reste tracée pour modération.", reportButton: "Signaler un problème", kind: { inspect: "INSPECTER", change: "MODIFIER", verify: "VÉRIFIER", recover: "RÉCUPÉRER" }, risk: { read_only: "LECTURE SEULE", reversible: "RÉVERSIBLE", system_change: "MODIFICATION SYSTÈME" },
  },
  de: {
    catalogEyebrow: "LINUXFIX / RUNBOOKS", catalogTitle: "Finden Sie die Hypothese, bevor Sie das System ändern.", catalogDescription: "Jedes Runbook trennt Prüfung, Änderung, Verifizierung, Rücknahme und Quelle. Fehlende Daten bleiben sichtbar.", searchPlaceholder: "Steam, Proton, Stuttering, schwarzer Bildschirm suchen…", allCategories: "Alle Kategorien", sourceRule: "Hier erscheinen nur Verfahren mit dokumentierter Quelle.", noResultsTitle: "Kein veröffentlichtes Runbook", noResultsDescription: "Für dieses Problem gibt es noch kein ausreichend belegtes Verfahren. Nach der Anmeldung können Sie die Lücke melden.", openRunbook: "Runbook öffnen", confidence: "Vertrauen", detailsEyebrow: "LINUXFIX / DIAGNOSE", detailsDescription: "Testen Sie jeweils nur eine Variable. Nutzerbestätigungen ersetzen keine technische Evidenz aus der Quelle.", contextTitle: "Technischer Kontext", contextReady: "Ein aktives Profil unterstützt die Einordnung. Das Öffnen dieses Runbooks sendet keine lokalen Daten.", contextEmpty: "Kein aktives Profil. Konfigurieren oder importieren Sie einen lokalen Scan, um Distro, Kernel, Treiber und Proton zu vergleichen.", configureProfile: "Mein PC konfigurieren", diagnosis: "Diagnosekarte", symptoms: "Beobachtete Symptome", likelyCause: "Haupthypothese", runbook: "Technisches Verfahren", beforeYouStart: "Vor dem Start", changeOneThing: "Ändern Sie nur eine Variable und dokumentieren Sie das Ergebnis vor dem nächsten Schritt.", step: "Schritt", verify: "So prüfen Sie", rollback: "So setzen Sie zurück", evidence: "Evidenz und Umfang", source: "Quelle öffnen", noSource: "Für diesen Schritt ist keine zusätzliche Quelle dokumentiert.", feedbackTitle: "Umgebungsberichte", feedbackDescription: "Bewertungen, Bestätigungen und Kommentare beschreiben Erfahrungen; sie machen eine Korrektur nicht verifiziert.", noCommunityData: "Noch sind keine Berichte veröffentlicht. Dokumentieren Sie als Erste:r das Ergebnis Ihrer Umgebung ohne sensible Daten.", reportTitle: "Redaktionelle Prüfung", reportDescription: "Melden Sie eine veraltete Anweisung, defekte Quelle oder nicht dokumentiertes Risiko. Die Entscheidung wird für die Moderation protokolliert.", reportButton: "Problem melden", kind: { inspect: "PRÜFEN", change: "ÄNDERN", verify: "VERIFIZIEREN", recover: "WIEDERHERSTELLEN" }, risk: { read_only: "NUR LESEN", reversible: "UMKEHRBAR", system_change: "SYSTEMÄNDERUNG" },
  },
  it: {
    catalogEyebrow: "LINUXFIX / RUNBOOK", catalogTitle: "Trova l’ipotesi prima di modificare il sistema.", catalogDescription: "Ogni runbook separa ispezione, modifica, verifica, ripristino e fonte. I dati mancanti restano espliciti.", searchPlaceholder: "Cerca Steam, Proton, stuttering, schermo nero…", allCategories: "Tutte le categorie", sourceRule: "Qui compaiono solo procedure con una fonte registrata.", noResultsTitle: "Nessun runbook pubblicato", noResultsDescription: "Il problema non ha ancora una procedura con fonti sufficienti. Puoi segnalare la lacuna dopo l’accesso.", openRunbook: "Apri runbook", confidence: "Confidenza", detailsEyebrow: "LINUXFIX / DIAGNOSI", detailsDescription: "Prova una variabile alla volta. Le conferme degli utenti non sostituiscono l’evidenza tecnica della fonte.", contextTitle: "Contesto tecnico", contextReady: "Un profilo attivo aiuta la lettura. Aprire questo runbook non invia dati locali.", contextEmpty: "Nessun profilo attivo. Configura o importa una scansione locale per confrontare distro, kernel, driver e Proton.", configureProfile: "Configura il mio PC", diagnosis: "Mappa diagnostica", symptoms: "Sintomi osservati", likelyCause: "Ipotesi principale", runbook: "Procedura tecnica", beforeYouStart: "Prima di iniziare", changeOneThing: "Modifica una variabile alla volta; registra il risultato prima di continuare.", step: "Passo", verify: "Come verificare", rollback: "Come ripristinare", evidence: "Evidenza e ambito", source: "Apri fonte", noSource: "Nessuna fonte aggiuntiva registrata per questo passo.", feedbackTitle: "Report dell’ambiente", feedbackDescription: "Voti, conferme e commenti descrivono esperienze; non rendono una correzione verificata.", noCommunityData: "Non ci sono ancora report pubblicati. Registra per primo il risultato del tuo ambiente senza dati sensibili.", reportTitle: "Revisione editoriale", reportDescription: "Segnala un’istruzione obsoleta, una fonte non disponibile o un rischio non documentato. La decisione resta tracciata per la moderazione.", reportButton: "Segnala problema", kind: { inspect: "ISPEZIONA", change: "MODIFICA", verify: "VERIFICA", recover: "RIPRISTINA" }, risk: { read_only: "SOLA LETTURA", reversible: "REVERSIBILE", system_change: "MODIFICA SISTEMA" },
  },
  ru: {
    catalogEyebrow: "LINUXFIX / РУКОВОДСТВА", catalogTitle: "Найдите гипотезу до изменения системы.", catalogDescription: "Каждое руководство разделяет проверку, изменение, подтверждение, откат и источник. Отсутствующие данные остаются явными.", searchPlaceholder: "Искать Steam, Proton, статтеры, чёрный экран…", allCategories: "Все категории", sourceRule: "Здесь показаны только процедуры с зарегистрированным источником.", noResultsTitle: "Нет опубликованного руководства", noResultsDescription: "Для этой проблемы пока нет достаточно подтверждённой процедуры. После входа можно сообщить о пробеле.", openRunbook: "Открыть руководство", confidence: "Уверенность", detailsEyebrow: "LINUXFIX / ДИАГНОСТИКА", detailsDescription: "Проверяйте по одной переменной. Подтверждения пользователей не заменяют технические доказательства источника.", contextTitle: "Технический контекст", contextReady: "Активный профиль помогает чтению. Открытие руководства не отправляет локальные данные.", contextEmpty: "Нет активного профиля. Настройте или импортируйте локальное сканирование для сравнения дистрибутива, ядра, драйвера и Proton.", configureProfile: "Настроить мой ПК", diagnosis: "Карта диагностики", symptoms: "Наблюдаемые симптомы", likelyCause: "Основная гипотеза", runbook: "Техническая процедура", beforeYouStart: "Перед началом", changeOneThing: "Меняйте только одну переменную и фиксируйте результат перед продолжением.", step: "Шаг", verify: "Как проверить", rollback: "Как откатить", evidence: "Доказательства и область", source: "Открыть источник", noSource: "Для этого шага нет дополнительного источника.", feedbackTitle: "Отчёты среды", feedbackDescription: "Голоса, подтверждения и комментарии описывают опыт; они не делают исправление проверенным.", noCommunityData: "Опубликованных отчётов ещё нет. Первым зафиксируйте результат среды без чувствительных данных.", reportTitle: "Редакционная проверка", reportDescription: "Сообщите об устаревшей инструкции, неработающем источнике или недокументированном риске. Решение сохраняется для модерации.", reportButton: "Сообщить о проблеме", kind: { inspect: "ПРОВЕРИТЬ", change: "ИЗМЕНИТЬ", verify: "ПОДТВЕРДИТЬ", recover: "ВОССТАНОВИТЬ" }, risk: { read_only: "ТОЛЬКО ЧТЕНИЕ", reversible: "ОБРАТИМО", system_change: "ИЗМЕНЕНИЕ СИСТЕМЫ" },
  },
  "zh-CN": {
    catalogEyebrow: "LINUXFIX / 操作手册", catalogTitle: "先找到假设，再修改系统。", catalogDescription: "每份操作手册区分检查、修改、验证、回滚和来源。缺失数据会明确显示。", searchPlaceholder: "搜索 Steam、Proton、卡顿、黑屏…", allCategories: "所有类别", sourceRule: "这里只显示已记录来源的流程。", noResultsTitle: "没有已发布的操作手册", noResultsDescription: "该问题尚无来源充分的流程。登录后可报告此缺口。", openRunbook: "打开操作手册", confidence: "置信度", detailsEyebrow: "LINUXFIX / 诊断", detailsDescription: "一次只测试一个变量。用户确认不能替代来源支持的技术证据。", contextTitle: "技术上下文", contextReady: "活动配置可帮助阅读此流程。打开操作手册不会发送本地数据。", contextEmpty: "没有活动配置。请配置或导入本地扫描，以比较发行版、内核、驱动和 Proton。", configureProfile: "配置我的电脑", diagnosis: "诊断图", symptoms: "观察到的症状", likelyCause: "主要假设", runbook: "技术流程", beforeYouStart: "开始前", changeOneThing: "一次只改一个变量；继续前记录结果。", step: "步骤", verify: "如何验证", rollback: "如何回滚", evidence: "证据与范围", source: "打开来源", noSource: "此步骤没有额外记录来源。", feedbackTitle: "环境报告", feedbackDescription: "投票、确认和评论描述用户体验；它们不会使修复变为已验证。", noCommunityData: "尚无已发布报告。请在不包含敏感数据的情况下率先记录环境结果。", reportTitle: "编辑审核", reportDescription: "报告过时说明、失效来源或未记录风险。决定将保留供审核。", reportButton: "报告问题", kind: { inspect: "检查", change: "修改", verify: "验证", recover: "恢复" }, risk: { read_only: "只读", reversible: "可逆", system_change: "系统修改" },
  },
  ja: {
    catalogEyebrow: "LINUXFIX / ランブック", catalogTitle: "システムを変更する前に仮説を見つけます。", catalogDescription: "各ランブックは確認、変更、検証、復元、ソースを分けます。不足データは明示したままです。", searchPlaceholder: "Steam、Proton、スタッター、黒画面を検索…", allCategories: "すべてのカテゴリ", sourceRule: "記録済みのソースを持つ手順のみを表示します。", noResultsTitle: "公開済みランブックがありません", noResultsDescription: "この問題には十分なソースを持つ手順がまだありません。ログイン後に不足を報告できます。", openRunbook: "ランブックを開く", confidence: "信頼度", detailsEyebrow: "LINUXFIX / 診断", detailsDescription: "一度に一つの変数を試してください。ユーザー確認はソースに基づく技術的根拠を置き換えません。", contextTitle: "技術コンテキスト", contextReady: "有効なプロファイルがこの手順の確認に役立ちます。開いてもローカルデータは送信されません。", contextEmpty: "有効なプロファイルがありません。ディストリビューション、カーネル、ドライバー、Proton を比較するためにローカルスキャンを設定またはインポートしてください。", configureProfile: "マイPCを設定", diagnosis: "診断マップ", symptoms: "確認された症状", likelyCause: "主な仮説", runbook: "技術手順", beforeYouStart: "開始前", changeOneThing: "一度に一つの変数だけを変更し、続行前に結果を記録してください。", step: "手順", verify: "確認方法", rollback: "元に戻す方法", evidence: "根拠と対象範囲", source: "ソースを開く", noSource: "この手順には追加ソースが登録されていません。", feedbackTitle: "環境レポート", feedbackDescription: "投票、確認、コメントはユーザー体験を記述するもので、修正を検証済みにしません。", noCommunityData: "公開済みレポートはまだありません。機密データを含めずに環境の結果を最初に記録してください。", reportTitle: "編集レビュー", reportDescription: "古い手順、壊れたソース、文書化されていないリスクを報告してください。判断はモデレーション用に残ります。", reportButton: "問題を報告", kind: { inspect: "確認", change: "変更", verify: "検証", recover: "復元" }, risk: { read_only: "読み取り専用", reversible: "元に戻せる", system_change: "システム変更" },
  },
  ko: {
    catalogEyebrow: "LINUXFIX / 런북", catalogTitle: "시스템을 바꾸기 전에 가설을 찾으세요.", catalogDescription: "각 런북은 점검, 변경, 검증, 복구 및 출처를 구분합니다. 누락된 데이터는 명시적으로 남습니다.", searchPlaceholder: "Steam, Proton, 끊김, 검은 화면 검색…", allCategories: "모든 분류", sourceRule: "기록된 출처가 있는 절차만 여기에 표시됩니다.", noResultsTitle: "게시된 런북이 없습니다", noResultsDescription: "이 문제에는 아직 출처가 충분한 절차가 없습니다. 로그인 후 공백을 신고할 수 있습니다.", openRunbook: "런북 열기", confidence: "신뢰도", detailsEyebrow: "LINUXFIX / 진단", detailsDescription: "한 번에 하나의 변수만 시험하세요. 사용자 확인은 출처 기반 기술 증거를 대체하지 않습니다.", contextTitle: "기술 컨텍스트", contextReady: "활성 프로필이 이 절차의 이해를 돕습니다. 런북을 열어도 로컬 데이터는 전송되지 않습니다.", contextEmpty: "활성 프로필이 없습니다. 배포판, 커널, 드라이버, Proton을 비교하려면 로컬 스캔을 구성하거나 가져오세요.", configureProfile: "내 PC 구성", diagnosis: "진단 맵", symptoms: "관찰된 증상", likelyCause: "주요 가설", runbook: "기술 절차", beforeYouStart: "시작 전", changeOneThing: "한 번에 하나의 변수만 바꾸고 계속하기 전에 결과를 기록하세요.", step: "단계", verify: "검증 방법", rollback: "되돌리는 방법", evidence: "증거 및 범위", source: "출처 열기", noSource: "이 단계에는 추가 출처가 기록되지 않았습니다.", feedbackTitle: "환경 보고", feedbackDescription: "투표, 확인 및 댓글은 사용자 경험을 설명할 뿐 수정 사항을 검증됨으로 만들지 않습니다.", noCommunityData: "게시된 보고가 아직 없습니다. 민감한 데이터 없이 환경 결과를 처음으로 기록하세요.", reportTitle: "편집 검토", reportDescription: "오래된 지침, 깨진 출처 또는 문서화되지 않은 위험을 신고하세요. 결정은 검토를 위해 보존됩니다.", reportButton: "문제 신고", kind: { inspect: "점검", change: "변경", verify: "검증", recover: "복구" }, risk: { read_only: "읽기 전용", reversible: "되돌릴 수 있음", system_change: "시스템 변경" },
  },
  ar: {
    catalogEyebrow: "LINUXFIX / أدلة التشغيل", catalogTitle: "اعثر على الفرضية قبل تغيير النظام.", catalogDescription: "يفصل كل دليل التشغيل بين الفحص والتغيير والتحقق والتراجع والمصدر. تظل البيانات الناقصة واضحة.", searchPlaceholder: "ابحث عن Steam أو Proton أو التقطيع أو الشاشة السوداء…", allCategories: "كل الفئات", sourceRule: "تظهر هنا الإجراءات ذات المصدر المسجّل فقط.", noResultsTitle: "لا يوجد دليل تشغيل منشور", noResultsDescription: "لا يملك هذا العطل إجراءً بمصادر كافية بعد. يمكنك الإبلاغ عن الفجوة بعد تسجيل الدخول.", openRunbook: "فتح دليل التشغيل", confidence: "الثقة", detailsEyebrow: "LINUXFIX / تشخيص", detailsDescription: "اختبر متغيراً واحداً في كل مرة. تأكيدات المستخدمين لا تحل محل الدليل التقني المدعوم بالمصدر.", contextTitle: "السياق التقني", contextReady: "يتوفر ملف نشط لتوجيه القراءة. فتح هذا الدليل لا يرسل بيانات محلية.", contextEmpty: "لا يوجد ملف نشط. اضبط أو استورد فحصاً محلياً لمقارنة التوزيعة والنواة والتعريف وProton.", configureProfile: "إعداد جهازي", diagnosis: "خريطة التشخيص", symptoms: "الأعراض الملاحظة", likelyCause: "الفرضية الأساسية", runbook: "الإجراء التقني", beforeYouStart: "قبل البدء", changeOneThing: "غيّر متغيراً واحداً في كل مرة وسجل النتيجة قبل المتابعة.", step: "خطوة", verify: "كيفية التحقق", rollback: "كيفية التراجع", evidence: "الدليل والنطاق", source: "فتح المصدر", noSource: "لا يوجد مصدر إضافي مسجل لهذه الخطوة.", feedbackTitle: "تقارير البيئة", feedbackDescription: "تصف الأصوات والتأكيدات والتعليقات تجارب المستخدمين؛ ولا تجعل الإصلاح موثقاً.", noCommunityData: "لا توجد تقارير منشورة بعد. كن أول من يسجل نتيجة بيئتك دون بيانات حساسة.", reportTitle: "مراجعة تحريرية", reportDescription: "أبلغ عن تعليمات قديمة أو مصدر معطل أو خطر غير موثق. يبقى القرار مسجلاً للمراجعة.", reportButton: "الإبلاغ عن مشكلة", kind: { inspect: "فحص", change: "تغيير", verify: "تحقق", recover: "استعادة" }, risk: { read_only: "قراءة فقط", reversible: "قابل للتراجع", system_change: "تغيير النظام" },
  },
};

type LinuxFixContributionCopy = {
  eyebrow: string; title: string; description: string; safety: string; start: string; observation: string; reproduction: string; suggestedSteps: string; source: string; sourceHint: string; shareContext: string; consent: string; submit: string; submitted: string; mine: string; empty: string; withdraw: string; statuses: Record<"submitted" | "in_review" | "accepted" | "rejected" | "withdrawn", string>;
};

export const linuxFixContributionCopy: Record<Locale, LinuxFixContributionCopy> = {
  "pt-BR": { eyebrow: "CONTRIBUIÇÃO MODERADA", title: "Proponha uma melhoria para este runbook", description: "Envie uma observação reproduzível, não uma solução publicada. A proposta só altera o conteúdo após revisão editorial.", safety: "Não inclua senhas, chaves, IPs, caminhos pessoais, logs completos ou comandos destrutivos. O contexto técnico é opcional e minimizado.", start: "Nova proposta", observation: "O que você observou?", reproduction: "Como reproduzir com segurança?", suggestedSteps: "Procedimento sugerido", source: "Fonte externa (opcional)", sourceHint: "https://documentação-ou-issue", shareContext: "Anexar contexto técnico mínimo", consent: "Se marcado, envia somente distro, kernel, driver, Proton, Wine e GPU do perfil ativo. Nenhum dado é enviado automaticamente pelo Scanner ou pelo app desktop.", submit: "Enviar para revisão", submitted: "Proposta enviada para revisão.", mine: "Minhas propostas", empty: "Você ainda não enviou propostas para este runbook.", withdraw: "Retirar", statuses: { submitted: "Enviada", in_review: "Em revisão", accepted: "Aceita para edição", rejected: "Recusada", withdrawn: "Retirada" } },
  en: { eyebrow: "MODERATED CONTRIBUTION", title: "Propose an improvement to this runbook", description: "Submit a reproducible observation, not published advice. A proposal changes content only after editorial review.", safety: "Do not include passwords, keys, IPs, personal paths, full logs or destructive commands. Technical context is optional and minimized.", start: "New proposal", observation: "What did you observe?", reproduction: "How can it be safely reproduced?", suggestedSteps: "Suggested procedure", source: "External source (optional)", sourceHint: "https://documentation-or-issue", shareContext: "Attach minimal technical context", consent: "When selected, only distro, kernel, driver, Proton, Wine and GPU from the active profile are sent. No data is sent automatically by Scanner or the desktop app.", submit: "Submit for review", submitted: "Proposal submitted for review.", mine: "My proposals", empty: "You have not submitted proposals for this runbook.", withdraw: "Withdraw", statuses: { submitted: "Submitted", in_review: "In review", accepted: "Accepted for editing", rejected: "Rejected", withdrawn: "Withdrawn" } },
  es: { eyebrow: "CONTRIBUCIÓN MODERADA", title: "Propón una mejora para este runbook", description: "Envía una observación reproducible, no una instrucción publicada. Una propuesta solo cambia contenido tras revisión editorial.", safety: "No incluyas contraseñas, claves, IP, rutas personales, logs completos ni comandos destructivos. El contexto técnico es opcional y mínimo.", start: "Nueva propuesta", observation: "¿Qué observaste?", reproduction: "¿Cómo reproducirlo con seguridad?", suggestedSteps: "Procedimiento sugerido", source: "Fuente externa (opcional)", sourceHint: "https://documentacion-o-issue", shareContext: "Adjuntar contexto técnico mínimo", consent: "Al marcarlo, solo se envían distro, kernel, driver, Proton, Wine y GPU del perfil activo. Scanner y la app de escritorio no envían datos automáticamente.", submit: "Enviar a revisión", submitted: "Propuesta enviada a revisión.", mine: "Mis propuestas", empty: "Aún no enviaste propuestas para este runbook.", withdraw: "Retirar", statuses: { submitted: "Enviada", in_review: "En revisión", accepted: "Aceptada para edición", rejected: "Rechazada", withdrawn: "Retirada" } },
  fr: { eyebrow: "CONTRIBUTION MODÉRÉE", title: "Proposer une amélioration de ce runbook", description: "Envoyez une observation reproductible, pas une instruction publiée. Une proposition ne modifie le contenu qu’après révision éditoriale.", safety: "N’incluez ni mots de passe, ni clés, ni IP, ni chemins personnels, ni journaux complets, ni commandes destructrices. Le contexte technique est facultatif et réduit.", start: "Nouvelle proposition", observation: "Qu’avez-vous observé ?", reproduction: "Comment le reproduire sans risque ?", suggestedSteps: "Procédure suggérée", source: "Source externe (facultative)", sourceHint: "https://documentation-ou-issue", shareContext: "Joindre un contexte technique minimal", consent: "Si sélectionné, seuls distribution, noyau, pilote, Proton, Wine et GPU du profil actif sont envoyés. Scanner et l’application desktop n’envoient rien automatiquement.", submit: "Envoyer pour révision", submitted: "Proposition envoyée pour révision.", mine: "Mes propositions", empty: "Vous n’avez encore envoyé aucune proposition pour ce runbook.", withdraw: "Retirer", statuses: { submitted: "Envoyée", in_review: "En révision", accepted: "Acceptée pour édition", rejected: "Refusée", withdrawn: "Retirée" } },
  de: { eyebrow: "MODERIERTER BEITRAG", title: "Verbesserung für dieses Runbook vorschlagen", description: "Senden Sie eine reproduzierbare Beobachtung, keine veröffentlichte Anleitung. Ein Vorschlag ändert Inhalte erst nach redaktioneller Prüfung.", safety: "Keine Passwörter, Schlüssel, IPs, persönlichen Pfade, vollständigen Logs oder destruktiven Befehle angeben. Technischer Kontext ist optional und minimiert.", start: "Neuer Vorschlag", observation: "Was haben Sie beobachtet?", reproduction: "Wie lässt es sich sicher reproduzieren?", suggestedSteps: "Vorgeschlagenes Verfahren", source: "Externe Quelle (optional)", sourceHint: "https://dokumentation-oder-issue", shareContext: "Minimalen technischen Kontext anhängen", consent: "Bei Auswahl werden nur Distro, Kernel, Treiber, Proton, Wine und GPU des aktiven Profils gesendet. Scanner und Desktop-App senden keine Daten automatisch.", submit: "Zur Prüfung senden", submitted: "Vorschlag zur Prüfung gesendet.", mine: "Meine Vorschläge", empty: "Für dieses Runbook wurden noch keine Vorschläge gesendet.", withdraw: "Zurückziehen", statuses: { submitted: "Eingereicht", in_review: "In Prüfung", accepted: "Für Bearbeitung akzeptiert", rejected: "Abgelehnt", withdrawn: "Zurückgezogen" } },
  it: { eyebrow: "CONTRIBUTO MODERATO", title: "Proponi un miglioramento per questo runbook", description: "Invia un’osservazione riproducibile, non un’istruzione pubblicata. Una proposta cambia il contenuto solo dopo revisione editoriale.", safety: "Non includere password, chiavi, IP, percorsi personali, log completi o comandi distruttivi. Il contesto tecnico è facoltativo e ridotto.", start: "Nuova proposta", observation: "Cosa hai osservato?", reproduction: "Come riprodurlo in sicurezza?", suggestedSteps: "Procedura suggerita", source: "Fonte esterna (facoltativa)", sourceHint: "https://documentazione-o-issue", shareContext: "Allega contesto tecnico minimo", consent: "Se selezionato, vengono inviati solo distro, kernel, driver, Proton, Wine e GPU del profilo attivo. Scanner e app desktop non inviano dati automaticamente.", submit: "Invia per revisione", submitted: "Proposta inviata per revisione.", mine: "Le mie proposte", empty: "Non hai ancora inviato proposte per questo runbook.", withdraw: "Ritira", statuses: { submitted: "Inviata", in_review: "In revisione", accepted: "Accettata per modifica", rejected: "Rifiutata", withdrawn: "Ritirata" } },
  ru: { eyebrow: "МОДЕРИРУЕМЫЙ ВКЛАД", title: "Предложить улучшение для этого руководства", description: "Отправьте воспроизводимое наблюдение, а не опубликованную инструкцию. Предложение меняет контент только после редакционной проверки.", safety: "Не указывайте пароли, ключи, IP, личные пути, полные логи или разрушительные команды. Технический контекст необязателен и минимизирован.", start: "Новое предложение", observation: "Что вы наблюдали?", reproduction: "Как безопасно воспроизвести?", suggestedSteps: "Предлагаемая процедура", source: "Внешний источник (необязательно)", sourceHint: "https://документация-или-issue", shareContext: "Приложить минимальный технический контекст", consent: "При выборе отправляются только дистрибутив, ядро, драйвер, Proton, Wine и GPU активного профиля. Scanner и desktop-приложение ничего не отправляют автоматически.", submit: "Отправить на проверку", submitted: "Предложение отправлено на проверку.", mine: "Мои предложения", empty: "Вы ещё не отправляли предложений для этого руководства.", withdraw: "Отозвать", statuses: { submitted: "Отправлено", in_review: "На проверке", accepted: "Принято для редактирования", rejected: "Отклонено", withdrawn: "Отозвано" } },
  "zh-CN": { eyebrow: "受审核贡献", title: "为此操作手册提出改进", description: "提交可复现的观察，而不是已发布的说明。提案仅在编辑审核后才会更改内容。", safety: "不要包含密码、密钥、IP、个人路径、完整日志或破坏性命令。技术上下文为可选且已最小化。", start: "新提案", observation: "你观察到了什么？", reproduction: "如何安全复现？", suggestedSteps: "建议流程", source: "外部来源（可选）", sourceHint: "https://文档或问题", shareContext: "附加最小技术上下文", consent: "选中后，只会发送活动配置中的发行版、内核、驱动、Proton、Wine 和 GPU。扫描器和桌面应用不会自动发送数据。", submit: "提交审核", submitted: "提案已提交审核。", mine: "我的提案", empty: "你尚未为此操作手册提交提案。", withdraw: "撤回", statuses: { submitted: "已提交", in_review: "审核中", accepted: "已接受编辑", rejected: "已拒绝", withdrawn: "已撤回" } },
  ja: { eyebrow: "モデレーション済み投稿", title: "このランブックの改善を提案", description: "公開済みの指示ではなく、再現可能な観察を送信してください。提案は編集レビュー後にのみ内容を変更します。", safety: "パスワード、キー、IP、個人パス、完全なログ、破壊的なコマンドを含めないでください。技術コンテキストは任意で最小化されます。", start: "新しい提案", observation: "何を観察しましたか？", reproduction: "安全に再現するには？", suggestedSteps: "提案する手順", source: "外部ソース（任意）", sourceHint: "https://ドキュメントまたはissue", shareContext: "最小技術コンテキストを添付", consent: "選択すると、アクティブプロファイルのディストリビューション、カーネル、ドライバー、Proton、Wine、GPU のみ送信されます。Scanner とデスクトップアプリは自動送信しません。", submit: "レビューに送信", submitted: "提案をレビューに送信しました。", mine: "自分の提案", empty: "このランブックにはまだ提案を送信していません。", withdraw: "取り下げ", statuses: { submitted: "送信済み", in_review: "レビュー中", accepted: "編集用に承認", rejected: "却下", withdrawn: "取り下げ済み" } },
  ko: { eyebrow: "검토형 기여", title: "이 런북 개선 제안", description: "게시된 지침이 아닌 재현 가능한 관찰을 제출하세요. 제안은 편집 검토 후에만 콘텐츠를 변경합니다.", safety: "비밀번호, 키, IP, 개인 경로, 전체 로그 또는 파괴적인 명령을 포함하지 마세요. 기술 컨텍스트는 선택 사항이며 최소화됩니다.", start: "새 제안", observation: "무엇을 관찰했나요?", reproduction: "안전하게 재현하려면?", suggestedSteps: "제안 절차", source: "외부 출처(선택 사항)", sourceHint: "https://문서-또는-issue", shareContext: "최소 기술 컨텍스트 첨부", consent: "선택하면 활성 프로필의 배포판, 커널, 드라이버, Proton, Wine, GPU만 전송됩니다. Scanner와 데스크톱 앱은 데이터를 자동으로 전송하지 않습니다.", submit: "검토에 제출", submitted: "제안이 검토에 제출되었습니다.", mine: "내 제안", empty: "이 런북에 아직 제안을 제출하지 않았습니다.", withdraw: "철회", statuses: { submitted: "제출됨", in_review: "검토 중", accepted: "편집 승인", rejected: "거절됨", withdrawn: "철회됨" } },
  ar: { eyebrow: "مساهمة خاضعة للإشراف", title: "اقترح تحسيناً لهذا الدليل", description: "أرسل ملاحظة قابلة لإعادة الإنتاج، وليس تعليمات منشورة. لا يغير الاقتراح المحتوى إلا بعد مراجعة تحريرية.", safety: "لا تُضمّن كلمات مرور أو مفاتيح أو عناوين IP أو مسارات شخصية أو سجلات كاملة أو أوامر مدمرة. السياق التقني اختياري ومصغّر.", start: "اقتراح جديد", observation: "ماذا لاحظت؟", reproduction: "كيف يمكن إعادة إنتاجه بأمان؟", suggestedSteps: "الإجراء المقترح", source: "مصدر خارجي (اختياري)", sourceHint: "https://توثيق-أو-issue", shareContext: "إرفاق سياق تقني أدنى", consent: "عند التحديد، تُرسل فقط التوزيعة والنواة والتعريف وProton وWine وGPU من الملف النشط. لا يرسل الماسح أو تطبيق سطح المكتب البيانات تلقائياً.", submit: "إرسال للمراجعة", submitted: "تم إرسال الاقتراح للمراجعة.", mine: "اقتراحاتي", empty: "لم ترسل اقتراحات لهذا الدليل بعد.", withdraw: "سحب", statuses: { submitted: "مرسل", in_review: "قيد المراجعة", accepted: "مقبول للتحرير", rejected: "مرفوض", withdrawn: "مسحوب" } },
};

type LinuxFixModerationCopy = { title: string; description: string; empty: string; review: string; accept: string; reject: string; context: string; source: string; };

export const linuxFixModerationCopy: Record<Locale, LinuxFixModerationCopy> = {
  "pt-BR": { title: "Propostas LinuxFix aguardando revisão", description: "Propostas são privadas até a decisão. Aceitar para edição não publica comandos nem altera o runbook automaticamente.", empty: "Nenhuma proposta aguardando revisão.", review: "Iniciar revisão", accept: "Aceitar para edição", reject: "Recusar", context: "Contexto técnico consentido", source: "Fonte declarada" },
  en: { title: "LinuxFix proposals awaiting review", description: "Proposals stay private until a decision. Accepting for editing does not publish commands or change the runbook automatically.", empty: "No proposals awaiting review.", review: "Start review", accept: "Accept for editing", reject: "Reject", context: "Consented technical context", source: "Declared source" },
  es: { title: "Propuestas LinuxFix pendientes de revisión", description: "Las propuestas son privadas hasta una decisión. Aceptar para edición no publica comandos ni cambia el runbook automáticamente.", empty: "No hay propuestas pendientes de revisión.", review: "Iniciar revisión", accept: "Aceptar para edición", reject: "Rechazar", context: "Contexto técnico consentido", source: "Fuente declarada" },
  fr: { title: "Propositions LinuxFix en attente de révision", description: "Les propositions restent privées jusqu’à la décision. L’acceptation pour édition ne publie pas de commandes et ne modifie pas le runbook automatiquement.", empty: "Aucune proposition en attente de révision.", review: "Démarrer la révision", accept: "Accepter pour édition", reject: "Refuser", context: "Contexte technique consenti", source: "Source déclarée" },
  de: { title: "LinuxFix-Vorschläge warten auf Prüfung", description: "Vorschläge bleiben bis zur Entscheidung privat. Die Annahme zur Bearbeitung veröffentlicht keine Befehle und ändert das Runbook nicht automatisch.", empty: "Keine Vorschläge warten auf Prüfung.", review: "Prüfung starten", accept: "Zur Bearbeitung annehmen", reject: "Ablehnen", context: "Zustimmter technischer Kontext", source: "Angegebene Quelle" },
  it: { title: "Proposte LinuxFix in attesa di revisione", description: "Le proposte restano private fino alla decisione. L’accettazione per modifica non pubblica comandi né cambia automaticamente il runbook.", empty: "Nessuna proposta in attesa di revisione.", review: "Avvia revisione", accept: "Accetta per modifica", reject: "Rifiuta", context: "Contesto tecnico consensuale", source: "Fonte dichiarata" },
  ru: { title: "Предложения LinuxFix ждут проверки", description: "Предложения остаются приватными до решения. Принятие для редактирования не публикует команды и не меняет руководство автоматически.", empty: "Нет предложений, ожидающих проверки.", review: "Начать проверку", accept: "Принять для редактирования", reject: "Отклонить", context: "Технический контекст с согласием", source: "Указанный источник" },
  "zh-CN": { title: "等待审核的 LinuxFix 提案", description: "提案在决定前保持私密。接受编辑不会发布命令，也不会自动更改操作手册。", empty: "没有等待审核的提案。", review: "开始审核", accept: "接受编辑", reject: "拒绝", context: "已同意的技术上下文", source: "声明的来源" },
  ja: { title: "レビュー待ちの LinuxFix 提案", description: "提案は決定まで非公開です。編集の受け入れではコマンドは公開されず、ランブックも自動変更されません。", empty: "レビュー待ちの提案はありません。", review: "レビュー開始", accept: "編集用に承認", reject: "却下", context: "同意済み技術コンテキスト", source: "申告したソース" },
  ko: { title: "검토 대기 중인 LinuxFix 제안", description: "제안은 결정 전까지 비공개입니다. 편집 수락은 명령을 게시하거나 런북을 자동 변경하지 않습니다.", empty: "검토 대기 중인 제안이 없습니다.", review: "검토 시작", accept: "편집 승인", reject: "거절", context: "동의한 기술 컨텍스트", source: "선언된 출처" },
  ar: { title: "اقتراحات LinuxFix بانتظار المراجعة", description: "تبقى الاقتراحات خاصة حتى القرار. القبول للتحرير لا ينشر أوامر ولا يغير الدليل تلقائياً.", empty: "لا توجد اقتراحات بانتظار المراجعة.", review: "بدء المراجعة", accept: "قبول للتحرير", reject: "رفض", context: "سياق تقني بموافقة", source: "مصدر معلن" },
};
