import type { Locale } from "@/contexts/LanguageContext";

type OverviewCopy = {
  eyebrow: string;
  title: string;
  description: string;
  catalog: string;
  catalogDescription: string;
  system: string;
  systemDescription: string;
  scannerAction: string;
  profileAction: string;
  noProfile: string;
  viewCatalog: string;
  evidence: string;
};

export const overviewCopy: Record<Locale, OverviewCopy> = {
  "pt-BR": { eyebrow: "VISÃO GERAL / GAME INTELLIGENCE", title: "Central de gaming Linux", description: "Organize seu ambiente, encontre jogos e consulte somente evidências publicadas.", catalog: "Catálogo operacional", catalogDescription: "Jogos indexados com metadados e descrição quando a fonte permite.", system: "Contexto do sistema", systemDescription: "Use o Scanner local ou crie um perfil para relacionar registros ao seu ambiente.", scannerAction: "Abrir Scanner", profileAction: "Configurar Meu PC", noProfile: "Nenhum perfil ativo", viewCatalog: "Abrir GameHub", evidence: "Dados ausentes permanecem explícitos" },
  en: { eyebrow: "OVERVIEW / GAME INTELLIGENCE", title: "Linux gaming hub", description: "Organize your environment, find games and consult only published evidence.", catalog: "Operational catalog", catalogDescription: "Indexed games with metadata and a description when the source allows it.", system: "System context", systemDescription: "Use the local Scanner or create a profile to relate records to your environment.", scannerAction: "Open Scanner", profileAction: "Configure My PC", noProfile: "No active profile", viewCatalog: "Open GameHub", evidence: "Missing data stays explicit" },
  es: { eyebrow: "RESUMEN / INTELIGENCIA DE JUEGOS", title: "Centro de juegos Linux", description: "Organiza tu entorno, encuentra juegos y consulta solo evidencia publicada.", catalog: "Catálogo operativo", catalogDescription: "Juegos indexados con metadatos y descripción cuando la fuente lo permite.", system: "Contexto del sistema", systemDescription: "Usa el Escáner local o crea un perfil para relacionar registros con tu entorno.", scannerAction: "Abrir escáner", profileAction: "Configurar Mi PC", noProfile: "Sin perfil activo", viewCatalog: "Abrir GameHub", evidence: "Los datos ausentes siguen explícitos" },
  fr: { eyebrow: "VUE D’ENSEMBLE / GAME INTELLIGENCE", title: "Centre de jeu Linux", description: "Organisez votre environnement, trouvez des jeux et consultez uniquement les preuves publiées.", catalog: "Catalogue opérationnel", catalogDescription: "Jeux indexés avec métadonnées et description lorsque la source l’autorise.", system: "Contexte système", systemDescription: "Utilisez l’Analyseur local ou créez un profil pour relier les enregistrements à votre environnement.", scannerAction: "Ouvrir l’analyseur", profileAction: "Configurer Mon PC", noProfile: "Aucun profil actif", viewCatalog: "Ouvrir GameHub", evidence: "Les données manquantes restent explicites" },
  de: { eyebrow: "ÜBERSICHT / GAME INTELLIGENCE", title: "Linux-Gaming-Zentrale", description: "Organisieren Sie Ihre Umgebung, finden Sie Spiele und nutzen Sie nur veröffentlichte Evidenz.", catalog: "Betriebskatalog", catalogDescription: "Indizierte Spiele mit Metadaten und Beschreibung, wenn die Quelle dies erlaubt.", system: "Systemkontext", systemDescription: "Nutzen Sie den lokalen Scanner oder ein Profil, um Einträge Ihrer Umgebung zuzuordnen.", scannerAction: "Scanner öffnen", profileAction: "Mein PC einrichten", noProfile: "Kein aktives Profil", viewCatalog: "GameHub öffnen", evidence: "Fehlende Daten bleiben ausdrücklich markiert" },
  it: { eyebrow: "PANORAMICA / GAME INTELLIGENCE", title: "Centro gaming Linux", description: "Organizza il tuo ambiente, trova giochi e consulta solo evidenze pubblicate.", catalog: "Catalogo operativo", catalogDescription: "Giochi indicizzati con metadati e descrizione quando la fonte lo consente.", system: "Contesto di sistema", systemDescription: "Usa lo Scanner locale o crea un profilo per collegare i record al tuo ambiente.", scannerAction: "Apri Scanner", profileAction: "Configura Il mio PC", noProfile: "Nessun profilo attivo", viewCatalog: "Apri GameHub", evidence: "I dati mancanti restano espliciti" },
  ru: { eyebrow: "ОБЗОР / GAME INTELLIGENCE", title: "Центр Linux Gaming", description: "Организуйте среду, находите игры и используйте только опубликованные свидетельства.", catalog: "Рабочий каталог", catalogDescription: "Индексированные игры с метаданными и описанием, когда источник это допускает.", system: "Контекст системы", systemDescription: "Используйте локальный Сканер или профиль, чтобы сопоставить записи с вашей средой.", scannerAction: "Открыть Сканер", profileAction: "Настроить Мой ПК", noProfile: "Нет активного профиля", viewCatalog: "Открыть GameHub", evidence: "Отсутствующие данные остаются явными" },
  "zh-CN": { eyebrow: "概览 / 游戏智能", title: "Linux 游戏中心", description: "整理你的环境、查找游戏，并且只查看已发布的证据。", catalog: "运行目录", catalogDescription: "已索引的游戏包含元数据，以及来源允许时的描述。", system: "系统上下文", systemDescription: "使用本地扫描器或创建配置文件，将记录与你的环境关联。", scannerAction: "打开扫描器", profileAction: "配置我的电脑", noProfile: "没有活动配置文件", viewCatalog: "打开 GameHub", evidence: "缺失的数据会保持明确" },
  ja: { eyebrow: "概要 / GAME INTELLIGENCE", title: "Linux ゲーミングハブ", description: "環境を整理し、ゲームを探し、公開済みの根拠のみを参照します。", catalog: "運用カタログ", catalogDescription: "ソースが許可する場合、メタデータと説明を持つインデックス済みゲームです。", system: "システムコンテキスト", systemDescription: "ローカルスキャナーを使うか、プロファイルを作成して記録を環境に関連付けます。", scannerAction: "スキャナーを開く", profileAction: "マイPCを設定", noProfile: "アクティブなプロファイルなし", viewCatalog: "GameHub を開く", evidence: "欠落したデータは明示されたままです" },
  ko: { eyebrow: "개요 / GAME INTELLIGENCE", title: "Linux 게이밍 허브", description: "환경을 정리하고 게임을 찾으며 공개된 근거만 확인합니다.", catalog: "운영 카탈로그", catalogDescription: "출처가 허용할 때 메타데이터와 설명이 포함된 색인 게임입니다.", system: "시스템 컨텍스트", systemDescription: "로컬 스캐너를 사용하거나 프로필을 만들어 기록을 환경과 연결하세요.", scannerAction: "스캐너 열기", profileAction: "내 PC 구성", noProfile: "활성 프로필 없음", viewCatalog: "GameHub 열기", evidence: "누락된 데이터는 명시적으로 유지됩니다" },
  ar: { eyebrow: "نظرة عامة / ذكاء الألعاب", title: "مركز ألعاب Linux", description: "نظّم بيئتك، وابحث عن الألعاب، واطّلع فقط على الأدلة المنشورة.", catalog: "كتالوج تشغيلي", catalogDescription: "ألعاب مفهرسة مع بيانات وصفية ووصف حين تسمح المصدر بذلك.", system: "سياق النظام", systemDescription: "استخدم الماسح المحلي أو أنشئ ملفًا شخصيًا لربط السجلات ببيئتك.", scannerAction: "فتح الماسح", profileAction: "إعداد جهازي", noProfile: "لا يوجد ملف شخصي نشط", viewCatalog: "فتح GameHub", evidence: "تبقى البيانات المفقودة صريحة" },
};
