import type { Locale } from "@/contexts/LanguageContext";

type ProductShellCopy = { workspace: string; system: string; personal: string; tools: string; compare: string; status: string; version: string; assistant: string; systemInformation: string; diagnostics: string; performance: string; mods: string; snapshots: string; systemMap: string; timeline: string; preflight: string; regression: string; recovery: string; logs: string; alerts: string; controllers: string; localActivity: string; supportProject: string; };

export const productShellCopy: Record<Locale, ProductShellCopy> = {
  "pt-BR": { workspace: "ÁREA PRINCIPAL", system: "SISTEMA", personal: "PESSOAL", tools: "MAIS FERRAMENTAS", compare: "Comparar", status: "Sistema local", version: "Versão 1.2.0", assistant: "Stray AI", systemInformation: "Informações do sistema", diagnostics: "Diagnóstico", performance: "Performance", mods: "Mods", snapshots: "Snapshots", systemMap: "Mapa do sistema", timeline: "Linha do tempo", preflight: "Pré-voo", regression: "Regressão", recovery: "Recuperação", logs: "Registros", alerts: "Alertas", controllers: "Controles", localActivity: "Atividade local", supportProject: "Apoie o projeto" },
  en: { workspace: "MAIN AREA", system: "SYSTEM", personal: "PERSONAL", tools: "MORE TOOLS", compare: "Compare", status: "Local system", version: "Version 1.2.0", assistant: "Stray AI", systemInformation: "System information", diagnostics: "Diagnostics", performance: "Performance", mods: "Mods", snapshots: "Snapshots", systemMap: "System map", timeline: "Timeline", preflight: "Preflight", regression: "Regression", recovery: "Recovery", logs: "Logs", alerts: "Alerts", controllers: "Controllers", localActivity: "Local activity", supportProject: "Support the project" },
  es: { workspace: "ÁREA PRINCIPAL", system: "SISTEMA", personal: "PERSONAL", tools: "MÁS HERRAMIENTAS", compare: "Comparar", status: "Sistema local", version: "Versión 1.2.0", assistant: "Stray AI", systemInformation: "Información del sistema", diagnostics: "Diagnóstico", performance: "Rendimiento", mods: "Mods", snapshots: "Instantáneas", systemMap: "Mapa del sistema", timeline: "Línea de tiempo", preflight: "Comprobación previa", regression: "Regresión", recovery: "Recuperación", logs: "Registros", alerts: "Alertas", controllers: "Controles", localActivity: "Actividad local", supportProject: "Apoya el proyecto" },
  fr: { workspace: "ESPACE PRINCIPAL", system: "SYSTÈME", personal: "PERSONNEL", tools: "PLUS D'OUTILS", compare: "Comparer", status: "Système local", version: "Version 1.2.0", assistant: "Stray AI", systemInformation: "Informations système", diagnostics: "Diagnostic", performance: "Performances", mods: "Mods", snapshots: "Instantanés", systemMap: "Carte du système", timeline: "Chronologie", preflight: "Pré-vérification", regression: "Régression", recovery: "Récupération", logs: "Journaux", alerts: "Alertes", controllers: "Contrôleurs", localActivity: "Activité locale", supportProject: "Soutenir le projet" },
  de: { workspace: "HAUPTBEREICH", system: "SYSTEM", personal: "PERSÖNLICH", tools: "WEITERE WERKZEUGE", compare: "Vergleichen", status: "Lokales System", version: "Version 1.2.0", assistant: "Stray AI", systemInformation: "Systeminformationen", diagnostics: "Diagnose", performance: "Leistung", mods: "Mods", snapshots: "Schnappschüsse", systemMap: "Systemkarte", timeline: "Zeitachse", preflight: "Vorabprüfung", regression: "Regression", recovery: "Wiederherstellung", logs: "Protokolle", alerts: "Warnungen", controllers: "Controller", localActivity: "Lokale Aktivität", supportProject: "Projekt unterstützen" },
  it: { workspace: "AREA PRINCIPALE", system: "SISTEMA", personal: "PERSONALE", tools: "ALTRI STRUMENTI", compare: "Confronta", status: "Sistema locale", version: "Versione 1.2.0", assistant: "Stray AI", systemInformation: "Informazioni di sistema", diagnostics: "Diagnostica", performance: "Prestazioni", mods: "Mod", snapshots: "Istantanee", systemMap: "Mappa del sistema", timeline: "Cronologia", preflight: "Controllo preliminare", regression: "Regressione", recovery: "Recupero", logs: "Registri", alerts: "Avvisi", controllers: "Controller", localActivity: "Attività locale", supportProject: "Sostieni il progetto" },
  ru: { workspace: "ОСНОВНОЙ РАЗДЕЛ", system: "СИСТЕМА", personal: "ЛИЧНОЕ", tools: "БОЛЬШЕ ИНСТРУМЕНТОВ", compare: "Сравнить", status: "Локальная система", version: "Версия 1.2.0", assistant: "Stray AI", systemInformation: "Сведения о системе", diagnostics: "Диагностика", performance: "Производительность", mods: "Моды", snapshots: "Снимки", systemMap: "Карта системы", timeline: "Временная шкала", preflight: "Предпроверка", regression: "Регрессия", recovery: "Восстановление", logs: "Журналы", alerts: "Оповещения", controllers: "Контроллеры", localActivity: "Локальная активность", supportProject: "Поддержать проект" },
  "zh-CN": { workspace: "主区域", system: "系统", personal: "个人", tools: "更多工具", compare: "比较", status: "本地系统", version: "版本 1.2.0", assistant: "Stray AI", systemInformation: "系统信息", diagnostics: "诊断", performance: "性能", mods: "模组", snapshots: "快照", systemMap: "系统地图", timeline: "时间线", preflight: "预检", regression: "回归", recovery: "恢复", logs: "日志", alerts: "警报", controllers: "控制器", localActivity: "本地活动", supportProject: "支持项目" },
  ja: { workspace: "メインエリア", system: "システム", personal: "個人", tools: "その他のツール", compare: "比較", status: "ローカルシステム", version: "バージョン 1.2.0", assistant: "Stray AI", systemInformation: "システム情報", diagnostics: "診断", performance: "パフォーマンス", mods: "MOD", snapshots: "スナップショット", systemMap: "システムマップ", timeline: "タイムライン", preflight: "事前確認", regression: "回帰", recovery: "復旧", logs: "ログ", alerts: "通知", controllers: "コントローラー", localActivity: "ローカルアクティビティ", supportProject: "プロジェクトを支援" },
  ko: { workspace: "기본 영역", system: "시스템", personal: "개인", tools: "추가 도구", compare: "비교", status: "로컬 시스템", version: "버전 1.2.0", assistant: "Stray AI", systemInformation: "시스템 정보", diagnostics: "진단", performance: "성능", mods: "모드", snapshots: "스냅샷", systemMap: "시스템 맵", timeline: "타임라인", preflight: "사전 점검", regression: "회귀", recovery: "복구", logs: "로그", alerts: "알림", controllers: "컨트롤러", localActivity: "로컬 활동", supportProject: "프로젝트 지원" },
  ar: { workspace: "المنطقة الرئيسية", system: "النظام", personal: "شخصي", tools: "المزيد من الأدوات", compare: "مقارنة", status: "نظام محلي", version: "الإصدار 1.2.0", assistant: "Stray AI", systemInformation: "معلومات النظام", diagnostics: "التشخيص", performance: "الأداء", mods: "التعديلات", snapshots: "اللقطات", systemMap: "خريطة النظام", timeline: "الخط الزمني", preflight: "فحص مسبق", regression: "تراجع", recovery: "استرداد", logs: "السجلات", alerts: "التنبيهات", controllers: "وحدات التحكم", localActivity: "النشاط المحلي", supportProject: "دعم المشروع" },
};
