import type { Locale } from "@/contexts/LanguageContext";

type RoadmapCopy = { nav: string; title: string; statusLabel: string; planning: string; building: string; validated: string; summary: string; disclaimer: string };

export const roadmapCopy: Record<Locale, RoadmapCopy> = {
  "pt-BR": { nav: "Roadmap", title: "Roadmap de intenção", statusLabel: "STATUS DO PRODUTO", planning: "Em planejamento", building: "Em desenvolvimento", validated: "Validada", summary: "Os estados mostram o estágio do produto e levam ao detalhamento completo.", disclaimer: "Status de produto não garantem funcionamento universal no seu computador." },
  en: { nav: "Roadmap", title: "Intent roadmap", statusLabel: "PRODUCT STATUS", planning: "Planning", building: "In development", validated: "Validated", summary: "Statuses show the product stage and lead to the complete details.", disclaimer: "Product status does not guarantee universal operation on your computer." },
  es: { nav: "Roadmap", title: "Roadmap de intención", statusLabel: "ESTADO DEL PRODUCTO", planning: "En planificación", building: "En desarrollo", validated: "Validada", summary: "Los estados muestran la etapa del producto y llevan al detalle completo.", disclaimer: "El estado del producto no garantiza funcionamiento universal en su equipo." },
  fr: { nav: "Roadmap", title: "Roadmap d’intention", statusLabel: "ÉTAT DU PRODUIT", planning: "En planification", building: "En développement", validated: "Validée", summary: "Les statuts indiquent l’étape du produit et mènent au détail complet.", disclaimer: "Le statut du produit ne garantit pas un fonctionnement universel sur votre ordinateur." },
  de: { nav: "Roadmap", title: "Roadmap der Absicht", statusLabel: "PRODUKTSTATUS", planning: "In Planung", building: "In Entwicklung", validated: "Validiert", summary: "Die Status zeigen die Produktphase und führen zu den vollständigen Details.", disclaimer: "Der Produktstatus garantiert keine universelle Funktion auf Ihrem Computer." },
  it: { nav: "Roadmap", title: "Roadmap delle intenzioni", statusLabel: "STATO DEL PRODOTTO", planning: "In pianificazione", building: "In sviluppo", validated: "Convalidata", summary: "Gli stati mostrano la fase del prodotto e portano ai dettagli completi.", disclaimer: "Lo stato del prodotto non garantisce il funzionamento universale sul tuo computer." },
  ru: { nav: "Дорожная карта", title: "Дорожная карта намерений", statusLabel: "СТАТУС ПРОДУКТА", planning: "В планировании", building: "В разработке", validated: "Проверено", summary: "Статусы показывают этап продукта и ведут к полным сведениям.", disclaimer: "Статус продукта не гарантирует универсальную работу на вашем компьютере." },
  "zh-CN": { nav: "路线图", title: "意向路线图", statusLabel: "产品状态", planning: "规划中", building: "开发中", validated: "已验证", summary: "状态显示产品阶段，并可查看完整详情。", disclaimer: "产品状态并不保证在您的计算机上普遍可用。" },
  ja: { nav: "ロードマップ", title: "意図のロードマップ", statusLabel: "製品ステータス", planning: "計画中", building: "開発中", validated: "検証済み", summary: "ステータスは製品段階を示し、詳細へ進めます。", disclaimer: "製品ステータスは、お使いのコンピュータでの普遍的な動作を保証しません。" },
  ko: { nav: "로드맵", title: "의도 로드맵", statusLabel: "제품 상태", planning: "계획 중", building: "개발 중", validated: "검증됨", summary: "상태는 제품 단계를 보여 주며 전체 세부 정보로 연결됩니다.", disclaimer: "제품 상태는 사용자의 컴퓨터에서 보편적인 작동을 보장하지 않습니다." },
  ar: { nav: "خارطة الطريق", title: "خارطة طريق النوايا", statusLabel: "حالة المنتج", planning: "قيد التخطيط", building: "قيد التطوير", validated: "تم التحقق", summary: "توضح الحالات مرحلة المنتج وتقود إلى التفاصيل الكاملة.", disclaimer: "حالة المنتج لا تضمن عملاً شاملاً على جهاز الكمبيوتر الخاص بك." },
};
